// Confederation Lili insights — translated for all 11 languages.
// Structure mirrors LILI_INSIGHTS and CONF_RACE_STAGE_INSIGHTS from confederationData.ts.

import type { LangCode } from './i18n';
import type { Federation } from './wcData';

// ─── Per-confederation Lili momentum analysis ──────────────────────────────────

export const LILI_INSIGHTS_I18N: Record<LangCode, Record<Federation, string>> = {
  EN: {
    UEFA:     "Europe enters 2026 as the undisputed power centre — 16 slots, extraordinary tactical depth. Yet a paradox emerges: club football has outpaced international transition patterns. France and Spain carry the clearest momentum signals entering the cycle. Germany's pressing intensity has resurged at precisely the right moment. Lili tracks one recurring vulnerability: European sides historically underperform against high-tempo CONMEBOL pressing in knockout conditions.",
    CONMEBOL: "South America's six-team presence belies its gravitational weight — Argentina and Brazil absorb roughly 80% of the confederation's tournament probability mass. Colombia and Uruguay carry the continent's high-press tradition intelligently, but remain structurally distant from the top two. Chile and Ecuador represent admirable qualifiers. Their group-stage path decisions will determine whether CONMEBOL once again dominates the semi-final bracket.",
    CAF:      "Africa's eight-team contingent is the largest in tournament history. Morocco has permanently redefined what African football can achieve at this level — their 2022 run was not an outlier, it was a signal. Senegal arrives with defensive intelligence that rivals Europe's mid-tier. Across the bloc, late-game fitness management and set-piece vulnerability remain systemic patterns Lili weights carefully. The continent's ceiling is rising. The floor remains uneven.",
    AFC:      "Asia's six representatives show the widest internal strength differential of any confederation in 2026. Japan remains the continental outlier — structured high press, superior transition patterns, consistent overperformance against pre-tournament expectation. South Korea carries individual quality in advanced zones. The remaining AFC sides face structural challenges in a 48-team format that demands consistency across three group games before knockout pressure arrives.",
    CONCACAF: "Hosting advantage is a compound variable Lili weights carefully: crowd familiarity, reduced travel fatigue, climate acclimatisation, and subtle officiating patterns tilt marginally toward USA, Canada, and Mexico. USA arrives meaningfully stronger than 2022 — this is not a rotation squad. Mexico faces a deeper identity question around press resistance entering a new cycle. Canada, now a maturing debut generation, holds genuine knockout ambitions the data supports.",
    OFC:      "New Zealand enters as the tournament's longest statistical outsider. One qualification path, a compressed competitive calendar, and a strength ceiling well below the tournament median create a steep gradient. Lili identifies one counterweight: Group H offers a narrow but analysable path to third place. Against the probable trajectory, New Zealand's greatest asset may be the absence of expectation — and the ability to operate without the weight of it.",
  },

  FR: {
    UEFA:     "L'Europe entre en 2026 comme le centre de pouvoir incontesté — 16 places, une profondeur tactique extraordinaire. Pourtant un paradoxe émerge : le football de club a dépassé les schémas de transition internationale. La France et l'Espagne portent les signaux de momentum les plus clairs en entrant dans le cycle. L'intensité du pressing allemand a resurgi au bon moment. Lili identifie une vulnérabilité récurrente : les équipes européennes sous-performent historiquement face au pressing CONMEBOL à haute cadence en phase éliminatoire.",
    CONMEBOL: "La présence de six équipes d'Amérique du Sud dissimule son poids gravitationnel — l'Argentine et le Brésil absorbent environ 80 % de la masse de probabilité du tournoi de la confédération. La Colombie et l'Uruguay portent intelligemment la tradition de pressing élevé du continent, mais restent structurellement éloignés des deux premiers. Le Chili et l'Équateur représentent d'admirables qualifiés. Leurs décisions de parcours en phase de groupes détermineront si la CONMEBOL domine une fois de plus le tableau des demi-finales.",
    CAF:      "Le contingent de huit équipes africaines est le plus important de l'histoire du tournoi. Le Maroc a redéfini de façon permanente ce que le football africain peut accomplir à ce niveau — leur parcours de 2022 n'était pas une anomalie, c'était un signal. Le Sénégal arrive avec une intelligence défensive qui rivalise avec le deuxième échelon européen. À travers le bloc, la gestion de la forme en fin de match et la vulnérabilité sur coups de pied arrêtés restent des schémas systémiques que Lili pondère attentivement. Le plafond du continent monte. Le plancher reste inégal.",
    AFC:      "Les six représentants asiatiques montrent le différentiel de force interne le plus large de toutes les confédérations en 2026. Le Japon reste l'outsider continental — pressing structuré, schémas de transition supérieurs, surperformance constante face aux attentes d'avant-tournoi. La Corée du Sud porte une qualité individuelle dans les zones avancées. Les autres équipes AFC font face à des défis structurels dans un format à 48 équipes qui exige de la régularité sur trois matchs de groupe avant que la pression éliminatoire n'arrive.",
    CONCACAF: "L'avantage de l'accueil est une variable composée que Lili pondère soigneusement : familiarité avec le public, fatigue de déplacement réduite, acclimatation climatique et tendances arbitrales subtiles inclinent marginalement vers les États-Unis, le Canada et le Mexique. Les États-Unis arrivent significativement plus forts qu'en 2022 — ce n'est pas une équipe de rotation. Le Mexique fait face à une question identitaire plus profonde autour de la résistance au pressing en entrant dans un nouveau cycle. Le Canada, désormais une génération de début mûrissante, nourrit de véritables ambitions éliminatoires que les données soutiennent.",
    OFC:      "La Nouvelle-Zélande entre comme le plus grand outsider statistique du tournoi. Un seul chemin de qualification, un calendrier compétitif compressé et un plafond de force bien en dessous de la médiane du tournoi créent un gradient raide. Lili identifie un contrepoids : le Groupe H offre une voie étroite mais analysable vers la troisième place. Face à la trajectoire probable, le plus grand atout de la Nouvelle-Zélande est peut-être l'absence d'attentes — et la capacité d'opérer sans le poids de celles-ci.",
  },

  IT: {
    UEFA:     "L'Europa entra nel 2026 come il centro di potere indiscusso — 16 posti, straordinaria profondità tattica. Emerge però un paradosso: il calcio di club ha superato i modelli di transizione internazionale. Francia e Spagna portano i segnali di momentum più chiari nell'entrare nel ciclo. L'intensità del pressing tedesco è riemersa nel momento giusto. Lili individua una vulnerabilità ricorrente: le squadre europee storicamente sottoperformano contro il pressing ad alta velocità della CONMEBOL nelle fasi eliminatorie.",
    CONMEBOL: "La presenza di sei squadre sudamericane nasconde il suo peso gravitazionale — Argentina e Brasile assorbono circa l'80% della massa di probabilità del torneo della confederazione. Colombia e Uruguay portano intelligentemente la tradizione del pressing alto del continente, ma rimangono strutturalmente lontani dalle prime due. Cile ed Ecuador rappresentano degni qualificati. Le loro decisioni nel percorso della fase a gironi determineranno se la CONMEBOL dominerà ancora il tabellone delle semifinali.",
    CAF:      "Il contingente di otto squadre africane è il più grande della storia del torneo. Il Marocco ha ridefinito permanentemente ciò che il calcio africano può ottenere a questo livello — il loro percorso del 2022 non era un'anomalia, era un segnale. Il Senegal arriva con un'intelligenza difensiva che rivaleggia con il livello medio europeo. In tutto il blocco, la gestione della condizione nel finale di partita e la vulnerabilità sui calci piazzati rimangono schemi sistemici che Lili valuta attentamente. Il soffitto del continente si sta alzando. Il pavimento rimane irregolare.",
    AFC:      "I sei rappresentanti asiatici mostrano il più ampio differenziale di forza interna di qualsiasi confederazione nel 2026. Il Giappone rimane l'outsider continentale — pressing strutturato, schemi di transizione superiori, costante sovra-performance rispetto alle aspettative pre-torneo. La Corea del Sud porta qualità individuale nelle zone avanzate. Le restanti squadre AFC affrontano sfide strutturali in un formato a 48 squadre che richiede costanza in tre partite del girone prima che arrivi la pressione eliminatoria.",
    CONCACAF: "Il vantaggio del paese ospitante è una variabile composta che Lili valuta attentamente: familiarità con il pubblico, ridotta stanchezza da viaggio, acclimatazione climatica e sottili tendenze arbitrali inclinano marginalmente verso USA, Canada e Messico. Gli USA arrivano significativamente più forti del 2022 — non è una squadra di rotazione. Il Messico affronta una questione identitaria più profonda sulla resistenza al pressing entrando in un nuovo ciclo. Il Canada, ora una generazione d'esordio che matura, nutre vere ambizioni eliminatorie che i dati supportano.",
    OFC:      "La Nuova Zelanda entra come il più grande outsider statistico del torneo. Un unico percorso di qualificazione, un calendario competitivo compresso e un soffitto di forza ben al di sotto della mediana del torneo creano un gradiente ripido. Lili identifica un contrappeso: il Gruppo H offre un percorso stretto ma analizzabile verso il terzo posto. Contro la probabile traiettoria, il più grande punto di forza della Nuova Zelanda potrebbe essere l'assenza di aspettative — e la capacità di operare senza il peso di esse.",
  },

  DE: {
    UEFA:     "Europa tritt 2026 als unbestrittenes Machtzentrum an — 16 Plätze, außerordentliche taktische Tiefe. Doch ein Paradoxon entsteht: Der Klubfußball hat die internationalen Übergangsmuster überholt. Frankreich und Spanien tragen die klarsten Momentumsignale in den Zyklus. Deutschlands Pressing-Intensität ist genau zum richtigen Zeitpunkt wieder aufgelebt. Lili verfolgt eine wiederkehrende Schwachstelle: Europäische Mannschaften unterperformen historisch gegen das hochtemporige CONMEBOL-Pressing in Knockout-Bedingungen.",
    CONMEBOL: "Die Präsenz von sechs südamerikanischen Teams verschleiert ihr Gravitationsgewicht — Argentinien und Brasilien absorbieren etwa 80% der Turnier-Wahrscheinlichkeitsmasse der Konföderation. Kolumbien und Uruguay tragen die Hochdruck-Tradition des Kontinents intelligent weiter, bleiben aber strukturell weit von den Top Zwei entfernt. Chile und Ecuador sind bewundernswerte Qualifikanten. Ihre Entscheidungen im Gruppenphase-Weg werden bestimmen, ob CONMEBOL wieder das Halbfinale dominiert.",
    CAF:      "Afrikas Acht-Teams-Kontingent ist das größte in der Turniergeschichte. Marokko hat dauerhaft neu definiert, was der afrikanische Fußball auf diesem Niveau erreichen kann — ihr Lauf 2022 war kein Ausreißer, sondern ein Signal. Senegal kommt mit defensiver Intelligenz, die mit Europas mittlerem Niveau rivalisiert. Im gesamten Block bleiben späte Fitness-Verwaltung und Standardsituationsvulnerabilität systemische Muster, die Lili sorgfältig gewichtet. Die Decke des Kontinents steigt. Der Boden bleibt uneben.",
    AFC:      "Asiens sechs Vertreter zeigen die breiteste interne Stärkendifferenz aller Konföderationen 2026. Japan bleibt der kontinentale Außenseiter — strukturiertes Hochpressing, überlegene Übergangsmuster, konsistente Überperformance gegenüber Vorturnier-Erwartungen. Südkorea trägt individuelle Qualität in fortgeschrittenen Zonen. Die übrigen AFC-Seiten stehen vor strukturellen Herausforderungen in einem 48-Teams-Format, das Konsistenz über drei Gruppenspiele erfordert, bevor Knockout-Druck entsteht.",
    CONCACAF: "Der Heimvorteil ist eine zusammengesetzte Variable, die Lili sorgfältig gewichtet: Publikumsvertrautheit, reduzierte Reisemüdigkeit, Klimaakklimatisierung und subtile Schieds-Muster neigen marginal zu USA, Kanada und Mexiko. Die USA treten deutlich stärker als 2022 an — das ist kein Rotationskader. Mexiko steht vor einer tieferen Identitätsfrage rund um die Pressing-Resistenz beim Eintritt in einen neuen Zyklus. Kanada, jetzt eine reifende Debüt-Generation, hegt echte Knockout-Ambitionen, die die Daten unterstützen.",
    OFC:      "Neuseeland tritt als der längste statistische Außenseiter des Turniers an. Ein einziger Qualifikationspfad, ein komprimierter Wettbewerbskalender und eine Stärkedecke weit unter dem Turnier-Median schaffen ein steiles Gefälle. Lili identifiziert ein Gegengewicht: Gruppe H bietet einen engen, aber analysierbaren Weg zum dritten Platz. Gegen die wahrscheinliche Entwicklung könnte Neuseelands größtes Kapital das Fehlen von Erwartungen sein — und die Fähigkeit, ohne deren Gewicht zu operieren.",
  },

  ES: {
    UEFA:     "Europa entra en 2026 como el centro de poder indiscutible — 16 plazas, extraordinaria profundidad táctica. Sin embargo, emerge una paradoja: el fútbol de clubes ha superado los patrones de transición internacional. Francia y España llevan las señales de impulso más claras al entrar en el ciclo. La intensidad del pressing alemán ha resurgido en el momento preciso. Lili detecta una vulnerabilidad recurrente: los equipos europeos históricamente rinden por debajo contra el pressing de alta cadencia de la CONMEBOL en condiciones eliminatorias.",
    CONMEBOL: "La presencia de seis equipos sudamericanos oculta su peso gravitacional — Argentina y Brasil absorben aproximadamente el 80% de la masa de probabilidad del torneo de la confederación. Colombia y Uruguay llevan inteligentemente la tradición del pressing alto del continente, pero permanecen estructuralmente alejados de los dos primeros. Chile y Ecuador representan clasificados admirables. Sus decisiones de trayectoria en la fase de grupos determinarán si la CONMEBOL vuelve a dominar el cuadro de semifinales.",
    CAF:      "El contingente de ocho equipos de África es el mayor en la historia del torneo. Marruecos ha redefinido permanentemente lo que el fútbol africano puede lograr a este nivel — su recorrido de 2022 no fue una anomalía, fue una señal. Senegal llega con inteligencia defensiva que rivaliza con el nivel medio europeo. En todo el bloque, la gestión de la condición física al final del partido y la vulnerabilidad a los balones parados siguen siendo patrones sistémicos que Lili pondera cuidadosamente. El techo del continente está subiendo. El suelo sigue siendo irregular.",
    AFC:      "Los seis representantes asiáticos muestran el diferencial de fuerza interno más amplio de cualquier confederación en 2026. Japón sigue siendo el outsider continental — pressing estructurado de alta intensidad, patrones de transición superiores, sobrerrendimiento constante respecto a las expectativas pre-torneo. Corea del Sur aporta calidad individual en zonas avanzadas. Los demás equipos de la AFC enfrentan desafíos estructurales en un formato de 48 equipos que exige consistencia en tres partidos de grupo antes de que llegue la presión eliminatoria.",
    CONCACAF: "La ventaja de ser anfitrión es una variable compuesta que Lili pondera cuidadosamente: familiaridad con el público, reducción de la fatiga por viaje, aclimatación climática y sutiles patrones arbitrales inclinan marginalmente hacia EE.UU., Canadá y México. EE.UU. llega significativamente más fuerte que en 2022 — no es un equipo de rotación. México enfrenta una pregunta identitaria más profunda sobre la resistencia al pressing al entrar en un nuevo ciclo. Canadá, ahora una generación debutante en maduración, alberga genuinas ambiciones eliminatorias que los datos respaldan.",
    OFC:      "Nueva Zelanda entra como el mayor outsider estadístico del torneo. Un único camino de clasificación, un calendario competitivo comprimido y un techo de fuerza muy por debajo de la mediana del torneo crean un gradiente empinado. Lili identifica un contrapeso: el Grupo H ofrece un camino estrecho pero analizable hacia el tercer lugar. Ante la trayectoria probable, el mayor activo de Nueva Zelanda puede ser la ausencia de expectativas — y la capacidad de operar sin su peso.",
  },

  RU: {
    UEFA:     "Европа входит в 2026 год как неоспоримый центр силы — 16 мест, исключительная тактическая глубина. Однако возникает парадокс: клубный футбол опередил международные переходные паттерны. Франция и Испания несут самые чёткие сигналы импульса в этот цикл. Интенсивность прессинга Германии восстановилась именно в нужный момент. Лили отслеживает одну повторяющуюся уязвимость: европейские команды исторически уступают высокотемповому прессингу КОНМЕБОЛ в условиях плей-офф.",
    CONMEBOL: "Присутствие шести команд Южной Америки скрывает её гравитационный вес — Аргентина и Бразилия поглощают около 80% турнирной вероятностной массы конфедерации. Колумбия и Уругвай умело несут традицию высокого прессинга континента, но структурно остаются далеко от двух лидеров. Чили и Эквадор — достойные квалифицировавшиеся команды. Их решения о пути в групповом этапе определят, будет ли КОНМЕБОЛ снова доминировать в сетке полуфиналов.",
    CAF:      "Восемь команд Африки — крупнейший контингент в истории турнира. Марокко навсегда переопределило, чего африканский футбол может достичь на этом уровне — их путь в 2022 году был не аномалией, а сигналом. Сенегал приходит с оборонительным интеллектом, который конкурирует со средним уровнем Европы. По всему блоку управление физической формой в конце матча и уязвимость к стандартным положениям остаются системными паттернами, которые Лили тщательно взвешивает. Потолок континента растёт. Пол остаётся неровным.",
    AFC:      "Шесть представителей Азии демонстрируют наибольший внутренний разрыв в силе среди всех конфедераций в 2026 году. Япония остаётся континентальным аутсайдером — структурированный высокий прессинг, превосходные переходные паттерны, неизменное превышение дотурнирных ожиданий. Южная Корея несёт индивидуальное качество в продвинутых зонах. Остальные команды АФК сталкиваются со структурными вызовами в формате с 48 командами, требующем последовательности в трёх групповых матчах до наступления давления плей-офф.",
    CONCACAF: "Преимущество принимающей страны — составная переменная, которую Лили тщательно взвешивает: близость к публике, сниженная усталость от дороги, климатическая акклиматизация и тонкие судейские паттерны незначительно склоняются в пользу США, Канады и Мексики. США приходят значительно сильнее, чем в 2022 году — это не ротационный состав. Мексика сталкивается с более глубоким вопросом идентичности вокруг сопротивления прессингу в начале нового цикла. Канада, ныне взрослеющее дебютное поколение, питает реальные амбиции в плей-офф, которые поддерживают данные.",
    OFC:      "Новая Зеландия входит как самый длинный статистический аутсайдер турнира. Один путь квалификации, сжатый соревновательный календарь и потолок силы значительно ниже медианы турнира создают крутой градиент. Лили определяет одно противовесное обстоятельство: Группа H предлагает узкий, но поддающийся анализу путь к третьему месту. Против вероятной траектории, главным активом Новой Зеландии может быть отсутствие ожиданий — и способность работать без их груза.",
  },

  CN: {
    UEFA:     "欧洲以无可争议的权力中心姿态进入2026年——16个名额，非凡的战术深度。然而一个悖论浮现：俱乐部足球已超越国际过渡模式。法国和西班牙在进入本周期时携带着最清晰的势头信号。德国的逼抢强度在恰当时机复苏。Lili追踪到一个反复出现的弱点：欧洲球队在淘汰赛条件下面对南美联合会高节奏逼抢时历史性地表现不佳。",
    CONMEBOL: "南美六支球队的存在掩盖了其引力权重——阿根廷和巴西吸收了联合会约80%的赛事概率质量。哥伦比亚和乌拉圭聪明地延续了大陆高压传统，但在结构上与前两名仍有较大差距。智利和厄瓜多尔是令人钦佩的晋级者。他们在小组赛阶段的路线决策将决定南美联合会是否再次主导半决赛格局。",
    CAF:      "非洲八支球队是赛事历史上最多的。摩洛哥永久重新定义了非洲足球在这一级别所能实现的成就——他们2022年的表现并非异常，而是一个信号。塞内加尔带来了可与欧洲中档球队媲美的防守智慧。在整个集团中，比赛后期的体能管理和定位球弱点仍是Lili仔细权衡的系统性模式。非洲足球的上限正在提升，但下限依然参差不齐。",
    AFC:      "亚洲六支代表队在2026年展示了所有联合会中最宽泛的内部实力差距。日本依然是大陆上的异数——结构化高位逼抢、出色的过渡模式、持续超越赛前预期。韩国在前场区域具备个人质量。其余亚足联球队在48支球队格局中面临结构性挑战，这一格局要求在淘汰赛压力到来之前保持三场小组赛的稳定性。",
    CONCACAF: "东道主优势是Lili仔细权衡的复合变量：观众熟悉度、减少的差旅疲劳、气候适应以及微妙的裁判模式，这些因素微弱地倾向于美国、加拿大和墨西哥。美国的到来明显比2022年更强——这不是一支轮换阵容。墨西哥在进入新周期时面临更深层的关于抗压能力的身份问题。加拿大作为一个成熟中的首次参赛世代，拥有数据支持的真实淘汰赛雄心。",
    OFC:      "新西兰作为赛事最大的统计局外人参赛。单一资格路径、紧凑的竞技赛历以及远低于赛事中位数的实力上限构成了陡峭的梯度。Lili发现一个反制因素：H组提供了通往第三名的狭窄但可分析的路径。与可能的轨迹相比，新西兰最大的资产或许是没有期望的束缚——以及在没有这一重量下运作的能力。",
  },

  JP: {
    UEFA:     "ヨーロッパは2026年に揺るぎないパワーセンターとして参入 — 16スロット、並外れた戦術的深さ。しかしパラドックスが生じている：クラブサッカーが国際的な移行パターンを上回っている。フランスとスペインはサイクル入りにあたり最も明確なモメンタムシグナルを持つ。ドイツのプレッシング強度はまさに適切なタイミングで復活した。Liliはある繰り返しの脆弱性を追跡している：ヨーロッパ勢はノックアウト条件下でCONMEBOLの高テンポプレッシングに対して歴史的に苦戦している。",
    CONMEBOL: "南米の6チームの存在はその重力的な重みを覆い隠している — アルゼンチンとブラジルがコンフェデレーションのトーナメント確率の約80%を吸収している。コロンビアとウルグアイは大陸のハイプレス伝統を知的に継承しているが、上位2チームとは構造的に距離がある。チリとエクアドルは立派な出場国だ。グループステージのパス選択がCONMEBOLが再び準決勝トーナメントを支配するかを決める。",
    CAF:      "アフリカの8チームはトーナメント史上最大のコンティンジェントだ。モロッコはアフリカサッカーがこのレベルで達成できることを永久に再定義した — 2022年の躍進は異常値ではなく、シグナルだった。セネガルはヨーロッパ中位に匹敵する守備的インテリジェンスをもって参入する。ブロック全体で、試合終盤のフィットネス管理とセットプレーの脆弱性はLiliが慎重に重みづけする体系的なパターンとして残っている。大陸の上限は上昇している。床は不均一なままだ。",
    AFC:      "アジアの6代表は2026年のすべてのコンフェデレーションの中で最も広い内部強度差を示している。日本は大陸の外れ値であり続ける — 構造化されたハイプレス、優れた移行パターン、前大会予想に対する一貫したオーバーパフォーマンス。韓国は前線のエリアで個人的な質を持つ。残りのAFC勢は、ノックアウト圧力が来る前に3試合の安定性を要求する48チーム形式において構造的な課題に直面している。",
    CONCACAF: "開催地の優位性はLiliが慎重に重みづけする複合変数だ：観客との親しみ、移動疲労の軽減、気候順応、そして微妙な審判パターンが、米国、カナダ、メキシコに若干傾いている。米国は2022年より意味ある形で強くなって参加 — これはローテーションスカッドではない。メキシコは新サイクル入りにあたりプレッシング耐性に関してより深いアイデンティティの問いに直面している。カナダは今や熟成するデビュー世代として、データが支持する真のノックアウト野心を持っている。",
    OFC:      "ニュージーランドはトーナメントで最も長い統計的外れ値として参入する。1つの資格経路、圧縮された競技カレンダー、そしてトーナメント中央値を大きく下回る強度の上限が急勾配を生み出している。Liliは1つのカウンターウェイトを特定している：グループHは3位へのわずかだが分析可能な道を提供している。おそらくの軌道に対し、ニュージーランドの最大の資産は期待の不在 — そしてその重みなしに動ける能力かもしれない。",
  },

  KR: {
    UEFA:     "유럽은 2026년에 논란의 여지 없는 힘의 중심으로 진입합니다 — 16개 슬롯, 비범한 전술적 깊이. 그러나 역설이 나타납니다: 클럽 축구가 국제적 전환 패턴을 앞질렀습니다. 프랑스와 스페인이 이 사이클에 들어서며 가장 명확한 모멘텀 신호를 보냅니다. 독일의 프레싱 강도가 정확히 적절한 시점에 부활했습니다. Lili는 반복되는 취약점을 추적합니다: 유럽 팀들은 역사적으로 노크아웃 조건에서 남미연맹의 고속 프레싱에 약한 모습을 보입니다.",
    CONMEBOL: "6개 남미 팀의 존재는 중력적 무게를 숨깁니다 — 아르헨티나와 브라질이 연맹의 토너먼트 확률 질량의 약 80%를 흡수합니다. 콜롬비아와 우루과이는 대륙의 고압 전통을 지능적으로 이어가지만 구조적으로 상위 두 팀과 거리가 있습니다. 칠레와 에콰도르는 훌륭한 진출팀입니다. 조별 리그 경로 결정이 남미연맹이 다시 한번 준결승 대진을 지배할지를 결정합니다.",
    CAF:      "아프리카의 8개 팀 진용은 토너먼트 역사상 최대입니다. 모로코는 이 수준에서 아프리카 축구가 달성할 수 있는 것을 영구적으로 재정의했습니다 — 2022년 여정은 이상치가 아니라 신호였습니다. 세네갈은 유럽 중위권에 필적하는 수비 지능을 갖추고 참가합니다. 블록 전체에서 경기 후반 체력 관리와 세트피스 취약성은 Lili가 신중하게 가중치를 부여하는 체계적 패턴으로 남아 있습니다. 대륙의 상한선은 높아지고 있습니다. 하한선은 여전히 불균일합니다.",
    AFC:      "아시아의 6개 대표팀은 2026년 모든 연맹 중 가장 넓은 내부 전력 차이를 보여줍니다. 일본은 대륙의 아웃라이어로 남아 있습니다 — 구조화된 고압 프레싱, 우수한 전환 패턴, 대회 전 기대치를 꾸준히 초과 달성합니다. 한국은 전방 구역에서 개인 능력을 갖추고 있습니다. 나머지 AFC 팀들은 노크아웃 압박이 오기 전에 세 경기에서 일관성을 요구하는 48팀 형식에서 구조적 과제에 직면합니다.",
    CONCACAF: "개최국 이점은 Lili가 신중하게 가중치를 부여하는 복합 변수입니다: 관중 친숙도, 감소된 이동 피로, 기후 적응, 미묘한 심판 패턴이 미국, 캐나다, 멕시코에게 미미하게 기울어집니다. 미국은 2022년보다 의미있게 강해진 상태로 참가합니다 — 로테이션 팀이 아닙니다. 멕시코는 새 사이클에 들어서며 프레싱 저항과 관련된 더 깊은 정체성 문제에 직면합니다. 캐나다는 이제 성숙해가는 데뷔 세대로서 데이터가 지지하는 진정한 노크아웃 야심을 품고 있습니다.",
    OFC:      "뉴질랜드는 토너먼트에서 가장 긴 통계적 아웃사이더로 진입합니다. 단 하나의 자격 경로, 압축된 경쟁 일정, 토너먼트 중앙값보다 훨씬 낮은 전력 상한이 가파른 기울기를 만들어냅니다. Lili는 하나의 반대 요인을 파악합니다: H조가 3위를 향한 좁지만 분석 가능한 경로를 제공합니다. 예상 궤적에 반하여, 뉴질랜드의 가장 큰 자산은 기대의 부재 — 그리고 그 무게 없이 운영할 수 있는 능력일 수 있습니다.",
  },

  PT: {
    UEFA:     "A Europa entra em 2026 como o centro de poder indisputável — 16 vagas, profundidade tática extraordinária. No entanto, emerge um paradoxo: o futebol de clubes superou os padrões de transição internacional. França e Espanha carregam os sinais de momentum mais claros ao entrar no ciclo. A intensidade do pressing alemão ressurgiu precisamente no momento certo. Lili rastreia uma vulnerabilidade recorrente: as equipas europeias historicamente ficam abaixo do esperado contra o pressing de alto ritmo da CONMEBOL em condições de eliminatória.",
    CONMEBOL: "A presença de seis equipas sul-americanas dissimula o seu peso gravitacional — Argentina e Brasil absorvem aproximadamente 80% da massa de probabilidade do torneio da confederação. Colômbia e Uruguai carregam inteligentemente a tradição do pressing alto do continente, mas permanecem estruturalmente distantes dos dois primeiros. Chile e Equador representam qualificados admiráveis. As suas decisões de percurso na fase de grupos determinarão se a CONMEBOL volta a dominar o quadro das meias-finais.",
    CAF:      "O contingente de oito equipas africanas é o maior da história do torneio. Marrocos redefiniu permanentemente o que o futebol africano pode alcançar a este nível — a sua campanha de 2022 não foi uma anomalia, foi um sinal. O Senegal chega com inteligência defensiva que rivaliza com o nível médio europeu. Em todo o bloco, a gestão da condição física no final do jogo e a vulnerabilidade nos cantos e livres continuam a ser padrões sistémicos que Lili pondera cuidadosamente. O teto do continente está a subir. O piso permanece irregular.",
    AFC:      "Os seis representantes da Ásia mostram o maior diferencial de força interno de qualquer confederação em 2026. O Japão continua a ser o outlier continental — pressing estruturado de alta intensidade, padrões de transição superiores, superação constante das expectativas pré-torneio. A Coreia do Sul tem qualidade individual em zonas avançadas. As restantes equipas da AFC enfrentam desafios estruturais num formato de 48 equipas que exige consistência em três jogos de grupo antes de chegar a pressão eliminatória.",
    CONCACAF: "A vantagem de acolher é uma variável composta que Lili pondera cuidadosamente: familiaridade do público, redução da fadiga de viagem, aclimatação climática e subtis padrões de arbitragem inclinam marginalmente para os EUA, Canadá e México. Os EUA chegam significativamente mais fortes do que em 2022 — não é um plantel de rotação. O México enfrenta uma questão identitária mais profunda sobre a resistência ao pressing ao entrar num novo ciclo. O Canadá, agora uma geração estreante em maturação, tem ambições eliminatórias genuínas que os dados suportam.",
    OFC:      "A Nova Zelândia entra como o maior outsider estatístico do torneio. Um único caminho de qualificação, um calendário competitivo comprimido e um teto de força muito abaixo da mediana do torneio criam um gradiente acentuado. Lili identifica um contrapeso: o Grupo H oferece um caminho estreito mas analisável para o terceiro lugar. Contra a trajetória provável, o maior ativo da Nova Zelândia pode ser a ausência de expectativas — e a capacidade de operar sem o seu peso.",
  },

  AR: {
    UEFA:     "تدخل أوروبا عام 2026 بوصفها مركز القوة الذي لا يُنازع — 16 مقعداً، عمقاً تكتيكياً استثنائياً. غير أن مفارقة تبرز: تجاوز كرة القدم في الأندية أنماط الانتقال الدولي. تحمل فرنسا وإسبانيا أوضح إشارات الزخم في الدخول إلى الدورة. عادت كثافة ضغط ألمانيا بقوة في اللحظة المناسبة تماماً. تتتبع ليلي نقطة ضعف متكررة: الفرق الأوروبية تؤدي أداءً أدنى من المتوقع تاريخياً في مواجهة الضغط العالي لكونميبول في مباريات الإقصاء.",
    CONMEBOL: "حضور ستة فرق من أمريكا الجنوبية يخفي ثقلها الجذبي — تمتص الأرجنتين والبرازيل نحو 80% من الكتلة الاحتمالية لبطولة الاتحاد. تحمل كولومبيا وأوروغواي تقليد الضغط العالي للقارة بذكاء، لكنهما تبقيان بُنيوياً بعيدتين عن القمتين. تشيلي والإكوادور مؤهلتان لافتتان. ستحدد قراراتهما في المسار خلال دور المجموعات ما إذا كانت كونميبول ستهيمن مجدداً على ربع نهائي البطولة.",
    CAF:      "يُعدّ وفد أفريقيا المؤلف من ثماني فرق الأكبر في تاريخ البطولة. أعادت المغرب تعريف ما يمكن لكرة القدم الأفريقية تحقيقه على هذا المستوى بصورة دائمة — مسيرتها في 2022 لم تكن استثناءً، بل كانت إشارة. يأتي السنغال بذكاء دفاعي يُنافس المستوى الأوروبي المتوسط. عبر الكتلة، تظل إدارة اللياقة في أواخر المباراة وهشاشة الكرات الثابتة أنماطاً منهجية تُقيّمها ليلي بعناية. سقف القارة يرتفع. أرضيتها لا تزال غير متساوية.",
    AFC:      "يُظهر الممثلون الستة لآسيا أوسع فجوة داخلية في القوة بين جميع الاتحادات في 2026. تبقى اليابان استثناءً قارياً — ضغط عالٍ منظم، أنماط انتقال متفوقة، أداء يتجاوز التوقعات ما قبل البطولة باستمرار. تحمل كوريا الجنوبية جودة فردية في المناطق المتقدمة. تواجه فرق الاتحاد الآسيوي المتبقية تحديات بنيوية في صيغة مؤلفة من 48 فريقاً تتطلب الاتساق في ثلاث مباريات جماعية قبل وصول ضغط الإقصاء.",
    CONCACAF: "ميزة الاستضافة متغير مركّب تُقيّمه ليلي بعناية: ألفة الجمهور، وتقليل إجهاد التنقل، والتأقلم المناخي، والأنماط التحكيمية الدقيقة، تنحاز قليلاً نحو الولايات المتحدة وكندا والمكسيك. تأتي الولايات المتحدة أقوى بشكل ملموس مما كانت عليه في 2022 — هذه ليست تشكيلة تناوب. تواجه المكسيك تساؤلاً أعمق حول هويتها في مقاومة الضغط عند الدخول في دورة جديدة. أما كندا، وهي جيل مبتدئ يتطور، فتحمل طموحات إقصاء حقيقية تدعمها البيانات.",
    OFC:      "تدخل نيوزيلندا بوصفها أكبر حصان أسود إحصائي في البطولة. مسار تأهل وحيد، وتقويم تنافسي مضغوط، وسقف قوة أدنى بكثير من متوسط البطولة تخلق تدرجاً حاداً. تُحدد ليلي موازناً واحداً: يقدم المجموعة H مساراً ضيقاً لكنه قابل للتحليل نحو المركز الثالث. في مواجهة المسار المحتمل، قد يكون أكبر ميزة لنيوزيلندا غياب التوقعات — والقدرة على العمل دون ثقلها.",
  },
};

// ─── Per-stage confederation race insights ────────────────────────────────────

export const CONF_RACE_INSIGHTS_I18N: Record<LangCode, string[]> = {
  EN: [
    "All 48 nations launch their campaigns. Maximum tournament entropy — Lili reads no confederation as dominant yet. The first matchday establishes momentum, narrative, and early qualification arithmetic.",
    "Patterns crystallise after the first round. UEFA's depth begins to separate the field. African and Asian sides face structural qualification pressure in the second group game — historically their most contested fixture.",
    "Group stage resolution. UEFA and CONMEBOL lock in their projected round of sixteen representation. CAF, AFC, and CONCACAF have narrower paths — but Lili notes that Matchday 3 produces the tournament's highest surprise rate.",
    "The tournament's first real pressure test. Sixteen matches, no draws. UEFA and CONMEBOL dominate this stage statistically. Each CAF or AFC survival at this point represents a historical signal shift — Morocco proved it in 2022.",
    "Eight remain. The quarterfinal stage is where tactical sophistication becomes survival currency. UEFA typically accounts for 5–6 of the eight spots. CONMEBOL holds 2–3. Beyond that, the bracket becomes historically unprecedented territory.",
    "Four teams. The semi-final concentration reveals the tournament's true power landscape. UEFA vs CONMEBOL remains the most common semi-final pairing Lili observes across simulation runs. Every other confederation's presence here is a tournament-defining moment.",
    "The championship stage. Lili's simulation most frequently resolves as a UEFA vs CONMEBOL final, though three of the last five World Cups have produced at least one unexpected finalist. This is the tournament's ultimate intelligence test.",
  ],

  FR: [
    "Les 48 nations lancent leurs campagnes. Entropie maximale du tournoi — Lili ne lit encore aucune confédération comme dominante. La première journée établit le momentum, le récit et l'arithmétique de qualification précoce.",
    "Les schémas se cristallisent après le premier tour. La profondeur de l'UEFA commence à séparer le peloton. Les équipes africaines et asiatiques font face à une pression de qualification structurelle lors du deuxième match de groupe — historiquement leur match le plus disputé.",
    "Résolution de la phase de groupes. L'UEFA et la CONMEBOL confirment leur représentation projetée au tour des seize. La CAF, l'AFC et la CONCACAF ont des chemins plus étroits — mais Lili note que la Journée 3 produit le taux de surprise le plus élevé du tournoi.",
    "Le premier vrai test de pression du tournoi. Seize matchs, sans nul. L'UEFA et la CONMEBOL dominent statistiquement ce stade. Chaque survie de la CAF ou de l'AFC ici représente un changement de signal historique — le Maroc l'a prouvé en 2022.",
    "Huit équipes restent. Le stade des quarts de finale est là où la sophistication tactique devient la monnaie de survie. L'UEFA compte généralement pour 5 à 6 des huit places. La CONMEBOL en détient 2 à 3. Au-delà, le tableau entre en territoire historiquement sans précédent.",
    "Quatre équipes. La concentration en demi-finale révèle le véritable paysage de puissance du tournoi. UEFA vs CONMEBOL reste le pairage de demi-finale le plus fréquent que Lili observe dans les simulations. La présence de toute autre confédération ici est un moment définissant le tournoi.",
    "La phase de championnat. La simulation de Lili se résout le plus souvent en une finale UEFA vs CONMEBOL, bien que trois des cinq dernières Coupes du Monde aient produit au moins un finaliste inattendu. C'est le test d'intelligence ultime du tournoi.",
  ],

  IT: [
    "Tutte le 48 nazioni lanciano le loro campagne. Entropia massima del torneo — Lili non legge ancora nessuna confederazione come dominante. La prima giornata stabilisce momentum, narrativa e l'aritmetica precoce della qualificazione.",
    "I modelli si cristallizzano dopo il primo turno. La profondità dell'UEFA inizia a separare il gruppo. Le squadre africane e asiatiche affrontano una pressione di qualificazione strutturale nella seconda partita del girone — storicamente il loro match più combattuto.",
    "Risoluzione della fase a gironi. UEFA e CONMEBOL confermano la loro rappresentanza proiettata ai sedicesimi. CAF, AFC e CONCACAF hanno percorsi più stretti — ma Lili nota che la Giornata 3 produce il più alto tasso di sorprese del torneo.",
    "Il primo vero test di pressione del torneo. Sedici partite, nessun pareggio. UEFA e CONMEBOL dominano statisticamente questo stadio. Ogni sopravvivenza della CAF o dell'AFC a questo punto rappresenta uno storico cambiamento di segnale — il Marocco lo ha dimostrato nel 2022.",
    "Otto squadre rimaste. Lo stadio dei quarti di finale è dove la sofisticazione tattica diventa la moneta di sopravvivenza. L'UEFA solitamente occupa 5-6 degli otto posti. La CONMEBOL ne detiene 2-3. Oltre, il tabellone entra in territorio storicamente senza precedenti.",
    "Quattro squadre. La concentrazione in semifinale rivela il vero panorama di potere del torneo. UEFA vs CONMEBOL rimane il pairage di semifinale più comune che Lili osserva nelle simulazioni. La presenza di qualsiasi altra confederazione qui è un momento che definisce il torneo.",
    "La fase del campionato. La simulazione di Lili si risolve più frequentemente come una finale UEFA vs CONMEBOL, sebbene tre degli ultimi cinque Mondiali abbiano prodotto almeno un finalista inaspettato. Questo è il test di intelligenza finale del torneo.",
  ],

  DE: [
    "Alle 48 Nationen starten ihre Kampagnen. Maximale Turnier-Entropie — Lili liest noch keine Konföderation als dominant. Der erste Spieltag etabliert Momentum, Narrativ und frühe Qualifikationsarithmetik.",
    "Muster kristallisieren sich nach der ersten Runde. Die Tiefe der UEFA beginnt, das Feld zu trennen. Afrikanische und asiatische Seiten stehen unter strukturellem Qualifikationsdruck im zweiten Gruppenspiel — historisch ihr umkämpftestes Spiel.",
    "Auflösung der Gruppenphase. UEFA und CONMEBOL sichern ihre prognostizierte Runde-der-Sechzehn-Vertretung. CAF, AFC und CONCACAF haben engere Pfade — aber Lili stellt fest, dass Spieltag 3 die höchste Überraschungsrate des Turniers produziert.",
    "Der erste echte Drucktest des Turniers. Sechzehn Spiele, keine Unentschieden. UEFA und CONMEBOL dominieren diese Phase statistisch. Jedes CAF- oder AFC-Überleben hier repräsentiert einen historischen Signalwechsel — Marokko bewies es 2022.",
    "Acht verbleiben. Die Viertelfinale-Phase ist der Ort, wo taktische Raffinesse zur Überlebenswährung wird. Die UEFA nimmt typischerweise 5-6 der acht Plätze ein. CONMEBOL hält 2-3. Darüber hinaus betritt das Bracket historisch noch nie dagewesenes Terrain.",
    "Vier Teams. Die Halbfinale-Konzentration enthüllt die wahre Machtlandschaft des Turniers. UEFA vs CONMEBOL bleibt das häufigste Halbfinale-Paarung, das Lili in Simulationsläufen beobachtet. Die Anwesenheit jeder anderen Konföderation hier ist ein turnierdefinierender Moment.",
    "Die Meisterschaftsphase. Lilis Simulation löst sich am häufigsten als UEFA vs CONMEBOL-Finale auf, obwohl drei der letzten fünf Weltmeisterschaften mindestens einen unerwarteten Finalisten hervorgebracht haben. Dies ist der ultimative Intelligenztest des Turniers.",
  ],

  ES: [
    "Las 48 naciones lanzan sus campañas. Entropía máxima del torneo — Lili no lee todavía ninguna confederación como dominante. La primera jornada establece el impulso, la narrativa y la aritmética temprana de clasificación.",
    "Los patrones se cristalizan después de la primera ronda. La profundidad de la UEFA comienza a separar el campo. Los equipos africanos y asiáticos enfrentan presión estructural de clasificación en el segundo partido de grupo — históricamente su partido más disputado.",
    "Resolución de la fase de grupos. UEFA y CONMEBOL aseguran su representación proyectada en los dieciseisavos. CAF, AFC y CONCACAF tienen caminos más estrechos — pero Lili señala que la Jornada 3 produce la tasa de sorpresa más alta del torneo.",
    "La primera prueba real de presión del torneo. Dieciséis partidos, sin empates. UEFA y CONMEBOL dominan estadísticamente esta fase. Cada supervivencia de CAF o AFC en este punto representa un cambio histórico de señal — Marruecos lo demostró en 2022.",
    "Quedan ocho. La fase de cuartos de final es donde la sofisticación táctica se convierte en moneda de supervivencia. La UEFA típicamente representa 5-6 de los ocho puestos. CONMEBOL tiene 2-3. Más allá, el cuadro entra en territorio históricamente sin precedentes.",
    "Cuatro equipos. La concentración de las semifinales revela el verdadero panorama de poder del torneo. UEFA vs CONMEBOL sigue siendo el enfrentamiento de semifinal más común que Lili observa en las simulaciones. La presencia de cualquier otra confederación aquí es un momento que define el torneo.",
    "La fase de campeonato. La simulación de Lili se resuelve más frecuentemente como una final UEFA vs CONMEBOL, aunque tres de las últimas cinco Copas del Mundo han producido al menos un finalista inesperado. Este es el test de inteligencia definitivo del torneo.",
  ],

  RU: [
    "Все 48 наций начинают свои кампании. Максимальная турнирная энтропия — Лили ещё не читает ни одну конфедерацию как доминирующую. Первый игровой день устанавливает импульс, нарратив и раннюю квалификационную арифметику.",
    "Паттерны кристаллизуются после первого раунда. Глубина УЕФА начинает разделять поле. Африканские и азиатские команды сталкиваются со структурным квалификационным давлением во втором групповом матче — исторически самом оспариваемом для них.",
    "Разрешение группового этапа. УЕФА и КОНМЕБОЛ закрепляют своё прогнозируемое представительство в раунде шестнадцати. КАФ, АФК и КОНКАКАФ имеют более узкие пути — но Лили отмечает, что Игровой день 3 производит наибольший коэффициент неожиданности в турнире.",
    "Первый реальный тест давления турнира. Шестнадцать матчей, без ничьих. УЕФА и КОНМЕБОЛ статистически доминируют на этой стадии. Каждое выживание КАФ или АФК здесь представляет исторический сдвиг сигнала — Марокко доказало это в 2022 году.",
    "Восемь команд остались. Четвертьфинальная стадия — это место, где тактическая изощрённость становится валютой выживания. УЕФА обычно занимает 5-6 из восьми мест. КОНМЕБОЛ держит 2-3. За этим пределом сетка вступает в исторически беспрецедентную территорию.",
    "Четыре команды. Концентрация полуфинала раскрывает истинный силовой ландшафт турнира. УЕФА против КОНМЕБОЛ остаётся наиболее распространённой парой полуфинала, которую Лили наблюдает в симуляционных прогонах. Присутствие любой другой конфедерации здесь — это момент, определяющий турнир.",
    "Чемпионская стадия. Симуляция Лили чаще всего разрешается как финал УЕФА против КОНМЕБОЛ, хотя три из последних пяти чемпионатов мира произвели хотя бы одного неожиданного финалиста. Это высший тест интеллекта турнира.",
  ],

  CN: [
    "48个国家全部开始了他们的征程。最大赛事熵值——Lili尚未将任何联合会视为主导。第一轮比赛日建立了势头、叙事和早期晋级数学。",
    "第一轮结束后模式开始清晰。欧洲足联的深度开始分离阵营。非洲和亚洲球队在第二场小组赛中面临结构性晋级压力——历史上是他们最具争议的比赛。",
    "小组赛决出。欧洲足联和南美足联确定了他们预计的十六强代表。非洲足联、亚足联和中北美足联的路径更为狭窄——但Lili注意到第3轮比赛日产生了赛事最高的惊喜率。",
    "赛事的第一个真正压力测试。十六场比赛，没有平局。欧洲足联和南美足联在统计上主导了这一阶段。非洲足联或亚足联在这一点上的每次生存都代表着历史性的信号转变——摩洛哥在2022年证明了这一点。",
    "八强出炉。四分之一决赛阶段是战术复杂性成为生存货币的地方。欧洲足联通常占据八个席位中的5-6个。南美足联占有2-3个。超过这个范围，赛事格局进入历史上前所未有的领域。",
    "四支球队。半决赛集中揭示了赛事真实的权力格局。欧洲足联对南美足联仍然是Lili在模拟中观察到的最常见的半决赛配对。任何其他联合会在这里的存在都是定义赛事的时刻。",
    "冠军阶段。Lili的模拟最常以欧洲足联对南美足联决赛告终，尽管最近五届世界杯中有三届产生了至少一位意外决赛选手。这是赛事的最终智慧测试。",
  ],

  JP: [
    "48カ国すべてがキャンペーンを開始。最大のトーナメントエントロピー — Liliはまだどのコンフェデレーションも支配的とは読んでいない。第1マッチデーがモメンタム、ナラティブ、早期資格算術を確立する。",
    "第1ラウンド後にパターンが結晶化。UEFAの深さがフィールドを分け始める。アフリカ勢とアジア勢は第2グループ戦で構造的な資格圧力に直面 — 歴史的に最も競われる試合だ。",
    "グループステージ決着。UEFAとCONMEBOLが予測されるラウンドオブ16の代表を確定。CAF、AFC、CONCACAFはより狭い道 — しかしLiliはマッチデー3がトーナメント最高のサプライズ率を生み出すと指摘する。",
    "トーナメント最初の真の圧力テスト。16試合、引き分けなし。UEFAとCONMEBOLがこのステージを統計的に支配。ここでのCAFまたはAFCの生存は歴史的なシグナルシフトを表す — モロッコが2022年に証明した。",
    "8チーム残。準々決勝ステージは戦術的洗練が生存通貨となる場所だ。UEFAは通常8つのスポットのうち5-6を占める。CONMEBOLは2-3を保持。それ以上はブラケットが歴史的に前例のない領域に入る。",
    "4チーム。準決勝の集中がトーナメントの真のパワー風景を明らかにする。UEFA対CONMEBOLはLiliがシミュレーションで観察する最も一般的な準決勝ペアリングだ。他のどのコンフェデレーションのここでの存在もトーナメントを定義する瞬間だ。",
    "チャンピオンシップステージ。Liliのシミュレーションは最も頻繁にUEFA対CONMEBOLの決勝として解決するが、最近5つのワールドカップのうち3つが少なくとも1人の予想外のファイナリストを生み出した。これがトーナメント究極のインテリジェンステストだ。",
  ],

  KR: [
    "48개 국가 모두 캠페인을 시작합니다. 최대 토너먼트 엔트로피 — Lili는 아직 어느 연맹도 지배적으로 읽지 않습니다. 첫 번째 경기일이 모멘텀, 내러티브, 조기 진출 산술을 확립합니다.",
    "첫 번째 라운드 후 패턴이 결정화됩니다. UEFA의 깊이가 필드를 분리하기 시작합니다. 아프리카와 아시아 팀들은 두 번째 조별 경기에서 구조적 진출 압박에 직면합니다 — 역사적으로 가장 치열한 경기입니다.",
    "조별 리그 마무리. UEFA와 CONMEBOL이 예측된 16강 진출을 확정합니다. CAF, AFC, CONCACAF는 더 좁은 길을 가집니다 — 하지만 Lili는 3경기일이 토너먼트 최고의 이변율을 생성한다고 지적합니다.",
    "토너먼트의 첫 번째 진정한 압박 테스트. 16경기, 무승부 없음. UEFA와 CONMEBOL이 통계적으로 이 단계를 지배합니다. 이 시점에서 CAF나 AFC의 생존은 역사적 신호 변화를 나타냅니다 — 모로코가 2022년에 증명했습니다.",
    "8팀 남음. 8강 단계는 전술적 정교함이 생존 화폐가 되는 곳입니다. UEFA는 일반적으로 8개 자리 중 5-6개를 차지합니다. CONMEBOL은 2-3개를 보유합니다. 그 이상은 대진이 역사적으로 전례 없는 영역에 들어갑니다.",
    "4팀. 준결승 집중이 토너먼트의 진정한 권력 지형을 드러냅니다. UEFA 대 CONMEBOL은 Lili가 시뮬레이션에서 가장 자주 관찰하는 준결승 매치업입니다. 여기에 다른 연맹의 존재는 토너먼트를 정의하는 순간입니다.",
    "챔피언십 단계. Lili의 시뮬레이션은 UEFA 대 CONMEBOL 결승으로 가장 자주 해결되지만, 최근 5개 월드컵 중 3개에서 예상치 못한 결승 진출팀이 나왔습니다. 이것이 토너먼트의 궁극적인 인텔리전스 테스트입니다.",
  ],

  PT: [
    "As 48 nações lançam as suas campanhas. Entropia máxima do torneio — Lili ainda não lê nenhuma confederação como dominante. A primeira jornada estabelece o momentum, a narrativa e a aritmética precoce de qualificação.",
    "Os padrões cristalizam-se após a primeira ronda. A profundidade da UEFA começa a separar o campo. Os lados africanos e asiáticos enfrentam pressão estrutural de qualificação na segunda partida do grupo — historicamente o seu jogo mais disputado.",
    "Resolução da fase de grupos. UEFA e CONMEBOL confirmam a sua representação projetada na ronda de dezasseis. CAF, AFC e CONCACAF têm caminhos mais estreitos — mas Lili nota que a Jornada 3 produz a maior taxa de surpresa do torneio.",
    "O primeiro verdadeiro teste de pressão do torneio. Dezasseis jogos, sem empates. UEFA e CONMEBOL dominam estatisticamente esta fase. Cada sobrevivência da CAF ou AFC neste ponto representa uma mudança histórica de sinal — Marrocos provou em 2022.",
    "Oito restam. A fase de quartos de final é onde a sofisticação tática se torna a moeda de sobrevivência. A UEFA normalmente representa 5-6 dos oito lugares. CONMEBOL detém 2-3. Além disso, o quadro entra em território historicamente sem precedentes.",
    "Quatro equipas. A concentração das meias-finais revela o verdadeiro panorama de poder do torneio. UEFA vs CONMEBOL continua a ser o emparelhamento de meias-finais mais comum que Lili observa nas simulações. A presença de qualquer outra confederação aqui é um momento que define o torneio.",
    "A fase do campeonato. A simulação de Lili resolve-se mais frequentemente como uma final UEFA vs CONMEBOL, embora três dos últimos cinco Campeonatos do Mundo tenham produzido pelo menos um finalista inesperado. Este é o teste de inteligência final do torneio.",
  ],

  AR: [
    "تنطلق 48 دولة في حملاتها. أقصى درجات الفوضى في البطولة — لا تقرأ ليلي أي اتحاد بوصفه مهيمناً بعد. تُرسي جولة المباريات الأولى الزخم والسرد وحسابات التأهل المبكرة.",
    "تتبلور الأنماط بعد الجولة الأولى. يبدأ عمق الاتحاد الأوروبي لكرة القدم في فصل الميدان. تواجه الفرق الأفريقية والآسيوية ضغطاً تأهلياً بنيوياً في مباراتهم الجماعية الثانية — وهي تاريخياً مبارياتهم الأشد تنافساً.",
    "حسم دور المجموعات. يؤمّن الاتحادان الأوروبي والجنوب أمريكي تمثيلهما المتوقع في دور الستة عشر. تملك كل من الكاف والاتحاد الآسيوي والكونكاكاف مسارات أضيق — غير أن ليلي تُلاحظ أن اليوم الثالث ينتج أعلى معدلات المفاجآت في البطولة.",
    "أول اختبار ضغط حقيقي في البطولة. ست عشرة مباراة، لا تعادلات. يهيمن الاتحادان الأوروبي والجنوب أمريكي إحصائياً على هذه المرحلة. كل بقاء لفريق أفريقي أو آسيوي في هذه المرحلة يمثل تحولاً تاريخياً في الإشارة — أثبتت المغرب ذلك في 2022.",
    "تبقى ثماني فرق. ربع النهائي هو المرحلة التي تصبح فيها التطور التكتيكي عملة البقاء. يستحوذ الاتحاد الأوروبي عادةً على 5 إلى 6 من المقاعد الثمانية. يحتفظ الاتحاد الجنوب أمريكي بـ2 إلى 3. وما وراء ذلك، يدخل الجدول في أرض غير مسبوقة تاريخياً.",
    "أربعة فرق. يكشف تركيز نصف النهائي عن المشهد الحقيقي للقوة في البطولة. لا يزال مواجهة الاتحاد الأوروبي أمام الاتحاد الجنوب أمريكي هي الثنائية الأكثر شيوعاً التي ترصدها ليلي عبر سيناريوهات المحاكاة. حضور أي اتحاد آخر هنا يُعدّ لحظة تُعرّف البطولة.",
    "مرحلة البطولة. تنتهي محاكاة ليلي في الغالب بنهائي بين الاتحاد الأوروبي والاتحاد الجنوب أمريكي، وإن كانت ثلاث من آخر خمس بطولات عالمية قد أفرزت متأهلاً للنهائي غير متوقع على الأقل. هذا هو الاختبار الاستخباراتي الأعلى مستوى في البطولة.",
  ],
};
