// GENERATED by scripts/sync-dispatch.ts — do not edit by hand.
// Bot-captured Dispatch candidates (published / quarantine stages). The curated
// baseline lives in routeDispatch.ts; this file only holds machine-captured items.

import type { DispatchCandidate } from './routeDispatch';

export const DISPATCH_CANDIDATES: DispatchCandidate[] = [];

export const DISPATCH_CANDIDATES_LAST_UPDATED = '1970-01-01T00:00:00.000Z';
