// Auto-generated by scripts/sync-fixture-results.ts — do not edit manually.
// Refreshed every 10 minutes during match windows via GitHub Actions.

export type FixtureStatus = 'SCHEDULED' | 'LIVE' | 'FINISHED';

export interface FixtureResult {
  status:    FixtureStatus;
  homeScore: number | null;
  awayScore: number | null;
  winner:    string | null; // winning team name, 'Draw', or null
}

// Keyed by "HomeTeam|AwayTeam" — matches WC_FIXTURES home|away exactly.
// Only contains entries for fixtures that are LIVE or FINISHED.
export const FIXTURE_RESULTS: Record<string, FixtureResult> = {
  "Mexico|South Africa": { status: 'LIVE', homeScore: 1, awayScore: 0, winner: 'Mexico' },
};

export const FIXTURE_RESULTS_LAST_UPDATED = '2026-06-11T19:37:40.001Z';
