// Auto-generated by scripts/sync-fixture-results.ts — do not edit manually.
// Refreshed every 10 minutes during match windows via GitHub Actions.

export type FixtureStatus = 'SCHEDULED' | 'LIVE' | 'FINISHED';

export interface FixtureResult {
  status:    FixtureStatus;
  homeScore: number | null;
  awayScore: number | null;
  winner:    string | null; // winning team name, 'Draw', or null
}

// Keyed by "HomeTeam|AwayTeam" — matches WC_FIXTURES home|away exactly.
// Only contains entries for fixtures that are LIVE or FINISHED.
export const FIXTURE_RESULTS: Record<string, FixtureResult> = {
  "Mexico|South Africa": { status: 'FINISHED', homeScore: 2, awayScore: 0, winner: 'Mexico' },
  "South Korea|Czech Republic": { status: 'FINISHED', homeScore: 2, awayScore: 1, winner: 'South Korea' },
  "Canada|Bosnia & Herzegovina": { status: 'FINISHED', homeScore: 1, awayScore: 1, winner: null },
  "USA|Paraguay": { status: 'FINISHED', homeScore: 4, awayScore: 1, winner: 'USA' },
  "Qatar|Switzerland": { status: 'FINISHED', homeScore: 1, awayScore: 1, winner: null },
  "Brazil|Morocco": { status: 'FINISHED', homeScore: 1, awayScore: 1, winner: null },
  "Haiti|Scotland": { status: 'FINISHED', homeScore: 0, awayScore: 1, winner: 'Scotland' },
  "Australia|Türkiye": { status: 'FINISHED', homeScore: 2, awayScore: 0, winner: 'Australia' },
  "Germany|Curaçao": { status: 'FINISHED', homeScore: 7, awayScore: 1, winner: 'Germany' },
  "Netherlands|Japan": { status: 'FINISHED', homeScore: 2, awayScore: 2, winner: null },
  "Ivory Coast|Ecuador": { status: 'FINISHED', homeScore: 1, awayScore: 0, winner: 'Ivory Coast' },
  "Sweden|Tunisia": { status: 'FINISHED', homeScore: 5, awayScore: 1, winner: 'Sweden' },
  "Spain|Cape Verde Islands": { status: 'FINISHED', homeScore: 0, awayScore: 0, winner: null },
  "Belgium|Egypt": { status: 'FINISHED', homeScore: 1, awayScore: 1, winner: null },
  "Saudi Arabia|Uruguay": { status: 'FINISHED', homeScore: 1, awayScore: 1, winner: null },
  "Iran|New Zealand": { status: 'FINISHED', homeScore: 2, awayScore: 2, winner: null },
  "France|Senegal": { status: 'FINISHED', homeScore: 3, awayScore: 1, winner: 'France' },
  "Iraq|Norway": { status: 'FINISHED', homeScore: 1, awayScore: 4, winner: 'Norway' },
  "Argentina|Algeria": { status: 'FINISHED', homeScore: 3, awayScore: 0, winner: 'Argentina' },
  "Austria|Jordan": { status: 'FINISHED', homeScore: 3, awayScore: 1, winner: 'Austria' },
};

export const FIXTURE_RESULTS_LAST_UPDATED = '2026-06-17T10:03:15.770Z';
