// Auto-generated by scripts/sync-injuries.ts — do not edit manually.
// Refreshed every 4 hours during the tournament via GitHub Actions.

import type { InjuredPlayer } from './wcData';

// Keyed by team name (matches WC_TEAMS[].name exactly).
export const INJURED_PLAYERS: Record<string, InjuredPlayer[]> = {

};

export const INJURY_LAST_UPDATED = '2026-05-29T09:47:08.477Z';
