// Auto-generated by scripts/sync-knockout.ts — do not edit manually.
// The WC 2026 knockout bracket (Round of 32 → Final), kept SEPARATE from the
// group-stage WC_FIXTURES so it never skews group-stage aggregates.
// Live scores come from the /api/fixture-results overlay (keyed home|away);
// this file is the fixture list + a baked status snapshot.

export type KnockoutRound = 'R32' | 'R16' | 'QF' | 'SF' | '3RD' | 'F';

export interface KnockoutFixture {
  id:         string;
  round:      KnockoutRound;
  roundLabel: string;
  home:       string;          // canonical app team name (may be a placeholder until a tie is decided)
  away:       string;
  date:       string;          // ISO 8601
  stadiumId:  string | null;   // curated stadium id (lib/stadiumData), or null when the feed gives no/unknown venue
  venueName:  string | null;   // raw feed venue name (fallback display when stadiumId is null)
  city:       string | null;
  status:     'SCHEDULED' | 'LIVE' | 'FINISHED';
  homeScore:  number | null;
  awayScore:  number | null;
}

// Display order for the six knockout rounds.
export const KNOCKOUT_ORDER: Record<KnockoutRound, number> = { R32: 0, R16: 1, QF: 2, SF: 3, '3RD': 4, F: 5 };

export const WC_KNOCKOUT: KnockoutFixture[] = [
  { id: '1561329', round: 'R32', roundLabel: 'Round of 32', home: 'South Africa', away: 'Canada', date: '2026-06-28T19:00:00+00:00', stadiumId: 'sofi', venueName: 'SoFi Stadium', city: 'Inglewood', status: 'FINISHED', homeScore: 0, awayScore: 1 },
  { id: '1562344', round: 'R32', roundLabel: 'Round of 32', home: 'Brazil', away: 'Japan', date: '2026-06-29T17:00:00+00:00', stadiumId: 'nrg', venueName: 'NRG Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1565176', round: 'R32', roundLabel: 'Round of 32', home: 'Germany', away: 'Paraguay', date: '2026-06-29T20:30:00+00:00', stadiumId: 'gillette', venueName: 'Gillette Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1562345', round: 'R32', roundLabel: 'Round of 32', home: 'Netherlands', away: 'Morocco', date: '2026-06-30T01:00:00+00:00', stadiumId: 'bbva', venueName: 'Estadio BBVA', city: 'Monterrey', status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1564789', round: 'R32', roundLabel: 'Round of 32', home: 'Ivory Coast', away: 'Norway', date: '2026-06-30T17:00:00+00:00', stadiumId: null, venueName: null, city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1565177', round: 'R32', roundLabel: 'Round of 32', home: 'France', away: 'Sweden', date: '2026-06-30T21:00:00+00:00', stadiumId: 'metlife', venueName: 'MetLife Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567306', round: 'R32', roundLabel: 'Round of 32', home: 'Mexico', away: 'Ecuador', date: '2026-07-01T01:00:00+00:00', stadiumId: 'azteca', venueName: 'Estadio Banorte', city: 'Mexico City', status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567307', round: 'R32', roundLabel: 'Round of 32', home: 'England', away: 'Congo DR', date: '2026-07-01T16:00:00+00:00', stadiumId: 'mercedes', venueName: 'Mercedes-Benz Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567308', round: 'R32', roundLabel: 'Round of 32', home: 'Belgium', away: 'Senegal', date: '2026-07-01T20:00:00+00:00', stadiumId: 'lumen', venueName: 'Lumen Field', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1562586', round: 'R32', roundLabel: 'Round of 32', home: 'USA', away: 'Bosnia & Herzegovina', date: '2026-07-02T00:00:00+00:00', stadiumId: null, venueName: null, city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567311', round: 'R32', roundLabel: 'Round of 32', home: 'Spain', away: 'Austria', date: '2026-07-02T19:00:00+00:00', stadiumId: 'sofi', venueName: 'SoFi Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567309', round: 'R32', roundLabel: 'Round of 32', home: 'Portugal', away: 'Croatia', date: '2026-07-02T23:00:00+00:00', stadiumId: 'bmo', venueName: 'BMO Field', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567312', round: 'R32', roundLabel: 'Round of 32', home: 'Switzerland', away: 'Algeria', date: '2026-07-03T03:00:00+00:00', stadiumId: 'bc', venueName: 'BC Place', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1565178', round: 'R32', roundLabel: 'Round of 32', home: 'Australia', away: 'Egypt', date: '2026-07-03T18:00:00+00:00', stadiumId: null, venueName: null, city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1565179', round: 'R32', roundLabel: 'Round of 32', home: 'Argentina', away: 'Cape Verde Islands', date: '2026-07-03T22:00:00+00:00', stadiumId: 'hardrock', venueName: 'Hard Rock Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
  { id: '1567310', round: 'R32', roundLabel: 'Round of 32', home: 'Colombia', away: 'Ghana', date: '2026-07-04T01:30:00+00:00', stadiumId: 'arrowhead', venueName: 'Arrowhead Stadium', city: null, status: 'SCHEDULED', homeScore: null, awayScore: null },
];

export const WC_KNOCKOUT_LAST_UPDATED = '2026-06-28T21:36:27.303Z';
