// Auto-generated by scripts/sync-knockout.ts — do not edit manually.
// The WC 2026 knockout bracket (Round of 32 → Final), kept SEPARATE from the
// group-stage WC_FIXTURES so it never skews group-stage aggregates.
// Live scores come from the /api/fixture-results overlay (keyed home|away);
// this file is the fixture list + a baked status snapshot.

export type KnockoutRound = 'R32' | 'R16' | 'QF' | 'SF' | '3RD' | 'F';

export interface KnockoutFixture {
  id:         string;
  round:      KnockoutRound;
  roundLabel: string;
  home:       string;          // canonical app team name (may be a placeholder until a tie is decided)
  away:       string;
  date:       string;          // ISO 8601
  stadiumId:  string | null;   // curated stadium id (lib/stadiumData), or null when the feed gives no/unknown venue
  venueName:  string | null;   // raw feed venue name (fallback display when stadiumId is null)
  city:       string | null;
  status:     'SCHEDULED' | 'LIVE' | 'FINISHED';
  homeScore:  number | null;
  awayScore:  number | null;
  winner:     'home' | 'away' | null;  // overall winner incl. ET/penalties (null until decided)
  penHome:    number | null;           // penalty-shootout score (null unless decided on spot-kicks)
  penAway:    number | null;
}

// Display order for the six knockout rounds.
export const KNOCKOUT_ORDER: Record<KnockoutRound, number> = { R32: 0, R16: 1, QF: 2, SF: 3, '3RD': 4, F: 5 };

export const WC_KNOCKOUT: KnockoutFixture[] = [
  { id: '1561329', round: 'R32', roundLabel: 'Round of 32', home: 'South Africa', away: 'Canada', date: '2026-06-28T19:00:00+00:00', stadiumId: 'sofi', venueName: 'SoFi Stadium', city: 'Inglewood', status: 'FINISHED', homeScore: 0, awayScore: 1, winner: 'away', penHome: null, penAway: null },
  { id: '1562344', round: 'R32', roundLabel: 'Round of 32', home: 'Brazil', away: 'Japan', date: '2026-06-29T17:00:00+00:00', stadiumId: 'nrg', venueName: 'NRG Stadium', city: 'Houston', status: 'FINISHED', homeScore: 2, awayScore: 1, winner: 'home', penHome: null, penAway: null },
  { id: '1565176', round: 'R32', roundLabel: 'Round of 32', home: 'Germany', away: 'Paraguay', date: '2026-06-29T20:30:00+00:00', stadiumId: 'gillette', venueName: 'Gillette Stadium', city: 'Boston', status: 'FINISHED', homeScore: 1, awayScore: 1, winner: 'away', penHome: 3, penAway: 4 },
  { id: '1562345', round: 'R32', roundLabel: 'Round of 32', home: 'Netherlands', away: 'Morocco', date: '2026-06-30T01:00:00+00:00', stadiumId: 'bbva', venueName: 'Estadio BBVA', city: 'Monterrey', status: 'FINISHED', homeScore: 1, awayScore: 1, winner: 'away', penHome: 2, penAway: 3 },
  { id: '1564789', round: 'R32', roundLabel: 'Round of 32', home: 'Ivory Coast', away: 'Norway', date: '2026-06-30T17:00:00+00:00', stadiumId: 'att', venueName: 'AT&T Stadium', city: 'Dallas', status: 'FINISHED', homeScore: 1, awayScore: 2, winner: 'away', penHome: null, penAway: null },
  { id: '1565177', round: 'R32', roundLabel: 'Round of 32', home: 'France', away: 'Sweden', date: '2026-06-30T21:00:00+00:00', stadiumId: 'metlife', venueName: 'MetLife Stadium', city: 'New-York', status: 'FINISHED', homeScore: 3, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1567306', round: 'R32', roundLabel: 'Round of 32', home: 'Mexico', away: 'Ecuador', date: '2026-07-01T01:00:00+00:00', stadiumId: 'azteca', venueName: 'Estadio Banorte', city: 'Mexico City', status: 'FINISHED', homeScore: 2, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1567307', round: 'R32', roundLabel: 'Round of 32', home: 'England', away: 'Congo DR', date: '2026-07-01T16:00:00+00:00', stadiumId: 'mercedes', venueName: 'Mercedes-Benz Stadium', city: 'Atlanta', status: 'FINISHED', homeScore: 2, awayScore: 1, winner: 'home', penHome: null, penAway: null },
  { id: '1567308', round: 'R32', roundLabel: 'Round of 32', home: 'Belgium', away: 'Senegal', date: '2026-07-01T20:00:00+00:00', stadiumId: 'lumen', venueName: 'Lumen Field', city: 'Seattle', status: 'FINISHED', homeScore: 3, awayScore: 2, winner: 'home', penHome: null, penAway: null },
  { id: '1562586', round: 'R32', roundLabel: 'Round of 32', home: 'USA', away: 'Bosnia & Herzegovina', date: '2026-07-02T00:00:00+00:00', stadiumId: 'levis', venueName: 'Levi\'s Stadium', city: 'San-Francisco', status: 'FINISHED', homeScore: 2, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1567311', round: 'R32', roundLabel: 'Round of 32', home: 'Spain', away: 'Austria', date: '2026-07-02T19:00:00+00:00', stadiumId: 'sofi', venueName: 'SoFi Stadium', city: 'Inglewood', status: 'FINISHED', homeScore: 3, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1567309', round: 'R32', roundLabel: 'Round of 32', home: 'Portugal', away: 'Croatia', date: '2026-07-02T23:00:00+00:00', stadiumId: 'bmo', venueName: 'BMO Field', city: 'Toronto', status: 'FINISHED', homeScore: 2, awayScore: 1, winner: 'home', penHome: null, penAway: null },
  { id: '1567312', round: 'R32', roundLabel: 'Round of 32', home: 'Switzerland', away: 'Algeria', date: '2026-07-03T03:00:00+00:00', stadiumId: 'bc', venueName: 'BC Place', city: 'Vancouver', status: 'FINISHED', homeScore: 2, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1565178', round: 'R32', roundLabel: 'Round of 32', home: 'Australia', away: 'Egypt', date: '2026-07-03T18:00:00+00:00', stadiumId: 'att', venueName: 'AT&T Stadium', city: 'Dallas', status: 'FINISHED', homeScore: 1, awayScore: 1, winner: 'away', penHome: 2, penAway: 4 },
  { id: '1565179', round: 'R32', roundLabel: 'Round of 32', home: 'Argentina', away: 'Cape Verde Islands', date: '2026-07-03T22:00:00+00:00', stadiumId: 'hardrock', venueName: 'Hard Rock Stadium', city: 'Miami', status: 'FINISHED', homeScore: 3, awayScore: 2, winner: 'home', penHome: null, penAway: null },
  { id: '1567310', round: 'R32', roundLabel: 'Round of 32', home: 'Colombia', away: 'Ghana', date: '2026-07-04T01:30:00+00:00', stadiumId: 'arrowhead', venueName: 'Arrowhead Stadium', city: 'Kansas City', status: 'FINISHED', homeScore: 1, awayScore: 0, winner: 'home', penHome: null, penAway: null },
  { id: '1567824', round: 'R16', roundLabel: 'Round of 16', home: 'Canada', away: 'Morocco', date: '2026-07-04T17:00:00+00:00', stadiumId: 'nrg', venueName: 'NRG Stadium', city: 'Houston', status: 'FINISHED', homeScore: 0, awayScore: 3, winner: 'away', penHome: null, penAway: null },
  { id: '1569870', round: 'R16', roundLabel: 'Round of 16', home: 'Paraguay', away: 'France', date: '2026-07-04T21:00:00+00:00', stadiumId: 'lincoln', venueName: 'Lincoln Financial Field', city: 'Philadelphia', status: 'FINISHED', homeScore: 0, awayScore: 1, winner: 'away', penHome: null, penAway: null },
  { id: '1568100', round: 'R16', roundLabel: 'Round of 16', home: 'Brazil', away: 'Norway', date: '2026-07-05T20:00:00+00:00', stadiumId: 'metlife', venueName: 'MetLife Stadium', city: 'East Rutherford', status: 'FINISHED', homeScore: 1, awayScore: 2, winner: 'away', penHome: null, penAway: null },
  { id: '1570714', round: 'R16', roundLabel: 'Round of 16', home: 'Mexico', away: 'England', date: '2026-07-06T01:00:00+00:00', stadiumId: 'azteca', venueName: 'Estadio Banorte', city: 'Mexico City', status: 'FINISHED', homeScore: 2, awayScore: 3, winner: 'away', penHome: null, penAway: null },
  { id: '1576756', round: 'R16', roundLabel: 'Round of 16', home: 'Portugal', away: 'Spain', date: '2026-07-06T19:00:00+00:00', stadiumId: 'att', venueName: 'AT&T Stadium', city: 'Dallas', status: 'FINISHED', homeScore: 0, awayScore: 1, winner: 'away', penHome: null, penAway: null },
  { id: '1570715', round: 'R16', roundLabel: 'Round of 16', home: 'USA', away: 'Belgium', date: '2026-07-07T00:00:00+00:00', stadiumId: 'lumen', venueName: 'Lumen Field', city: 'Seattle', status: 'SCHEDULED', homeScore: null, awayScore: null, winner: null, penHome: null, penAway: null },
  { id: '1576804', round: 'R16', roundLabel: 'Round of 16', home: 'Argentina', away: 'Egypt', date: '2026-07-07T16:00:00+00:00', stadiumId: 'mercedes', venueName: 'Mercedes-Benz Stadium', city: 'Atlanta', status: 'SCHEDULED', homeScore: null, awayScore: null, winner: null, penHome: null, penAway: null },
  { id: '1576805', round: 'R16', roundLabel: 'Round of 16', home: 'Switzerland', away: 'Colombia', date: '2026-07-07T20:00:00+00:00', stadiumId: 'bc', venueName: 'BC Place', city: 'Vancouver', status: 'SCHEDULED', homeScore: null, awayScore: null, winner: null, penHome: null, penAway: null },
  { id: '1578539', round: 'QF', roundLabel: 'Quarter-final', home: 'France', away: 'Morocco', date: '2026-07-09T20:00:00+00:00', stadiumId: 'gillette', venueName: 'Gillette Stadium', city: 'Boston', status: 'SCHEDULED', homeScore: null, awayScore: null, winner: null, penHome: null, penAway: null },
  { id: '1581037', round: 'QF', roundLabel: 'Quarter-final', home: 'Norway', away: 'England', date: '2026-07-11T21:00:00+00:00', stadiumId: 'hardrock', venueName: 'Hard Rock Stadium', city: 'Miami', status: 'SCHEDULED', homeScore: null, awayScore: null, winner: null, penHome: null, penAway: null },
];

export const WC_KNOCKOUT_LAST_UPDATED = '2026-07-06T21:56:23.873Z';
