// Auto-generated by scripts/sync-lineups.ts — do not edit manually.
// Refreshed every 30 min during the tournament via GitHub Actions.
// Primary source: SofaScore (pre-match, ~1h before kickoff).
// Fallback: api-football (post-match confirmed).

export type Position = 'GK' | 'DF' | 'MF' | 'FW';

export interface LineupPlayer {
  name: string;
  number: number;
  pos: Position;
  starter: boolean;  // false = bench
}

export interface TeamLineup {
  formation: string;    // e.g. "4-3-3"
  players: LineupPlayer[];
  coach?: string;
}

export interface MatchLineup {
  fixtureKey: string;   // "Home|Away" — same convention as FIXTURE_RESULTS
  home: TeamLineup;
  away: TeamLineup;
  confirmed: boolean;   // true = official submission; false = predicted
  source: 'sofascore' | 'api-football';
  updatedAt: string;
}

export const MATCH_LINEUPS: MatchLineup[] = [];

export const LINEUPS_LAST_UPDATED = '';
