// Auto-generated by scripts/sync-lineups.ts — do not edit manually.
// Refreshed every 30 min during the tournament via GitHub Actions.
// Source: api-football /fixtures/lineups (formation + XI + coach) → baseline fallback.

export type Position = 'GK' | 'DF' | 'MF' | 'FW';

export interface LineupPlayer {
  name: string;
  number: number;
  pos: Position;
  starter: boolean;
}

export interface TeamLineup {
  formation: string;
  players: LineupPlayer[];
  coach?: string;
}

export interface MatchLineup {
  fixtureKey: string;
  home: TeamLineup;
  away: TeamLineup;
  confirmed: boolean;
  source: 'api-football' | 'baseline';
  updatedAt: string;
}

export const MATCH_LINEUPS: MatchLineup[] = [
  {
    "fixtureKey": "Algeria|Austria",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Argentina|Algeria",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Argentina|Austria",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Australia|Türkiye",
    "home": {
      "formation": "5-4-1",
      "players": [
        {
          "name": "Patrick Beach",
          "number": 18,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Jacob Italiano",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Alessandro Circati",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Harry Souttar",
          "number": 19,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Cameron Burgess",
          "number": 21,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Jordan Bos",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Connor Metcalfe",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Aiden O'Neill",
          "number": 13,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Paul Okon-Engstler",
          "number": 24,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Nestory Irankunda",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Mohamed Touré",
          "number": 9,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Nishan Velupillay",
          "number": 23,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Jason Geria",
          "number": 6,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Tete Yengi",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Aziz Behich",
          "number": 16,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Jackson Irvine",
          "number": 22,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Mathew Ryan",
          "number": 1,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Paul Izzo",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Miloš Degenek",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Lucas Herrington",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Kai Trewin",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Cameron Devlin",
          "number": 14,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Mathew Leckie",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Ajdin Hrustić",
          "number": 10,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Awer Mabil",
          "number": 11,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Cristian Volpato",
          "number": 20,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Tony Popovic"
    },
    "away": {
      "formation": "4-2-3-1",
      "players": [
        {
          "name": "Uğurcan Çakır",
          "number": 23,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Zeki Çelik",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Merih Demiral",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Abdülkerim Bardakcı",
          "number": 14,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ferdi Kadıoğlu",
          "number": 20,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "İsmail Yüksek",
          "number": 16,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Hakan Çalhanoğlu",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Arda Güler",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Orkun Kökçü",
          "number": 6,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Barış Alper Yılmaz",
          "number": 21,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Kerem Aktürkoğlu",
          "number": 7,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Kenan Yıldız",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Yunus Akgün",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Mert Müldür",
          "number": 18,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Salih Özcan",
          "number": 5,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Deniz Gül",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Mert Günok",
          "number": 1,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Altay Bayındır",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Çağlar Söyüncü",
          "number": 4,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Eren Elmalı",
          "number": 13,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ozan Kabak",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Samet Akaydın",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Kaan Ayhan",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "İrfan Can Kahveci",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Oğuz Aydın",
          "number": 24,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Can Uzun",
          "number": 26,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Vincenzo Montella"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:37.786Z"
  },
  {
    "fixtureKey": "Austria|Jordan",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-5-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Belgium|Egypt",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Belgium|Iran",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Bosnia & Herzegovina|Qatar",
    "home": {
      "formation": "4-4-2",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Brazil|Haiti",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Brazil|Morocco",
    "home": {
      "formation": "4-2-3-1",
      "players": [
        {
          "name": "Alisson",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Roger Ibañez",
          "number": 24,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Marquinhos",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Gabriel Magalhães",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Douglas Santos",
          "number": 16,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Casemiro",
          "number": 5,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Bruno Guimarães",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Lucas Paquetá",
          "number": 20,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Raphinha",
          "number": 11,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Vinícius Júnior",
          "number": 7,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Igor Thiago",
          "number": 25,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Danilo",
          "number": 13,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Fabinho",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Luiz Henrique",
          "number": 21,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Matheus Cunha",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Danilo Santos",
          "number": 18,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Ederson",
          "number": 23,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Weverton",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Alex Sandro",
          "number": 6,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Bremer",
          "number": 14,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Léo Pereira",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Rayan",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Éderson",
          "number": 2,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Endrick",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Gabriel Martinelli",
          "number": 22,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Carlo Ancelotti"
    },
    "away": {
      "formation": "4-2-3-1",
      "players": [
        {
          "name": "Bono",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Achraf Hakimi",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Issa Diop",
          "number": 14,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Chadi Riad",
          "number": 18,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Noussair Mazraoui",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Neil El Aynaoui",
          "number": 24,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Ayyoub Bouaddi",
          "number": 6,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Brahim Díaz",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Azzedine Ounahi",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Bilal El Khannouss",
          "number": 23,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Ismael Saibari",
          "number": 11,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Chemsdine Talbi",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Samir El Mourabet",
          "number": 15,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Anass Salah-Eddine",
          "number": 26,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ayoube Amaimouni Echghouyab",
          "number": 21,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Soufiane Rahimi",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Munir El Kajoui",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Ahmed Reda Tagnaouti",
          "number": 22,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Marwane Saadane",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Redouane Halhal",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Zakaria El Ouahdi",
          "number": 13,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Youssef Belammari",
          "number": 19,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Amine Sbai",
          "number": 17,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Gessime Yassine",
          "number": 16,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Sofyan Amrabat",
          "number": 4,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Ayoub El Kaabi",
          "number": 20,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Mohamed Ouahbi"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:37.065Z"
  },
  {
    "fixtureKey": "Canada|Bosnia & Herzegovina",
    "home": {
      "formation": "4-4-2",
      "players": [
        {
          "name": "M. Crepeau",
          "number": 16,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "A. Johnston",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "L. De Fougerolles",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "D. Cornelius",
          "number": 13,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "R. Laryea",
          "number": 22,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "T. Buchanan",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "I. Kone",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "S. Eustaquio",
          "number": 7,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "L. Millar",
          "number": 11,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "J. David",
          "number": 10,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "T. Oluwaseyi",
          "number": 12,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "D. St.Clair",
          "number": 1,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "O. Goodman",
          "number": 18,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "C. Larin",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "J. Waterman",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "A. Davies",
          "number": 19,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "J. Shaffelburg",
          "number": 14,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "J. Nelson",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "M. Bombito",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "N. Sigur",
          "number": 23,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "J. Osorio",
          "number": 21,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Jones",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "M. Choiniere",
          "number": 6,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "N. Saliba",
          "number": 25,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "P. David",
          "number": 24,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "A. Ahmed",
          "number": 20,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Jesse Marsch"
    },
    "away": {
      "formation": "4-4-2",
      "players": [
        {
          "name": "N. Vasilj",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "A. Dedic",
          "number": 7,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "N. Katic",
          "number": 18,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "T. Muharemovic",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "S. Kolasinac",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "E. Bajraktarevic",
          "number": 20,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "B. Tahirovic",
          "number": 6,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "I. Basic",
          "number": 13,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "A. Memic",
          "number": 15,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "E. Demirovic",
          "number": 10,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "J. Lukic",
          "number": 25,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "M. Zlomislic",
          "number": 22,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "M. Jurkas",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "E. Dzeko",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "I. Sunjic",
          "number": 14,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "E. Mahmic",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "K. Alajbegovic",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "H. Tabakovic",
          "number": 23,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "A. Hadziahmetovic",
          "number": 16,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "D. Hadzikadunic",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "D. Burnic",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "S. Radeljic",
          "number": 21,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "N. Mujakic",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "A. Gigovic",
          "number": 8,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "S. Bazdar",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "A. Malic",
          "number": 24,
          "pos": "DF",
          "starter": false
        }
      ],
      "coach": "Sergej Barbarez"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:35.976Z"
  },
  {
    "fixtureKey": "Canada|Qatar",
    "home": {
      "formation": "4-4-2",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Cape Verde Islands|Saudi Arabia",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Colombia|Congo DR",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Colombia|Portugal",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Congo DR|Uzbekistan",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Croatia|Ghana",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Curaçao|Ivory Coast",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Czech Republic|Mexico",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Czech Republic|South Africa",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Ecuador|Curaçao",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Ecuador|Germany",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Egypt|Iran",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "England|Croatia",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "England|Ghana",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "France|Iraq",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-4-2",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "France|Senegal",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Germany|Curaçao",
    "home": {
      "formation": "4-2-3-1",
      "players": [
        {
          "name": "Manuel Neuer",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Joshua Kimmich",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Jonathan Tah",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Nico Schlotterbeck",
          "number": 15,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Nathaniel Brown",
          "number": 18,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Felix Nmecha",
          "number": 23,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Aleksandar Pavlović",
          "number": 5,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Leroy Sané",
          "number": 19,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Jamal Musiala",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Florian Wirtz",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Kai Havertz",
          "number": 7,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Deniz Undav",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "David Raum",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Antonio Rüdiger",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Leon Goretzka",
          "number": 8,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Waldemar Anton",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Alexander Nübel",
          "number": 21,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Oliver Baumann",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Malick Thiaw",
          "number": 24,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Jamie Leweling",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Assan Ouédraogo",
          "number": 25,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Nadiem Amiri",
          "number": 20,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Angelo Stiller",
          "number": 16,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Pascal Groß",
          "number": 13,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Nick Woltemade",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Maximilian Beier",
          "number": 14,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Julian Nagelsmann"
    },
    "away": {
      "formation": "4-3-1-2",
      "players": [
        {
          "name": "Eloy Room",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Sherel Constancio Floranus",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Riechedly Bazoer",
          "number": 23,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Armando Obispo",
          "number": 18,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Deveron Fonville",
          "number": 24,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Livano Comenencia",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Leandro Bacuna",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Juninho Bacuna",
          "number": 7,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Tahith Chong",
          "number": 21,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Jürgen Locadia",
          "number": 9,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Sontje Hansen",
          "number": 12,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Jeremy Antonisse",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Jearl Margaritha",
          "number": 16,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Gervane Kastaneer",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Trevor Iriving Doornbusch",
          "number": 26,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Tyrick Bodak",
          "number": 25,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Jurien Gaari",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Joshua Brenet",
          "number": 20,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Shurandy Sambo",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Roshon van Eijma",
          "number": 4,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ar'Jany Martha",
          "number": 15,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Kenji Gorré",
          "number": 14,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Kevin Felida",
          "number": 22,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Tyrese Noslin",
          "number": 13,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Godfried Roemeratoe",
          "number": 6,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Brandley Kuwas",
          "number": 17,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Dick Advocaat"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:38.143Z"
  },
  {
    "fixtureKey": "Germany|Ivory Coast",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Ghana|Panama",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Haiti|Scotland",
    "home": {
      "formation": "4-4-2",
      "players": [
        {
          "name": "Johny Placide",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Carlens Arcus",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ricardo Adé",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Hannes Delcroix",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Martin Expérience",
          "number": 8,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Louicius Don Deedson",
          "number": 11,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Danley Jean Jacques",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Jean-Ricner Bellegarde",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Ruben Providence",
          "number": 15,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Frantzdy Pierrot",
          "number": 20,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Wilson Isidor",
          "number": 18,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Josué Casimir",
          "number": 21,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Lenny Joseph",
          "number": 16,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Yassin Fortune",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Alexandre Pierre",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Josué Duverger",
          "number": 23,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Keeto Thermoncy",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Duke Lacroix",
          "number": 13,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Garven-Michee Metusala",
          "number": 14,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Jean-Kévin Duverne",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Wilguens Paugain",
          "number": 24,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Carl Fred Sainté",
          "number": 6,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Dominique Simon",
          "number": 25,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Woodensky Pierre",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Derrick Etienne",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Duckens Nazon",
          "number": 9,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Sebastien Migne"
    },
    "away": {
      "formation": "4-4-2",
      "players": [
        {
          "name": "Angus Gunn",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Aaron Hickey",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Grant Hanley",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Jack Hendry",
          "number": 13,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Andy Robertson",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ben Gannon-Doak",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Scott McTominay",
          "number": 4,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Lewis Ferguson",
          "number": 19,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "John McGinn",
          "number": 7,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Lawrence Shankland",
          "number": 20,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Che Adams",
          "number": 10,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Nathan Patterson",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ryan Christie",
          "number": 11,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Lyndon Dykes",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Kenny McLean",
          "number": 23,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Findlay Curtis",
          "number": 25,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Liam Kelly",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Craig Gordon",
          "number": 21,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Kieran Tierney",
          "number": 6,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "John Souttar",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Dominic Hyam",
          "number": 16,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Tony Ralston",
          "number": 24,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Scott McKenna",
          "number": 26,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Tyler Fletcher",
          "number": 8,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Ross Stewart",
          "number": 14,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "George Hirst",
          "number": 18,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Steve Clarke"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:37.426Z"
  },
  {
    "fixtureKey": "Iran|New Zealand",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Iraq|Norway",
    "home": {
      "formation": "4-4-2",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Ivory Coast|Ecuador",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Japan|Sweden",
    "home": {
      "formation": "3-4-2-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Jordan|Algeria",
    "home": {
      "formation": "4-5-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Jordan|Argentina",
    "home": {
      "formation": "4-5-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Mexico|South Africa",
    "home": {
      "formation": "4-1-4-1",
      "players": [
        {
          "name": "R. Rangel",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "I. Reyes",
          "number": 15,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "C. Montes",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "J. Vasquez",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "J. Gallardo",
          "number": 23,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "E. Lira",
          "number": 6,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "R. Alvarado",
          "number": 25,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "B. Gutierrez",
          "number": 26,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "A. Fidalgo",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "J. Quinones",
          "number": 16,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "R. Jimenez",
          "number": 9,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "G. Ochoa",
          "number": 13,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "C. Acevedo",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "G. Martinez",
          "number": 22,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "L. Chavez",
          "number": 24,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "O. Vargas",
          "number": 18,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "M. Chavez Garcia",
          "number": 20,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "O. Pineda",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Vega",
          "number": 10,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "J. Sanchez",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "E. Alvarez",
          "number": 4,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "S. Gimenez",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "C. S. Huerta Valera",
          "number": 21,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "L. Romo",
          "number": 7,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Gonzalez",
          "number": 14,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "G. Mora",
          "number": 19,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Javier Aguirre"
    },
    "away": {
      "formation": "5-3-2",
      "players": [
        {
          "name": "R. Williams",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "K. Mudau",
          "number": 20,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "N. Sibisi",
          "number": 19,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "I. Okon",
          "number": 21,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "M. Mbokazi",
          "number": 14,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "A. Modiba",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "T. Mokoena",
          "number": 4,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Y. Sithole",
          "number": 13,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "J. Adams",
          "number": 23,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "I. Rayners",
          "number": 15,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "L. Foster",
          "number": 9,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "R. Goss",
          "number": 22,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "S. Chaine",
          "number": 16,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "B. Cross",
          "number": 26,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "T. Mbatha",
          "number": 5,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "E. Makgopa",
          "number": 17,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "T. Matuludi",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "K. Ndamane",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "T. Zwane",
          "number": 11,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "O. Appollis",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "T. Moremi",
          "number": 8,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "T. Maseko",
          "number": 12,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "K. Sebelebele",
          "number": 25,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "O. Makhanya",
          "number": 24,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "R. Mofokeng",
          "number": 10,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "S. Kabini",
          "number": 18,
          "pos": "DF",
          "starter": false
        }
      ],
      "coach": "Hugo Broos"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:18.666Z"
  },
  {
    "fixtureKey": "Mexico|South Korea",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Morocco|Haiti",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Netherlands|Japan",
    "home": {
      "formation": "4-3-3",
      "players": [
        {
          "name": "Bart Verbruggen",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Denzel Dumfries",
          "number": 22,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Jan Paul van Hecke",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Virgil van Dijk",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Micky van de Ven",
          "number": 15,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ryan Gravenberch",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Frenkie de Jong",
          "number": 21,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Tijjani Reijnders",
          "number": 14,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Crysencio Summerville",
          "number": 24,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Donyell Malen",
          "number": 18,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Cody Gakpo",
          "number": 11,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Mark Flekken",
          "number": 23,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Robin Roefs",
          "number": 13,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Jorrel Hato",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Lutsharel Geertruida",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Mats Wieffer",
          "number": 12,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Nathan Aké",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Guus Til",
          "number": 16,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Marten de Roon",
          "number": 3,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Justin Kluivert",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Quinten Timber",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Teun Koopmeiners",
          "number": 20,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Brian Brobbey",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Memphis Depay",
          "number": 10,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Wout Weghorst",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Noa Lang",
          "number": 17,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Ronald Koeman"
    },
    "away": {
      "formation": "3-4-2-1",
      "players": [
        {
          "name": "Zion Suzuki",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Tsuyoshi Watanabe",
          "number": 16,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Shogo Taniguchi",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Hiroki Itō",
          "number": 21,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ritsu Doan",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Kaishu Sano",
          "number": 24,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Daichi Kamada",
          "number": 15,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Keito Nakamura",
          "number": 13,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Takefusa Kubo",
          "number": 8,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Daizen Maeda",
          "number": 11,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Ayase Ueda",
          "number": 18,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Keisuke Osako",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Tomoki Hayakawa",
          "number": 23,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Ayumu Seko",
          "number": 20,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ko Itakura",
          "number": 4,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Junnosuke Suzuki",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Yukinari Sugawara",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Takehiro Tomiyasu",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Yuto Nagatomo",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ao Tanaka",
          "number": 7,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Yuito Suzuki",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Junya Ito",
          "number": 14,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Keisuke Goto",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Koki Ogawa",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Kento Shiogai",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Shuto Machino",
          "number": 6,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Hajime Moriyasu"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:09.218Z"
  },
  {
    "fixtureKey": "Netherlands|Sweden",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "New Zealand|Belgium",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "New Zealand|Egypt",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Norway|France",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Norway|Senegal",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Panama|Croatia",
    "home": {
      "formation": "3-4-2-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Panama|England",
    "home": {
      "formation": "3-4-2-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Paraguay|Australia",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Portugal|Congo DR",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Portugal|Uzbekistan",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Qatar|Switzerland",
    "home": {
      "formation": "4-3-3",
      "players": [
        {
          "name": "Mahmud Abunad",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Ayoub Al Oui",
          "number": 13,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Pedro Miguel",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Boualem Khoukhi",
          "number": 16,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Homam Al-Amin",
          "number": 14,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Jassem Gaber Abdulsallam",
          "number": 5,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Assim Madibo",
          "number": 23,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Issa Laye",
          "number": 4,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Edmilson Junior",
          "number": 8,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Yusuf Abdurisag",
          "number": 15,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Akram Afif",
          "number": 11,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Ahmed Fathi",
          "number": 20,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Karim Boudiaf",
          "number": 12,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Ahmed Alaaeldin",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Mohamed Naceur Almanai",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Hassan Al Haydos",
          "number": 10,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Meshaal Barsham",
          "number": 22,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Salah Zakaria",
          "number": 21,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Lucas Mendes",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Sultan Al-Brake",
          "number": 18,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Al-Hashmi Al-Hussain",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Abdelaziz Hatem",
          "number": 6,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Ahmed Al-Ganehi",
          "number": 17,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Almoez Ali",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Mohammed Muntari",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Tahsin Mohammed Jamshid",
          "number": 24,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Julen Lopetegui"
    },
    "away": {
      "formation": "4-3-3",
      "players": [
        {
          "name": "Gregor Kobel",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Denis Zakaria",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Nico Elvedi",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Manuel Akanji",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Ricardo Rodríguez",
          "number": 13,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Michel Aebischer",
          "number": 20,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Granit Xhaka",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Remo Freuler",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Dan Ndoye",
          "number": 11,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Breel Embolo",
          "number": 7,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Rubén Vargas",
          "number": 17,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Fabian Rieder",
          "number": 22,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Johan Manzambi",
          "number": 9,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Zeki Amdouni",
          "number": 23,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Miro Muheim",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Ardon Jashari",
          "number": 14,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Yvon Mvogo",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Marvin Keller",
          "number": 21,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Luca Jaquez",
          "number": 25,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Eray Cömert",
          "number": 18,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Aurèle Amenda",
          "number": 24,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Djibril Sow",
          "number": 15,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Silvan Widmer",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Christian Fassnacht",
          "number": 16,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Cédric Itten",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Noah Okafor",
          "number": 19,
          "pos": "FW",
          "starter": false
        }
      ],
      "coach": "Murat Yakin"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:36.700Z"
  },
  {
    "fixtureKey": "Saudi Arabia|Uruguay",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-4-2",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Scotland|Brazil",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Scotland|Morocco",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Senegal|Iraq",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-4-2",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "South Africa|South Korea",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "South Korea|Czech Republic",
    "home": {
      "formation": "3-4-2-1",
      "players": [
        {
          "name": "Kim Seung-Gyu",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "Lee Han-Beom",
          "number": 2,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Kim Min-Jae",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Lee Gi-Hyuk",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "Seol Young-Woo",
          "number": 22,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Hwang In-Beom",
          "number": 6,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Paik Seung-Ho",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Lee Tae-Seok",
          "number": 13,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "Lee Kang-In",
          "number": 19,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Lee Jae-Sung",
          "number": 10,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Son Heung-Min",
          "number": 7,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "Jo Hyeon-Woo",
          "number": 21,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Song Bum-Keun",
          "number": 12,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "Hwang Hee-Chan",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Kim Jin-Gyu",
          "number": 24,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Park Jin-Seob",
          "number": 16,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Lee Dong-Gyeong",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Cho Gue-Sung",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Oh Hyeon-Gyu",
          "number": 18,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Eom Ji-Sung",
          "number": 25,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "J. Castrop",
          "number": 23,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Kim Moon-Hwan",
          "number": 15,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Kim Tae-Hyeon",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Yang Hyun-Jun",
          "number": 20,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Bae Jun-Ho",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Cho Wi-Je",
          "number": 14,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Myung-Bo Hong"
    },
    "away": {
      "formation": "3-4-2-1",
      "players": [
        {
          "name": "M. Kovar",
          "number": 1,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "S. Chaloupek",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "R. Hranac",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "L. Krejci",
          "number": 7,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "V. Coufal",
          "number": 5,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "T. Soucek",
          "number": 22,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "A. Sojka",
          "number": 24,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "J. Zeleny",
          "number": 20,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "L. Provod",
          "number": 17,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "P. Sulc",
          "number": 15,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "P. Schick",
          "number": 10,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "J. Stanek",
          "number": 16,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "L. Hornicek",
          "number": 23,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "T. Holes",
          "number": 3,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "J. Kuchta",
          "number": 11,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "D. Doudera",
          "number": 21,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "D. Zima",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "D. Jurasek",
          "number": 14,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "A. Hlozek",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "L. Cerv",
          "number": 12,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "D. Visinsky",
          "number": 26,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "V. Darida",
          "number": 8,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "T. Chory",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "M. Sadilek",
          "number": 18,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "M. Chytil",
          "number": 13,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "H. Sochurek",
          "number": 25,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Miroslav Koubek"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:34.398Z"
  },
  {
    "fixtureKey": "Spain|Cape Verde Islands",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Spain|Saudi Arabia",
    "home": {
      "formation": "4-3-3",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Sweden|Tunisia",
    "home": {
      "formation": "3-4-2-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Switzerland|Bosnia & Herzegovina",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-4-2",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Switzerland|Canada",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-4-2",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Tunisia|Japan",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Tunisia|Netherlands",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Türkiye|Paraguay",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Türkiye|USA",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Uruguay|Cape Verde Islands",
    "home": {
      "formation": "4-4-2",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "Uruguay|Spain",
    "home": {
      "formation": "4-4-2",
      "players": []
    },
    "away": {
      "formation": "4-3-3",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "USA|Australia",
    "home": {
      "formation": "4-2-3-1",
      "players": []
    },
    "away": {
      "formation": "3-4-2-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  },
  {
    "fixtureKey": "USA|Paraguay",
    "home": {
      "formation": "4-2-3-1",
      "players": [
        {
          "name": "M. Freese",
          "number": 24,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "A. Freeman",
          "number": 16,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "C. Richards",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "T. Ream",
          "number": 13,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "A. Robinson",
          "number": 5,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "T. Adams",
          "number": 4,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "M. Tillman",
          "number": 17,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "S. Dest",
          "number": 2,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "W. McKennie",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "C. Pulisic",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "F. Balogun",
          "number": 20,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "C. Brady",
          "number": 25,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "M. Turner",
          "number": 1,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "A. Trusty",
          "number": 6,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "R. Pepi",
          "number": 9,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "G. Reyna",
          "number": 7,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "S. Berhalter",
          "number": 14,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "H. Wright",
          "number": 19,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "C. Roldan",
          "number": 15,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Zendejas",
          "number": 26,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "T. Weah",
          "number": 21,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "M. Robinson",
          "number": 12,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "B. Aaronson",
          "number": 11,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "M. McKenzie",
          "number": 22,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "J. Scally",
          "number": 23,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "M. Arfsten",
          "number": 18,
          "pos": "MF",
          "starter": false
        }
      ],
      "coach": "Mauricio Pochettino"
    },
    "away": {
      "formation": "4-4-2",
      "players": [
        {
          "name": "O. Gill",
          "number": 12,
          "pos": "GK",
          "starter": true
        },
        {
          "name": "J. Caceres",
          "number": 4,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "G. Gomez",
          "number": 15,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "O. Alderete",
          "number": 3,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "J. Alonso",
          "number": 6,
          "pos": "DF",
          "starter": true
        },
        {
          "name": "D. Gomez",
          "number": 8,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "A. Cubas",
          "number": 14,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "D. Bobadilla",
          "number": 16,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "M. Almiron",
          "number": 10,
          "pos": "MF",
          "starter": true
        },
        {
          "name": "A. Sanabria",
          "number": 9,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "J. Enciso",
          "number": 19,
          "pos": "FW",
          "starter": true
        },
        {
          "name": "R. Fernandez",
          "number": 1,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "G. Olveira",
          "number": 22,
          "pos": "GK",
          "starter": false
        },
        {
          "name": "G. Velazquez",
          "number": 2,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "Fabian Balbuena",
          "number": 5,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "G. Avalos",
          "number": 21,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "G. Caballero",
          "number": 24,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "J. Canale",
          "number": 13,
          "pos": "DF",
          "starter": false
        },
        {
          "name": "I. Pitta",
          "number": 25,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "M. Galarza",
          "number": 23,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "Mauricio",
          "number": 11,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "R. Sosa",
          "number": 7,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "Kaku",
          "number": 17,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Arce",
          "number": 18,
          "pos": "FW",
          "starter": false
        },
        {
          "name": "B. Ojeda",
          "number": 20,
          "pos": "MF",
          "starter": false
        },
        {
          "name": "A. Maidana",
          "number": 26,
          "pos": "DF",
          "starter": false
        }
      ],
      "coach": "Gustavo Alfaro"
    },
    "confirmed": true,
    "source": "api-football",
    "updatedAt": "2026-06-14T20:06:36.342Z"
  },
  {
    "fixtureKey": "Uzbekistan|Colombia",
    "home": {
      "formation": "3-4-2-1",
      "players": []
    },
    "away": {
      "formation": "4-2-3-1",
      "players": []
    },
    "confirmed": false,
    "source": "baseline",
    "updatedAt": "2026-06-12T16:43:43.362Z"
  }
];

export const LINEUPS_LAST_UPDATED = '2026-06-14T20:06:39.125Z';
