// Auto-generated by scripts/sync-market-odds.ts — do not edit manually.
// Pre-match bookmaker consensus (de-vigged) + api-football model prediction per
// fixture, powering the "Lili vs The Market" screen (app/lili-vs-market.tsx).

export interface MarketTriple { home: number; draw: number; away: number }

export interface MarketOdds {
  fixtureId: string;
  home: string;
  away: string;
  market: MarketTriple | null;  // bookmaker consensus, de-vigged (probs sum to 1)
  model: MarketTriple | null;   // api-football /predictions percentages (0..1)
  advice: string | null;        // api-football betting advice, verbatim
  bookmakers: number;           // books contributing to the consensus
}

export const MARKET_ODDS: MarketOdds[] = [
  { fixtureId: "B1_Canada_v_Bosnia_Herzegovina", home: "Canada", away: "Bosnia & Herzegovina", market: { home: 0.5200, draw: 0.2755, away: 0.2045 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "C1_USA_v_Paraguay", home: "USA", away: "Paraguay", market: { home: 0.4594, draw: 0.2959, away: 0.2448 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : USA or draw", bookmakers: 14 },
  { fixtureId: "B1_Qatar_v_Switzerland", home: "Qatar", away: "Switzerland", market: { home: 0.0679, draw: 0.1421, away: 0.7901 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : Qatar or draw", bookmakers: 14 },
  { fixtureId: "D1_Brazil_v_Morocco", home: "Brazil", away: "Morocco", market: { home: 0.5720, draw: 0.2526, away: 0.1754 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Morocco", bookmakers: 14 },
  { fixtureId: "D1_Haiti_v_Scotland", home: "Haiti", away: "Scotland", market: { home: 0.1592, draw: 0.2152, away: 0.6256 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "C1_Australia_v_T_rkiye", home: "Australia", away: "Türkiye", market: { home: 0.1841, draw: 0.2578, away: 0.5581 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "E1_Germany_v_Cura_ao", home: "Germany", away: "Curaçao", market: { home: 0.9266, draw: 0.0502, away: 0.0232 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F1_Netherlands_v_Japan", home: "Netherlands", away: "Japan", market: { home: 0.4619, draw: 0.2776, away: 0.2605 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : Netherlands or draw", bookmakers: 14 },
  { fixtureId: "E1_Ivory_Coast_v_Ecuador", home: "Ivory Coast", away: "Ecuador", market: { home: 0.2918, draw: 0.3324, away: 0.3758 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F1_Sweden_v_Tunisia", home: "Sweden", away: "Tunisia", market: { home: 0.5004, draw: 0.2821, away: 0.2175 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "G1_Spain_v_Cape_Verde_Islands", home: "Spain", away: "Cape Verde Islands", market: { home: 0.8866, draw: 0.0797, away: 0.0337 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "H1_Belgium_v_Egypt", home: "Belgium", away: "Egypt", market: { home: 0.6053, draw: 0.2355, away: 0.1592 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Belgium or draw", bookmakers: 14 },
  { fixtureId: "G1_Saudi_Arabia_v_Uruguay", home: "Saudi Arabia", away: "Uruguay", market: { home: 0.1195, draw: 0.2213, away: 0.6592 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Uruguay", bookmakers: 14 },
  { fixtureId: "H1_Iran_v_New_Zealand", home: "Iran", away: "New Zealand", market: { home: 0.5240, draw: 0.2740, away: 0.2020 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "I1_France_v_Senegal", home: "France", away: "Senegal", market: { home: 0.6485, draw: 0.2134, away: 0.1381 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "I1_Iraq_v_Norway", home: "Iraq", away: "Norway", market: { home: 0.0716, draw: 0.1457, away: 0.7827 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "J1_Argentina_v_Algeria", home: "Argentina", away: "Algeria", market: { home: 0.6422, draw: 0.2253, away: 0.1325 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "J1_Austria_v_Jordan", home: "Austria", away: "Jordan", market: { home: 0.6867, draw: 0.1982, away: 0.1151 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "K1_Portugal_v_Congo_DR", home: "Portugal", away: "Congo DR", market: { home: 0.7425, draw: 0.1745, away: 0.0830 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "L1_England_v_Croatia", home: "England", away: "Croatia", market: { home: 0.5585, draw: 0.2571, away: 0.1843 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : England or draw", bookmakers: 14 },
  { fixtureId: "L1_Ghana_v_Panama", home: "Ghana", away: "Panama", market: { home: 0.4116, draw: 0.2975, away: 0.2909 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "K1_Uzbekistan_v_Colombia", home: "Uzbekistan", away: "Colombia", market: { home: 0.1073, draw: 0.2081, away: 0.6846 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "A2_Czech_Republic_v_South_Africa", home: "Czech Republic", away: "South Africa", market: { home: 0.5134, draw: 0.2736, away: 0.2130 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Czechia or draw", bookmakers: 14 },
  { fixtureId: "B2_Switzerland_v_Bosnia_Herzegovina", home: "Switzerland", away: "Bosnia & Herzegovina", market: { home: 0.6085, draw: 0.2354, away: 0.1562 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "B2_Canada_v_Qatar", home: "Canada", away: "Qatar", market: { home: 0.7285, draw: 0.1775, away: 0.0940 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Canada or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "A2_Mexico_v_South_Korea", home: "Mexico", away: "South Korea", market: { home: 0.4671, draw: 0.2921, away: 0.2407 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Mexico or draw", bookmakers: 14 },
  { fixtureId: "C2_USA_v_Australia", home: "USA", away: "Australia", market: { home: 0.5790, draw: 0.2296, away: 0.1914 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : USA", bookmakers: 13 },
  { fixtureId: "D2_Scotland_v_Morocco", home: "Scotland", away: "Morocco", market: { home: 0.1738, draw: 0.2664, away: 0.5598 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Scotland or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "D2_Brazil_v_Haiti", home: "Brazil", away: "Haiti", market: { home: 0.8632, draw: 0.0937, away: 0.0430 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Brazil or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "C2_T_rkiye_v_Paraguay", home: "Türkiye", away: "Paraguay", market: { home: 0.4590, draw: 0.2855, away: 0.2556 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F2_Netherlands_v_Sweden", home: "Netherlands", away: "Sweden", market: { home: 0.5462, draw: 0.2454, away: 0.2084 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Winner : Sweden and +2.5 goals", bookmakers: 14 },
  { fixtureId: "E2_Germany_v_Ivory_Coast", home: "Germany", away: "Ivory Coast", market: { home: 0.6178, draw: 0.2131, away: 0.1691 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Winner : Germany and +1.5 goals", bookmakers: 14 },
  { fixtureId: "E2_Ecuador_v_Cura_ao", home: "Ecuador", away: "Curaçao", market: { home: 0.8560, draw: 0.1019, away: 0.0420 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F2_Tunisia_v_Japan", home: "Tunisia", away: "Japan", market: { home: 0.1466, draw: 0.2388, away: 0.6145 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Japan and +2.5 goals", bookmakers: 14 },
  { fixtureId: "G2_Spain_v_Saudi_Arabia", home: "Spain", away: "Saudi Arabia", market: { home: 0.8658, draw: 0.0958, away: 0.0384 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Spain or draw and -2.5 goals", bookmakers: 14 },
  { fixtureId: "H2_Belgium_v_Iran", home: "Belgium", away: "Iran", market: { home: 0.6635, draw: 0.2076, away: 0.1288 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : Belgium or draw", bookmakers: 14 },
  { fixtureId: "G2_Uruguay_v_Cape_Verde_Islands", home: "Uruguay", away: "Cape Verde Islands", market: { home: 0.6474, draw: 0.2288, away: 0.1238 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Uruguay or draw and -2.5 goals", bookmakers: 14 },
  { fixtureId: "H2_New_Zealand_v_Egypt", home: "New Zealand", away: "Egypt", market: { home: 0.1720, draw: 0.2418, away: 0.5862 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Double chance : draw or Egypt", bookmakers: 14 },
  { fixtureId: "J2_Argentina_v_Austria", home: "Argentina", away: "Austria", market: { home: 0.5963, draw: 0.2446, away: 0.1591 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Argentina or draw", bookmakers: 13 },
  { fixtureId: "I2_France_v_Iraq", home: "France", away: "Iraq", market: { home: 0.8755, draw: 0.0909, away: 0.0336 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Combo Winner : France and +1.5 goals", bookmakers: 13 },
  { fixtureId: "I2_Norway_v_Senegal", home: "Norway", away: "Senegal", market: { home: 0.4115, draw: 0.2766, away: 0.3119 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Combo Winner : Norway and +1.5 goals", bookmakers: 13 },
  { fixtureId: "J2_Jordan_v_Algeria", home: "Jordan", away: "Algeria", market: { home: 0.1626, draw: 0.2349, away: 0.6025 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Jordan or draw", bookmakers: 13 },
  { fixtureId: "K2_Portugal_v_Uzbekistan", home: "Portugal", away: "Uzbekistan", market: { home: 0.7889, draw: 0.1459, away: 0.0652 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Portugal or draw", bookmakers: 13 },
  { fixtureId: "L2_England_v_Ghana", home: "England", away: "Ghana", market: { home: 0.7760, draw: 0.1541, away: 0.0699 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Winner : England", bookmakers: 13 },
  { fixtureId: "L2_Panama_v_Croatia", home: "Panama", away: "Croatia", market: { home: 0.1428, draw: 0.2404, away: 0.6168 }, model: null, advice: null, bookmakers: 13 },
  { fixtureId: "K2_Colombia_v_Congo_DR", home: "Colombia", away: "Congo DR", market: { home: 0.6340, draw: 0.2309, away: 0.1351 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : Colombia", bookmakers: 13 },
  { fixtureId: "B3_Switzerland_v_Canada", home: "Switzerland", away: "Canada", market: { home: 0.3947, draw: 0.3092, away: 0.2960 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Canada and +1.5 goals", bookmakers: 13 },
  { fixtureId: "B3_Bosnia_Herzegovina_v_Qatar", home: "Bosnia & Herzegovina", away: "Qatar", market: { home: 0.6639, draw: 0.2017, away: 0.1345 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Bosnia & Herzegovina or draw and +1.5 goals", bookmakers: 13 },
  { fixtureId: "D3_Morocco_v_Haiti", home: "Morocco", away: "Haiti", market: { home: 0.7453, draw: 0.1706, away: 0.0842 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Morocco or draw and -3.5 goals", bookmakers: 13 },
  { fixtureId: "D3_Scotland_v_Brazil", home: "Scotland", away: "Brazil", market: { home: 0.1330, draw: 0.2003, away: 0.6667 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Scotland or draw and -3.5 goals", bookmakers: 13 },
  { fixtureId: "A3_Czech_Republic_v_Mexico", home: "Czech Republic", away: "Mexico", market: { home: 0.2838, draw: 0.2672, away: 0.4490 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Mexico and -3.5 goals", bookmakers: 13 },
  { fixtureId: "A3_South_Africa_v_South_Korea", home: "South Africa", away: "South Korea", market: { home: 0.1750, draw: 0.2483, away: 0.5768 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Combo Double chance : draw or South Korea and -3.5 goals", bookmakers: 13 },
  { fixtureId: "E3_Ecuador_v_Germany", home: "Ecuador", away: "Germany", market: { home: 0.1909, draw: 0.2502, away: 0.5588 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Winner : Germany and +1.5 goals", bookmakers: 13 },
  { fixtureId: "E3_Cura_ao_v_Ivory_Coast", home: "Curaçao", away: "Ivory Coast", market: { home: 0.0490, draw: 0.1155, away: 0.8356 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Ivory Coast and +1.5 goals", bookmakers: 13 },
  { fixtureId: "F3_Japan_v_Sweden", home: "Japan", away: "Sweden", market: { home: 0.4403, draw: 0.2797, away: 0.2801 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Combo Winner : Sweden and +2.5 goals", bookmakers: 13 },
  { fixtureId: "F3_Tunisia_v_Netherlands", home: "Tunisia", away: "Netherlands", market: { home: 0.1035, draw: 0.1849, away: 0.7116 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Combo Double chance : draw or Netherlands and +2.5 goals", bookmakers: 13 },
  { fixtureId: "C3_T_rkiye_v_USA", home: "Türkiye", away: "USA", market: { home: 0.3392, draw: 0.2630, away: 0.3978 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Winner : USA", bookmakers: 12 },
  { fixtureId: "C3_Paraguay_v_Australia", home: "Paraguay", away: "Australia", market: { home: 0.4364, draw: 0.2885, away: 0.2751 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Australia", bookmakers: 13 },
  { fixtureId: "I3_Senegal_v_Iraq", home: "Senegal", away: "Iraq", market: { home: 0.7175, draw: 0.1874, away: 0.0951 }, model: null, advice: null, bookmakers: 13 },
  { fixtureId: "I3_Norway_v_France", home: "Norway", away: "France", market: { home: 0.2207, draw: 0.2539, away: 0.5254 }, model: null, advice: null, bookmakers: 13 },
  { fixtureId: "G3_Uruguay_v_Spain", home: "Uruguay", away: "Spain", market: { home: 0.1594, draw: 0.2299, away: 0.6107 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Spain and -2.5 goals", bookmakers: 13 },
  { fixtureId: "G3_Cape_Verde_Islands_v_Saudi_Arabia", home: "Cape Verde Islands", away: "Saudi Arabia", market: { home: 0.3451, draw: 0.2684, away: 0.3865 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Cape Verde Islands or draw and -2.5 goals", bookmakers: 13 },
  { fixtureId: "H3_Egypt_v_Iran", home: "Egypt", away: "Iran", market: { home: 0.4531, draw: 0.3029, away: 0.2440 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : Egypt or draw", bookmakers: 13 },
  { fixtureId: "H3_New_Zealand_v_Belgium", home: "New Zealand", away: "Belgium", market: { home: 0.0755, draw: 0.1560, away: 0.7685 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : New Zealand or draw", bookmakers: 13 },
  { fixtureId: "L3_Croatia_v_Ghana", home: "Croatia", away: "Ghana", market: { home: 0.5858, draw: 0.2479, away: 0.1662 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Double chance : draw or Ghana", bookmakers: 13 },
  { fixtureId: "L3_Panama_v_England", home: "Panama", away: "England", market: { home: 0.0888, draw: 0.1540, away: 0.7572 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Winner : England", bookmakers: 13 },
  { fixtureId: "K3_Colombia_v_Portugal", home: "Colombia", away: "Portugal", market: { home: 0.2619, draw: 0.2788, away: 0.4592 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : Colombia", bookmakers: 13 },
  { fixtureId: "K3_Congo_DR_v_Uzbekistan", home: "Congo DR", away: "Uzbekistan", market: { home: 0.4438, draw: 0.2709, away: 0.2853 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Congo DR or draw", bookmakers: 13 },
  { fixtureId: "J3_Algeria_v_Austria", home: "Algeria", away: "Austria", market: { home: 0.3087, draw: 0.3071, away: 0.3842 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Winner : Austria", bookmakers: 13 },
  { fixtureId: "J3_Jordan_v_Argentina", home: "Jordan", away: "Argentina", market: { home: 0.0681, draw: 0.1434, away: 0.7885 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Winner : Argentina", bookmakers: 13 },
];

export const MARKET_ODDS_LAST_UPDATED = '2026-06-19T21:19:02.567Z';
