// Auto-generated by scripts/sync-market-odds.ts — do not edit manually.
// Pre-match bookmaker consensus (de-vigged) + api-football model prediction per
// fixture, powering the "Lili vs The Market" screen (app/lili-vs-market.tsx).

export interface MarketTriple { home: number; draw: number; away: number }

export interface MarketOdds {
  fixtureId: string;
  home: string;
  away: string;
  market: MarketTriple | null;  // bookmaker consensus, de-vigged (probs sum to 1)
  model: MarketTriple | null;   // api-football /predictions percentages (0..1)
  advice: string | null;        // api-football betting advice, verbatim
  bookmakers: number;           // books contributing to the consensus
}

export const MARKET_ODDS: MarketOdds[] = [
  { fixtureId: "C1_USA_v_Paraguay", home: "USA", away: "Paraguay", market: null, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : USA or draw", bookmakers: 0 },
  { fixtureId: "B1_Qatar_v_Switzerland", home: "Qatar", away: "Switzerland", market: null, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : Qatar or draw", bookmakers: 0 },
  { fixtureId: "D1_Brazil_v_Morocco", home: "Brazil", away: "Morocco", market: null, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Morocco", bookmakers: 0 },
  { fixtureId: "C1_Australia_v_T_rkiye", home: "Australia", away: "Türkiye", market: { home: 0.1841, draw: 0.2578, away: 0.5581 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "E1_Germany_v_Cura_ao", home: "Germany", away: "Curaçao", market: { home: 0.9266, draw: 0.0502, away: 0.0232 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F1_Netherlands_v_Japan", home: "Netherlands", away: "Japan", market: { home: 0.4619, draw: 0.2776, away: 0.2605 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Double chance : Netherlands or draw", bookmakers: 14 },
  { fixtureId: "E1_Ivory_Coast_v_Ecuador", home: "Ivory Coast", away: "Ecuador", market: { home: 0.2918, draw: 0.3324, away: 0.3758 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F1_Sweden_v_Tunisia", home: "Sweden", away: "Tunisia", market: { home: 0.5004, draw: 0.2821, away: 0.2175 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "G1_Spain_v_Cape_Verde_Islands", home: "Spain", away: "Cape Verde Islands", market: { home: 0.8866, draw: 0.0797, away: 0.0337 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "H1_Belgium_v_Egypt", home: "Belgium", away: "Egypt", market: { home: 0.6053, draw: 0.2355, away: 0.1592 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Belgium or draw", bookmakers: 14 },
  { fixtureId: "G1_Saudi_Arabia_v_Uruguay", home: "Saudi Arabia", away: "Uruguay", market: { home: 0.1195, draw: 0.2213, away: 0.6592 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Uruguay", bookmakers: 14 },
  { fixtureId: "H1_Iran_v_New_Zealand", home: "Iran", away: "New Zealand", market: { home: 0.5240, draw: 0.2740, away: 0.2020 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "I1_France_v_Senegal", home: "France", away: "Senegal", market: { home: 0.6485, draw: 0.2134, away: 0.1381 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "I1_Iraq_v_Norway", home: "Iraq", away: "Norway", market: { home: 0.0716, draw: 0.1457, away: 0.7827 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "J1_Argentina_v_Algeria", home: "Argentina", away: "Algeria", market: { home: 0.6422, draw: 0.2253, away: 0.1325 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "J1_Austria_v_Jordan", home: "Austria", away: "Jordan", market: { home: 0.6867, draw: 0.1982, away: 0.1151 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "K1_Portugal_v_Congo_DR", home: "Portugal", away: "Congo DR", market: { home: 0.7425, draw: 0.1745, away: 0.0830 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "L1_England_v_Croatia", home: "England", away: "Croatia", market: { home: 0.5585, draw: 0.2571, away: 0.1843 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : England or draw", bookmakers: 14 },
  { fixtureId: "L1_Ghana_v_Panama", home: "Ghana", away: "Panama", market: { home: 0.4116, draw: 0.2975, away: 0.2909 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "K1_Uzbekistan_v_Colombia", home: "Uzbekistan", away: "Colombia", market: { home: 0.1073, draw: 0.2081, away: 0.6846 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "A2_Czech_Republic_v_South_Africa", home: "Czech Republic", away: "South Africa", market: { home: 0.5134, draw: 0.2736, away: 0.2130 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Czechia or draw", bookmakers: 14 },
  { fixtureId: "B2_Switzerland_v_Bosnia_Herzegovina", home: "Switzerland", away: "Bosnia & Herzegovina", market: { home: 0.6085, draw: 0.2354, away: 0.1562 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "B2_Canada_v_Qatar", home: "Canada", away: "Qatar", market: { home: 0.7285, draw: 0.1775, away: 0.0940 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Canada or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "A2_Mexico_v_South_Korea", home: "Mexico", away: "South Korea", market: { home: 0.4671, draw: 0.2921, away: 0.2407 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Mexico or draw", bookmakers: 14 },
  { fixtureId: "C2_USA_v_Australia", home: "USA", away: "Australia", market: { home: 0.5790, draw: 0.2296, away: 0.1914 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : USA", bookmakers: 13 },
  { fixtureId: "D2_Scotland_v_Morocco", home: "Scotland", away: "Morocco", market: { home: 0.1705, draw: 0.2664, away: 0.5631 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Scotland or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "D2_Brazil_v_Haiti", home: "Brazil", away: "Haiti", market: { home: 0.8650, draw: 0.0925, away: 0.0425 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Brazil or draw and -3.5 goals", bookmakers: 14 },
  { fixtureId: "C2_T_rkiye_v_Paraguay", home: "Türkiye", away: "Paraguay", market: { home: 0.4670, draw: 0.2860, away: 0.2471 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F2_Netherlands_v_Sweden", home: "Netherlands", away: "Sweden", market: { home: 0.5549, draw: 0.2392, away: 0.2059 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Winner : Sweden and +2.5 goals", bookmakers: 14 },
  { fixtureId: "E2_Germany_v_Ivory_Coast", home: "Germany", away: "Ivory Coast", market: { home: 0.6467, draw: 0.2047, away: 0.1486 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Winner : Germany and +1.5 goals", bookmakers: 14 },
  { fixtureId: "E2_Ecuador_v_Cura_ao", home: "Ecuador", away: "Curaçao", market: { home: 0.8162, draw: 0.1262, away: 0.0576 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "F2_Tunisia_v_Japan", home: "Tunisia", away: "Japan", market: { home: 0.1299, draw: 0.2275, away: 0.6425 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Japan and +2.5 goals", bookmakers: 14 },
  { fixtureId: "G2_Spain_v_Saudi_Arabia", home: "Spain", away: "Saudi Arabia", market: { home: 0.8667, draw: 0.0946, away: 0.0387 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Spain or draw and -2.5 goals", bookmakers: 14 },
  { fixtureId: "H2_Belgium_v_Iran", home: "Belgium", away: "Iran", market: { home: 0.6658, draw: 0.2090, away: 0.1251 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : Belgium or draw", bookmakers: 14 },
  { fixtureId: "G2_Uruguay_v_Cape_Verde_Islands", home: "Uruguay", away: "Cape Verde Islands", market: { home: 0.6491, draw: 0.2303, away: 0.1206 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Uruguay or draw and -2.5 goals", bookmakers: 14 },
  { fixtureId: "H2_New_Zealand_v_Egypt", home: "New Zealand", away: "Egypt", market: { home: 0.1693, draw: 0.2378, away: 0.5929 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Double chance : draw or Egypt", bookmakers: 14 },
  { fixtureId: "J2_Argentina_v_Austria", home: "Argentina", away: "Austria", market: { home: 0.6019, draw: 0.2431, away: 0.1550 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Argentina or draw", bookmakers: 14 },
  { fixtureId: "I2_France_v_Iraq", home: "France", away: "Iraq", market: { home: 0.8748, draw: 0.0907, away: 0.0345 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Combo Winner : France and +1.5 goals", bookmakers: 14 },
  { fixtureId: "I2_Norway_v_Senegal", home: "Norway", away: "Senegal", market: { home: 0.4211, draw: 0.2764, away: 0.3025 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Combo Winner : Norway and +1.5 goals", bookmakers: 14 },
  { fixtureId: "J2_Jordan_v_Algeria", home: "Jordan", away: "Algeria", market: { home: 0.1617, draw: 0.2346, away: 0.6038 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Jordan or draw", bookmakers: 14 },
  { fixtureId: "K2_Portugal_v_Uzbekistan", home: "Portugal", away: "Uzbekistan", market: { home: 0.7842, draw: 0.1476, away: 0.0683 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Portugal or draw", bookmakers: 14 },
  { fixtureId: "L2_England_v_Ghana", home: "England", away: "Ghana", market: { home: 0.7786, draw: 0.1506, away: 0.0709 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Winner : England", bookmakers: 14 },
  { fixtureId: "L2_Panama_v_Croatia", home: "Panama", away: "Croatia", market: { home: 0.1442, draw: 0.2395, away: 0.6163 }, model: null, advice: null, bookmakers: 14 },
  { fixtureId: "K2_Colombia_v_Congo_DR", home: "Colombia", away: "Congo DR", market: { home: 0.6305, draw: 0.2322, away: 0.1374 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : Colombia", bookmakers: 14 },
  { fixtureId: "B3_Switzerland_v_Canada", home: "Switzerland", away: "Canada", market: { home: 0.3953, draw: 0.3088, away: 0.2959 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Canada and +1.5 goals", bookmakers: 13 },
  { fixtureId: "B3_Bosnia_Herzegovina_v_Qatar", home: "Bosnia & Herzegovina", away: "Qatar", market: { home: 0.6622, draw: 0.2011, away: 0.1367 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Combo Double chance : Bosnia & Herzegovina or draw and +1.5 goals", bookmakers: 13 },
  { fixtureId: "D3_Morocco_v_Haiti", home: "Morocco", away: "Haiti", market: { home: 0.7934, draw: 0.1452, away: 0.0614 }, model: { home: 0.5000, draw: 0.5000, away: 0.0000 }, advice: "Combo Double chance : Morocco or draw and -3.5 goals", bookmakers: 13 },
  { fixtureId: "D3_Scotland_v_Brazil", home: "Scotland", away: "Brazil", market: { home: 0.1229, draw: 0.1910, away: 0.6861 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Brazil and -3.5 goals", bookmakers: 13 },
  { fixtureId: "A3_Czech_Republic_v_Mexico", home: "Czech Republic", away: "Mexico", market: { home: 0.2584, draw: 0.2591, away: 0.4825 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Mexico and -3.5 goals", bookmakers: 13 },
  { fixtureId: "A3_South_Africa_v_South_Korea", home: "South Africa", away: "South Korea", market: { home: 0.1742, draw: 0.2468, away: 0.5790 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Combo Double chance : draw or South Korea and -3.5 goals", bookmakers: 13 },
  { fixtureId: "E3_Ecuador_v_Germany", home: "Ecuador", away: "Germany", market: { home: 0.2549, draw: 0.2582, away: 0.4869 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Winner : Germany", bookmakers: 13 },
  { fixtureId: "E3_Cura_ao_v_Ivory_Coast", home: "Curaçao", away: "Ivory Coast", market: { home: 0.0522, draw: 0.1203, away: 0.8276 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Double chance : draw or Ivory Coast", bookmakers: 13 },
  { fixtureId: "F3_Japan_v_Sweden", home: "Japan", away: "Sweden", market: { home: 0.4452, draw: 0.2834, away: 0.2714 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Sweden and +2.5 goals", bookmakers: 13 },
  { fixtureId: "F3_Tunisia_v_Netherlands", home: "Tunisia", away: "Netherlands", market: { home: 0.0945, draw: 0.1741, away: 0.7314 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Combo Winner : Netherlands and +2.5 goals", bookmakers: 13 },
  { fixtureId: "C3_T_rkiye_v_USA", home: "Türkiye", away: "USA", market: { home: 0.3049, draw: 0.2461, away: 0.4491 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Winner : USA", bookmakers: 12 },
  { fixtureId: "C3_Paraguay_v_Australia", home: "Paraguay", away: "Australia", market: { home: 0.3563, draw: 0.3930, away: 0.2507 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Double chance : draw or Australia", bookmakers: 13 },
  { fixtureId: "I3_Senegal_v_Iraq", home: "Senegal", away: "Iraq", market: { home: 0.7220, draw: 0.1838, away: 0.0942 }, model: null, advice: null, bookmakers: 13 },
  { fixtureId: "I3_Norway_v_France", home: "Norway", away: "France", market: { home: 0.2209, draw: 0.2525, away: 0.5266 }, model: null, advice: null, bookmakers: 13 },
  { fixtureId: "G3_Uruguay_v_Spain", home: "Uruguay", away: "Spain", market: { home: 0.1590, draw: 0.2302, away: 0.6108 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Combo Double chance : draw or Spain and -2.5 goals", bookmakers: 13 },
  { fixtureId: "G3_Cape_Verde_Islands_v_Saudi_Arabia", home: "Cape Verde Islands", away: "Saudi Arabia", market: { home: 0.3458, draw: 0.2696, away: 0.3847 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Combo Double chance : Cape Verde Islands or draw and -2.5 goals", bookmakers: 13 },
  { fixtureId: "H3_Egypt_v_Iran", home: "Egypt", away: "Iran", market: { home: 0.4582, draw: 0.3007, away: 0.2411 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : Egypt or draw", bookmakers: 13 },
  { fixtureId: "H3_New_Zealand_v_Belgium", home: "New Zealand", away: "Belgium", market: { home: 0.0756, draw: 0.1570, away: 0.7675 }, model: { home: 0.3500, draw: 0.3500, away: 0.3000 }, advice: "Double chance : New Zealand or draw", bookmakers: 13 },
  { fixtureId: "L3_Croatia_v_Ghana", home: "Croatia", away: "Ghana", market: { home: 0.5870, draw: 0.2497, away: 0.1633 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Double chance : draw or Ghana", bookmakers: 13 },
  { fixtureId: "L3_Panama_v_England", home: "Panama", away: "England", market: { home: 0.0847, draw: 0.1476, away: 0.7678 }, model: { home: 0.1000, draw: 0.4500, away: 0.4500 }, advice: "Winner : England", bookmakers: 13 },
  { fixtureId: "K3_Colombia_v_Portugal", home: "Colombia", away: "Portugal", market: { home: 0.2609, draw: 0.2791, away: 0.4600 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Winner : Colombia", bookmakers: 13 },
  { fixtureId: "K3_Congo_DR_v_Uzbekistan", home: "Congo DR", away: "Uzbekistan", market: { home: 0.4472, draw: 0.2701, away: 0.2827 }, model: { home: 0.4500, draw: 0.4500, away: 0.1000 }, advice: "Double chance : Congo DR or draw", bookmakers: 13 },
  { fixtureId: "J3_Algeria_v_Austria", home: "Algeria", away: "Austria", market: { home: 0.3096, draw: 0.3078, away: 0.3826 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Winner : Austria", bookmakers: 13 },
  { fixtureId: "J3_Jordan_v_Argentina", home: "Jordan", away: "Argentina", market: { home: 0.0691, draw: 0.1430, away: 0.7879 }, model: { home: 0.0000, draw: 0.5000, away: 0.5000 }, advice: "Winner : Argentina", bookmakers: 13 },
];

export const MARKET_ODDS_LAST_UPDATED = '2026-06-21T07:00:58.308Z';
