// Auto-generated by scripts/sync-live-stats.ts — do not edit manually.
// Live match statistics feeding the territory/pressure heatmap (lib/heatmap.ts).

export interface TeamMatchStats {
  team: string;
  possession: number;      // 0..1
  totalShots: number;
  shotsInsideBox: number;
  shotsOutsideBox: number;
  shotsOnGoal: number;
  corners: number;
  xg: number;
  passAccuracy: number;    // 0..1
  passes?: number;         // total passes attempted
  fouls?: number;
}

export interface MatchStats {
  fixtureId: string; // matches WCFixture.id
  home: string;
  away: string;
  date: string;
  status: 'LIVE' | 'FINISHED';
  elapsed: number | null;  // live minute, null when finished
  homeStats: TeamMatchStats;
  awayStats: TeamMatchStats;
}

export const MATCH_STATS: MatchStats[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Mexico", possession: 0.61, totalShots: 16, shotsInsideBox: 9, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 3, xg: 1.46, passAccuracy: 0.9, passes: 520, fouls: 12 },
    awayStats: { team: "South Africa", possession: 0.39, totalShots: 3, shotsInsideBox: 1, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 1, xg: 0.07, passAccuracy: 0.81, passes: 334, fouls: 11 },
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "South Korea", possession: 0.62, totalShots: 15, shotsInsideBox: 10, shotsOutsideBox: 5, shotsOnGoal: 6, corners: 4, xg: 2.3, passAccuracy: 0.87, passes: 541, fouls: 9 },
    awayStats: { team: "Czech Republic", possession: 0.38, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 4, corners: 5, xg: 0.83, passAccuracy: 0.7, passes: 327, fouls: 16 },
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Canada", possession: 0.61, totalShots: 13, shotsInsideBox: 10, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 9, xg: 1.23, passAccuracy: 0.74, passes: 421, fouls: 10 },
    awayStats: { team: "Bosnia & Herzegovina", possession: 0.39, totalShots: 8, shotsInsideBox: 5, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.96, passAccuracy: 0.63, passes: 271, fouls: 20 },
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "USA", possession: 0.65, totalShots: 16, shotsInsideBox: 13, shotsOutsideBox: 3, shotsOnGoal: 6, corners: 3, xg: 1.42, passAccuracy: 0.85, passes: 598, fouls: 13 },
    awayStats: { team: "Paraguay", possession: 0.35, totalShots: 9, shotsInsideBox: 4, shotsOutsideBox: 5, shotsOnGoal: 1, corners: 1, xg: 0.54, passAccuracy: 0.73, passes: 319, fouls: 17 },
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Qatar", possession: 0.32, totalShots: 6, shotsInsideBox: 4, shotsOutsideBox: 2, shotsOnGoal: 3, corners: 3, xg: 0.6, passAccuracy: 0.72, passes: 278, fouls: 12 },
    awayStats: { team: "Switzerland", possession: 0.68, totalShots: 26, shotsInsideBox: 18, shotsOutsideBox: 8, shotsOnGoal: 7, corners: 10, xg: 3.2, passAccuracy: 0.91, passes: 576, fouls: 11 },
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Brazil", possession: 0.51, totalShots: 12, shotsInsideBox: 9, shotsOutsideBox: 3, shotsOnGoal: 5, corners: 6, xg: 1.26, passAccuracy: 0.87, passes: 514, fouls: 16 },
    awayStats: { team: "Morocco", possession: 0.49, totalShots: 14, shotsInsideBox: 7, shotsOutsideBox: 7, shotsOnGoal: 3, corners: 2, xg: 1.37, passAccuracy: 0.86, passes: 486, fouls: 14 },
  },
  {
    fixtureId: "D1_Haiti_v_Scotland",
    home: "Haiti", away: "Scotland", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Haiti", possession: 0.54, totalShots: 15, shotsInsideBox: 8, shotsOutsideBox: 7, shotsOnGoal: 2, corners: 4, xg: 1.05, passAccuracy: 0.85, passes: 431, fouls: 23 },
    awayStats: { team: "Scotland", possession: 0.46, totalShots: 9, shotsInsideBox: 8, shotsOutsideBox: 1, shotsOnGoal: 2, corners: 3, xg: 1.05, passAccuracy: 0.82, passes: 374, fouls: 21 },
  },
  {
    fixtureId: "C1_Australia_v_T_rkiye",
    home: "Australia", away: "Türkiye", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Australia", possession: 0.28, totalShots: 9, shotsInsideBox: 6, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 5, xg: 1.18, passAccuracy: 0.74, passes: 271, fouls: 12 },
    awayStats: { team: "Türkiye", possession: 0.72, totalShots: 30, shotsInsideBox: 14, shotsOutsideBox: 16, shotsOnGoal: 8, corners: 8, xg: 1.36, passAccuracy: 0.9, passes: 704, fouls: 4 },
  },
  {
    fixtureId: "E1_Germany_v_Cura_ao",
    home: "Germany", away: "Curaçao", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Germany", possession: 0.65, totalShots: 26, shotsInsideBox: 21, shotsOutsideBox: 5, shotsOnGoal: 12, corners: 8, xg: 4.22, passAccuracy: 0.87, passes: 637, fouls: 18 },
    awayStats: { team: "Curaçao", possession: 0.35, totalShots: 8, shotsInsideBox: 4, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 1, xg: 0.41, passAccuracy: 0.82, passes: 343, fouls: 11 },
  },
  {
    fixtureId: "F1_Netherlands_v_Japan",
    home: "Netherlands", away: "Japan", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Netherlands", possession: 0.6, totalShots: 10, shotsInsideBox: 10, shotsOutsideBox: 0, shotsOnGoal: 6, corners: 5, xg: 0.78, passAccuracy: 0.88, passes: 524, fouls: 7 },
    awayStats: { team: "Japan", possession: 0.4, totalShots: 10, shotsInsideBox: 6, shotsOutsideBox: 4, shotsOnGoal: 3, corners: 4, xg: 0.59, passAccuracy: 0.84, passes: 341, fouls: 7 },
  },
  {
    fixtureId: "E1_Ivory_Coast_v_Ecuador",
    home: "Ivory Coast", away: "Ecuador", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Ivory Coast", possession: 0.48, totalShots: 15, shotsInsideBox: 8, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 3, xg: 1.52, passAccuracy: 0.84, passes: 470, fouls: 10 },
    awayStats: { team: "Ecuador", possession: 0.52, totalShots: 12, shotsInsideBox: 5, shotsOutsideBox: 7, shotsOnGoal: 1, corners: 5, xg: 1.01, passAccuracy: 0.85, passes: 492, fouls: 13 },
  },
  {
    fixtureId: "F1_Sweden_v_Tunisia",
    home: "Sweden", away: "Tunisia", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Sweden", possession: 0.49, totalShots: 13, shotsInsideBox: 9, shotsOutsideBox: 4, shotsOnGoal: 7, corners: 4, xg: 1.33, passAccuracy: 0.78, passes: 356, fouls: 10 },
    awayStats: { team: "Tunisia", possession: 0.51, totalShots: 6, shotsInsideBox: 2, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 2, xg: 0.28, passAccuracy: 0.79, passes: 371, fouls: 8 },
  },
  {
    fixtureId: "G1_Spain_v_Cape_Verde_Islands",
    home: "Spain", away: "Cape Verde Islands", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Spain", possession: 0.74, totalShots: 27, shotsInsideBox: 16, shotsOutsideBox: 11, shotsOnGoal: 7, corners: 11, xg: 2.1, passAccuracy: 0.92, passes: 800, fouls: 10 },
    awayStats: { team: "Cape Verde Islands", possession: 0.26, totalShots: 6, shotsInsideBox: 2, shotsOutsideBox: 4, shotsOnGoal: 1, corners: 1, xg: 0.2, passAccuracy: 0.74, passes: 278, fouls: 1 },
  },
  {
    fixtureId: "H1_Belgium_v_Egypt",
    home: "Belgium", away: "Egypt", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Belgium", possession: 0.54, totalShots: 15, shotsInsideBox: 9, shotsOutsideBox: 6, shotsOnGoal: 3, corners: 2, xg: 1.35, passAccuracy: 0.86, passes: 455, fouls: 15 },
    awayStats: { team: "Egypt", possession: 0.46, totalShots: 14, shotsInsideBox: 10, shotsOutsideBox: 4, shotsOnGoal: 3, corners: 7, xg: 1.08, passAccuracy: 0.81, passes: 398, fouls: 15 },
  },
  {
    fixtureId: "G1_Saudi_Arabia_v_Uruguay",
    home: "Saudi Arabia", away: "Uruguay", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Saudi Arabia", possession: 0.33, totalShots: 7, shotsInsideBox: 4, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.66, passAccuracy: 0.73, passes: 322, fouls: 11 },
    awayStats: { team: "Uruguay", possession: 0.67, totalShots: 27, shotsInsideBox: 16, shotsOutsideBox: 11, shotsOnGoal: 10, corners: 14, xg: 1.72, passAccuracy: 0.88, passes: 612, fouls: 6 },
  },
  {
    fixtureId: "H1_Iran_v_New_Zealand",
    home: "Iran", away: "New Zealand", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Iran", possession: 0.49, totalShots: 17, shotsInsideBox: 10, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 4, xg: 1.5, passAccuracy: 0.77, passes: 409, fouls: 10 },
    awayStats: { team: "New Zealand", possession: 0.51, totalShots: 14, shotsInsideBox: 10, shotsOutsideBox: 4, shotsOnGoal: 8, corners: 1, xg: 1.24, passAccuracy: 0.84, passes: 446, fouls: 8 },
  },
  {
    fixtureId: "I1_France_v_Senegal",
    home: "France", away: "Senegal", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "France", possession: 0.53, totalShots: 11, shotsInsideBox: 7, shotsOutsideBox: 4, shotsOnGoal: 8, corners: 6, xg: 1.79, passAccuracy: 0.88, passes: 575, fouls: 5 },
    awayStats: { team: "Senegal", possession: 0.47, totalShots: 6, shotsInsideBox: 4, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 4, xg: 0.53, passAccuracy: 0.86, passes: 502, fouls: 9 },
  },
  {
    fixtureId: "I1_Iraq_v_Norway",
    home: "Iraq", away: "Norway", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Iraq", possession: 0.39, totalShots: 11, shotsInsideBox: 8, shotsOutsideBox: 3, shotsOnGoal: 1, corners: 2, xg: 0.8, passAccuracy: 0.81, passes: 334, fouls: 12 },
    awayStats: { team: "Norway", possession: 0.61, totalShots: 12, shotsInsideBox: 11, shotsOutsideBox: 1, shotsOnGoal: 5, corners: 5, xg: 2.52, passAccuracy: 0.89, passes: 537, fouls: 13 },
  },
  {
    fixtureId: "J1_Argentina_v_Algeria",
    home: "Argentina", away: "Algeria", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Argentina", possession: 0.48, totalShots: 10, shotsInsideBox: 4, shotsOutsideBox: 6, shotsOnGoal: 6, corners: 2, xg: 1.47, passAccuracy: 0.9, passes: 561, fouls: 13 },
    awayStats: { team: "Algeria", possession: 0.52, totalShots: 7, shotsInsideBox: 3, shotsOutsideBox: 4, shotsOnGoal: 0, corners: 2, xg: 0.3, passAccuracy: 0.92, passes: 609, fouls: 8 },
  },
  {
    fixtureId: "J1_Austria_v_Jordan",
    home: "Austria", away: "Jordan", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Austria", possession: 0.63, totalShots: 11, shotsInsideBox: 6, shotsOutsideBox: 5, shotsOnGoal: 4, corners: 4, xg: 1.69, passAccuracy: 0.84, passes: 580, fouls: 12 },
    awayStats: { team: "Jordan", possession: 0.37, totalShots: 11, shotsInsideBox: 7, shotsOutsideBox: 4, shotsOnGoal: 4, corners: 3, xg: 1.15, passAccuracy: 0.73, passes: 332, fouls: 7 },
  },
  {
    fixtureId: "K1_Portugal_v_Congo_DR",
    home: "Portugal", away: "Congo DR", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Portugal", possession: 0.75, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 1, corners: 5, xg: 0.65, passAccuracy: 0.92, passes: 783, fouls: 9 },
    awayStats: { team: "Congo DR", possession: 0.25, totalShots: 8, shotsInsideBox: 2, shotsOutsideBox: 6, shotsOnGoal: 2, corners: 4, xg: 0.87, passAccuracy: 0.78, passes: 249, fouls: 10 },
  },
  {
    fixtureId: "L1_England_v_Croatia",
    home: "England", away: "Croatia", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "England", possession: 0.52, totalShots: 22, shotsInsideBox: 20, shotsOutsideBox: 2, shotsOnGoal: 11, corners: 8, xg: 3.2, passAccuracy: 0.86, passes: 474, fouls: 10 },
    awayStats: { team: "Croatia", possession: 0.48, totalShots: 10, shotsInsideBox: 4, shotsOutsideBox: 6, shotsOnGoal: 5, corners: 2, xg: 0.7, passAccuracy: 0.86, passes: 443, fouls: 12 },
  },
  {
    fixtureId: "L1_Ghana_v_Panama",
    home: "Ghana", away: "Panama", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Ghana", possession: 0.38, totalShots: 8, shotsInsideBox: 7, shotsOutsideBox: 1, shotsOnGoal: 2, corners: 2, xg: 1.31, passAccuracy: 0.83, passes: 351, fouls: 9 },
    awayStats: { team: "Panama", possession: 0.62, totalShots: 11, shotsInsideBox: 6, shotsOutsideBox: 5, shotsOnGoal: 4, corners: 2, xg: 0.73, passAccuracy: 0.86, passes: 583, fouls: 11 },
  },
  {
    fixtureId: "K1_Uzbekistan_v_Colombia",
    home: "Uzbekistan", away: "Colombia", date: "2026-06-18",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Uzbekistan", possession: 0.39, totalShots: 8, shotsInsideBox: 4, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 3, xg: 1.16, passAccuracy: 0.76, passes: 319, fouls: 14 },
    awayStats: { team: "Colombia", possession: 0.61, totalShots: 15, shotsInsideBox: 10, shotsOutsideBox: 5, shotsOnGoal: 4, corners: 4, xg: 1.61, passAccuracy: 0.86, passes: 519, fouls: 11 },
  },
  {
    fixtureId: "A2_Czech_Republic_v_South_Africa",
    home: "Czech Republic", away: "South Africa", date: "2026-06-18",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Czech Republic", possession: 0.38, totalShots: 14, shotsInsideBox: 11, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 5, xg: 1.02, passAccuracy: 0.8, passes: 341, fouls: 12 },
    awayStats: { team: "South Africa", possession: 0.62, totalShots: 17, shotsInsideBox: 6, shotsOutsideBox: 11, shotsOnGoal: 4, corners: 5, xg: 1.38, passAccuracy: 0.9, passes: 563, fouls: 10 },
  },
  {
    fixtureId: "B2_Switzerland_v_Bosnia_Herzegovina",
    home: "Switzerland", away: "Bosnia & Herzegovina", date: "2026-06-18",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Switzerland", possession: 0.62, totalShots: 13, shotsInsideBox: 9, shotsOutsideBox: 4, shotsOnGoal: 7, corners: 7, xg: 2.06, passAccuracy: 0.88, passes: 586, fouls: 7 },
    awayStats: { team: "Bosnia & Herzegovina", possession: 0.38, totalShots: 5, shotsInsideBox: 3, shotsOutsideBox: 2, shotsOnGoal: 3, corners: 3, xg: 0.23, passAccuracy: 0.81, passes: 354, fouls: 18 },
  },
  {
    fixtureId: "B2_Canada_v_Qatar",
    home: "Canada", away: "Qatar", date: "2026-06-18",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Canada", possession: 0.79, totalShots: 32, shotsInsideBox: 21, shotsOutsideBox: 11, shotsOnGoal: 10, corners: 19, xg: 4.6, passAccuracy: 0.91, passes: 567, fouls: 9 },
    awayStats: { team: "Qatar", possession: 0.21, totalShots: 2, shotsInsideBox: 1, shotsOutsideBox: 1, shotsOnGoal: 0, corners: 1, xg: 0.22, passAccuracy: 0.64, passes: 162, fouls: 10 },
  },
  {
    fixtureId: "A2_Mexico_v_South_Korea",
    home: "Mexico", away: "South Korea", date: "2026-06-19",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Mexico", possession: 0.42, totalShots: 8, shotsInsideBox: 5, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 0, xg: 0.53, passAccuracy: 0.82, passes: 427, fouls: 9 },
    awayStats: { team: "South Korea", possession: 0.58, totalShots: 9, shotsInsideBox: 6, shotsOutsideBox: 3, shotsOnGoal: 2, corners: 2, xg: 0.91, passAccuracy: 0.84, passes: 578, fouls: 7 },
  },
  {
    fixtureId: "C2_USA_v_Australia",
    home: "USA", away: "Australia", date: "2026-06-19",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "USA", possession: 0.62, totalShots: 10, shotsInsideBox: 8, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 7, xg: 1.08, passAccuracy: 0.85, passes: 523, fouls: 12 },
    awayStats: { team: "Australia", possession: 0.38, totalShots: 5, shotsInsideBox: 3, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 4, xg: 0.35, passAccuracy: 0.71, passes: 310, fouls: 16 },
  },
  {
    fixtureId: "D2_Scotland_v_Morocco",
    home: "Scotland", away: "Morocco", date: "2026-06-19",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Scotland", possession: 0.41, totalShots: 6, shotsInsideBox: 5, shotsOutsideBox: 1, shotsOnGoal: 0, corners: 2, xg: 0.51, passAccuracy: 0.85, passes: 456, fouls: 11 },
    awayStats: { team: "Morocco", possession: 0.59, totalShots: 12, shotsInsideBox: 9, shotsOutsideBox: 3, shotsOnGoal: 2, corners: 5, xg: 0.99, passAccuracy: 0.9, passes: 670, fouls: 8 },
  },
  {
    fixtureId: "D2_Brazil_v_Haiti",
    home: "Brazil", away: "Haiti", date: "2026-06-20",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Brazil", possession: 0.57, totalShots: 8, shotsInsideBox: 8, shotsOutsideBox: 0, shotsOnGoal: 5, corners: 4, xg: 1.75, passAccuracy: 0.88, passes: 525, fouls: 13 },
    awayStats: { team: "Haiti", possession: 0.43, totalShots: 7, shotsInsideBox: 4, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.23, passAccuracy: 0.83, passes: 399, fouls: 14 },
  },
  {
    fixtureId: "C2_T_rkiye_v_Paraguay",
    home: "Türkiye", away: "Paraguay", date: "2026-06-19",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Türkiye", possession: 0.79, totalShots: 32, shotsInsideBox: 16, shotsOutsideBox: 16, shotsOnGoal: 5, corners: 12, xg: 2.17, passAccuracy: 0.89, passes: 629, fouls: 14 },
    awayStats: { team: "Paraguay", possession: 0.21, totalShots: 7, shotsInsideBox: 3, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 0, xg: 0.32, passAccuracy: 0.54, passes: 178, fouls: 15 },
  },
  {
    fixtureId: "F2_Netherlands_v_Sweden",
    home: "Netherlands", away: "Sweden", date: "2026-06-20",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Netherlands", possession: 0.51, totalShots: 10, shotsInsideBox: 6, shotsOutsideBox: 4, shotsOnGoal: 7, corners: 2, xg: 2.61, passAccuracy: 0.89, passes: 449, fouls: 9 },
    awayStats: { team: "Sweden", possession: 0.49, totalShots: 16, shotsInsideBox: 7, shotsOutsideBox: 9, shotsOnGoal: 8, corners: 5, xg: 1.01, passAccuracy: 0.85, passes: 425, fouls: 12 },
  },
  {
    fixtureId: "E2_Germany_v_Ivory_Coast",
    home: "Germany", away: "Ivory Coast", date: "2026-06-20",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Germany", possession: 0.6, totalShots: 16, shotsInsideBox: 9, shotsOutsideBox: 7, shotsOnGoal: 7, corners: 8, xg: 1.89, passAccuracy: 0.89, passes: 624, fouls: 5 },
    awayStats: { team: "Ivory Coast", possession: 0.4, totalShots: 9, shotsInsideBox: 6, shotsOutsideBox: 3, shotsOnGoal: 2, corners: 3, xg: 1.22, passAccuracy: 0.85, passes: 431, fouls: 7 },
  },
  {
    fixtureId: "E2_Ecuador_v_Cura_ao",
    home: "Ecuador", away: "Curaçao", date: "2026-06-21",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Ecuador", possession: 0.75, totalShots: 28, shotsInsideBox: 22, shotsOutsideBox: 6, shotsOnGoal: 15, corners: 9, xg: 3.06, passAccuracy: 0.9, passes: 641, fouls: 7 },
    awayStats: { team: "Curaçao", possession: 0.25, totalShots: 10, shotsInsideBox: 4, shotsOutsideBox: 6, shotsOnGoal: 3, corners: 0, xg: 0.48, passAccuracy: 0.69, passes: 223, fouls: 10 },
  },
  {
    fixtureId: "F2_Tunisia_v_Japan",
    home: "Tunisia", away: "Japan", date: "2026-06-21",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Tunisia", possession: 0.38, totalShots: 2, shotsInsideBox: 1, shotsOutsideBox: 1, shotsOnGoal: 0, corners: 3, xg: 0.05, passAccuracy: 0.8, passes: 353, fouls: 8 },
    awayStats: { team: "Japan", possession: 0.62, totalShots: 11, shotsInsideBox: 8, shotsOutsideBox: 3, shotsOnGoal: 5, corners: 5, xg: 2.07, passAccuracy: 0.9, passes: 581, fouls: 15 },
  },
  {
    fixtureId: "G2_Spain_v_Saudi_Arabia",
    home: "Spain", away: "Saudi Arabia", date: "2026-06-21",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Spain", possession: 0.67, totalShots: 22, shotsInsideBox: 13, shotsOutsideBox: 9, shotsOnGoal: 8, corners: 6, xg: 2.85, passAccuracy: 0.92, passes: 725, fouls: 10 },
    awayStats: { team: "Saudi Arabia", possession: 0.33, totalShots: 3, shotsInsideBox: 0, shotsOutsideBox: 3, shotsOnGoal: 1, corners: 1, xg: 0.14, passAccuracy: 0.8, passes: 364, fouls: 2 },
  },
  {
    fixtureId: "H2_Belgium_v_Iran",
    home: "Belgium", away: "Iran", date: "2026-06-21",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Belgium", possession: 0.7, totalShots: 23, shotsInsideBox: 20, shotsOutsideBox: 3, shotsOnGoal: 7, corners: 4, xg: 1.8, passAccuracy: 0.86, passes: 622, fouls: 7 },
    awayStats: { team: "Iran", possession: 0.3, totalShots: 7, shotsInsideBox: 6, shotsOutsideBox: 1, shotsOnGoal: 3, corners: 2, xg: 0.63, passAccuracy: 0.74, passes: 268, fouls: 9 },
  },
  {
    fixtureId: "G2_Uruguay_v_Cape_Verde_Islands",
    home: "Uruguay", away: "Cape Verde Islands", date: "2026-06-21",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Uruguay", possession: 0.66, totalShots: 16, shotsInsideBox: 8, shotsOutsideBox: 8, shotsOnGoal: 2, corners: 11, xg: 2.28, passAccuracy: 0.83, passes: 494, fouls: 8 },
    awayStats: { team: "Cape Verde Islands", possession: 0.34, totalShots: 7, shotsInsideBox: 1, shotsOutsideBox: 6, shotsOnGoal: 2, corners: 3, xg: 0.77, passAccuracy: 0.74, passes: 256, fouls: 4 },
  },
  {
    fixtureId: "H2_New_Zealand_v_Egypt",
    home: "New Zealand", away: "Egypt", date: "2026-06-22",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "New Zealand", possession: 0.44, totalShots: 11, shotsInsideBox: 6, shotsOutsideBox: 5, shotsOnGoal: 5, corners: 4, xg: 1.12, passAccuracy: 0.8, passes: 420, fouls: 14 },
    awayStats: { team: "Egypt", possession: 0.56, totalShots: 19, shotsInsideBox: 12, shotsOutsideBox: 7, shotsOnGoal: 7, corners: 3, xg: 1.96, passAccuracy: 0.88, passes: 528, fouls: 8 },
  },
  {
    fixtureId: "J2_Argentina_v_Austria",
    home: "Argentina", away: "Austria", date: "2026-06-22",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Argentina", possession: 0.54, totalShots: 12, shotsInsideBox: 10, shotsOutsideBox: 2, shotsOnGoal: 5, corners: 1, xg: 2.65, passAccuracy: 0.89, passes: 553, fouls: 13 },
    awayStats: { team: "Austria", possession: 0.46, totalShots: 6, shotsInsideBox: 4, shotsOutsideBox: 2, shotsOnGoal: 1, corners: 3, xg: 0.5, passAccuracy: 0.86, passes: 468, fouls: 13 },
  },
  {
    fixtureId: "I2_France_v_Iraq",
    home: "France", away: "Iraq", date: "2026-06-22",
    status: "LIVE", elapsed: null,
    homeStats: { team: "France", possession: 0.58, totalShots: 7, shotsInsideBox: 1, shotsOutsideBox: 6, shotsOnGoal: 1, corners: 1, xg: 0.24, passAccuracy: 0.89, passes: 291, fouls: 5 },
    awayStats: { team: "Iraq", possession: 0.42, totalShots: 2, shotsInsideBox: 1, shotsOutsideBox: 1, shotsOnGoal: 0, corners: 1, xg: 0.16, passAccuracy: 0.8, passes: 213, fouls: 2 },
  },
];

export const MATCH_STATS_LAST_UPDATED = '2026-06-22T23:46:47.141Z';
