// Auto-generated by scripts/sync-live-stats.ts — do not edit manually.
// Live match statistics feeding the territory/pressure heatmap (lib/heatmap.ts).

export interface TeamMatchStats {
  team: string;
  possession: number;      // 0..1
  totalShots: number;
  shotsInsideBox: number;
  shotsOutsideBox: number;
  shotsOnGoal: number;
  corners: number;
  xg: number;
  passAccuracy: number;    // 0..1
  passes?: number;         // total passes attempted
  fouls?: number;
}

export interface MatchStats {
  fixtureId: string; // matches WCFixture.id
  home: string;
  away: string;
  date: string;
  status: 'LIVE' | 'FINISHED';
  elapsed: number | null;  // live minute, null when finished
  homeStats: TeamMatchStats;
  awayStats: TeamMatchStats;
}

export const MATCH_STATS: MatchStats[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Mexico", possession: 0.61, totalShots: 16, shotsInsideBox: 9, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 3, xg: 1.46, passAccuracy: 0.9, passes: 520, fouls: 12 },
    awayStats: { team: "South Africa", possession: 0.39, totalShots: 3, shotsInsideBox: 1, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 1, xg: 0.07, passAccuracy: 0.81, passes: 334, fouls: 11 },
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "South Korea", possession: 0.62, totalShots: 15, shotsInsideBox: 10, shotsOutsideBox: 5, shotsOnGoal: 6, corners: 4, xg: 2.3, passAccuracy: 0.87, passes: 541, fouls: 9 },
    awayStats: { team: "Czech Republic", possession: 0.38, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 4, corners: 5, xg: 0.83, passAccuracy: 0.7, passes: 327, fouls: 16 },
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Canada", possession: 0.61, totalShots: 13, shotsInsideBox: 10, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 9, xg: 1.23, passAccuracy: 0.74, passes: 421, fouls: 10 },
    awayStats: { team: "Bosnia & Herzegovina", possession: 0.39, totalShots: 8, shotsInsideBox: 5, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.96, passAccuracy: 0.63, passes: 271, fouls: 20 },
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "USA", possession: 0.65, totalShots: 16, shotsInsideBox: 13, shotsOutsideBox: 3, shotsOnGoal: 6, corners: 3, xg: 1.42, passAccuracy: 0.85, passes: 598, fouls: 13 },
    awayStats: { team: "Paraguay", possession: 0.35, totalShots: 9, shotsInsideBox: 4, shotsOutsideBox: 5, shotsOnGoal: 1, corners: 1, xg: 0.54, passAccuracy: 0.73, passes: 319, fouls: 17 },
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Qatar", possession: 0.32, totalShots: 6, shotsInsideBox: 4, shotsOutsideBox: 2, shotsOnGoal: 3, corners: 3, xg: 0.6, passAccuracy: 0.72, passes: 278, fouls: 12 },
    awayStats: { team: "Switzerland", possession: 0.68, totalShots: 26, shotsInsideBox: 18, shotsOutsideBox: 8, shotsOnGoal: 7, corners: 10, xg: 3.2, passAccuracy: 0.91, passes: 576, fouls: 11 },
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Brazil", possession: 0.51, totalShots: 12, shotsInsideBox: 9, shotsOutsideBox: 3, shotsOnGoal: 5, corners: 6, xg: 1.26, passAccuracy: 0.87, passes: 514, fouls: 16 },
    awayStats: { team: "Morocco", possession: 0.49, totalShots: 14, shotsInsideBox: 7, shotsOutsideBox: 7, shotsOnGoal: 3, corners: 2, xg: 1.37, passAccuracy: 0.86, passes: 486, fouls: 14 },
  },
  {
    fixtureId: "D1_Haiti_v_Scotland",
    home: "Haiti", away: "Scotland", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Haiti", possession: 0.54, totalShots: 15, shotsInsideBox: 8, shotsOutsideBox: 7, shotsOnGoal: 2, corners: 4, xg: 1.05, passAccuracy: 0.85, passes: 431, fouls: 23 },
    awayStats: { team: "Scotland", possession: 0.46, totalShots: 9, shotsInsideBox: 8, shotsOutsideBox: 1, shotsOnGoal: 2, corners: 3, xg: 1.05, passAccuracy: 0.82, passes: 374, fouls: 21 },
  },
  {
    fixtureId: "C1_Australia_v_T_rkiye",
    home: "Australia", away: "Türkiye", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Australia", possession: 0.28, totalShots: 9, shotsInsideBox: 6, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 5, xg: 1.18, passAccuracy: 0.74, passes: 271, fouls: 12 },
    awayStats: { team: "Türkiye", possession: 0.72, totalShots: 30, shotsInsideBox: 14, shotsOutsideBox: 16, shotsOnGoal: 8, corners: 8, xg: 1.36, passAccuracy: 0.9, passes: 704, fouls: 4 },
  },
  {
    fixtureId: "E1_Germany_v_Cura_ao",
    home: "Germany", away: "Curaçao", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Germany", possession: 0.65, totalShots: 26, shotsInsideBox: 21, shotsOutsideBox: 5, shotsOnGoal: 12, corners: 8, xg: 4.22, passAccuracy: 0.87, passes: 637, fouls: 18 },
    awayStats: { team: "Curaçao", possession: 0.35, totalShots: 8, shotsInsideBox: 4, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 1, xg: 0.41, passAccuracy: 0.82, passes: 343, fouls: 11 },
  },
  {
    fixtureId: "F1_Netherlands_v_Japan",
    home: "Netherlands", away: "Japan", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Netherlands", possession: 0.6, totalShots: 10, shotsInsideBox: 10, shotsOutsideBox: 0, shotsOnGoal: 6, corners: 5, xg: 0.78, passAccuracy: 0.88, passes: 524, fouls: 7 },
    awayStats: { team: "Japan", possession: 0.4, totalShots: 10, shotsInsideBox: 6, shotsOutsideBox: 4, shotsOnGoal: 3, corners: 4, xg: 0.59, passAccuracy: 0.84, passes: 341, fouls: 7 },
  },
  {
    fixtureId: "E1_Ivory_Coast_v_Ecuador",
    home: "Ivory Coast", away: "Ecuador", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Ivory Coast", possession: 0.48, totalShots: 15, shotsInsideBox: 8, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 3, xg: 1.52, passAccuracy: 0.84, passes: 470, fouls: 10 },
    awayStats: { team: "Ecuador", possession: 0.52, totalShots: 12, shotsInsideBox: 5, shotsOutsideBox: 7, shotsOnGoal: 1, corners: 5, xg: 1.01, passAccuracy: 0.85, passes: 492, fouls: 13 },
  },
  {
    fixtureId: "F1_Sweden_v_Tunisia",
    home: "Sweden", away: "Tunisia", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Sweden", possession: 0.49, totalShots: 13, shotsInsideBox: 9, shotsOutsideBox: 4, shotsOnGoal: 7, corners: 4, xg: 1.33, passAccuracy: 0.78, passes: 356, fouls: 10 },
    awayStats: { team: "Tunisia", possession: 0.51, totalShots: 6, shotsInsideBox: 2, shotsOutsideBox: 4, shotsOnGoal: 2, corners: 2, xg: 0.28, passAccuracy: 0.79, passes: 371, fouls: 8 },
  },
  {
    fixtureId: "G1_Spain_v_Cape_Verde_Islands",
    home: "Spain", away: "Cape Verde Islands", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Spain", possession: 0.74, totalShots: 27, shotsInsideBox: 16, shotsOutsideBox: 11, shotsOnGoal: 7, corners: 11, xg: 2.1, passAccuracy: 0.92, passes: 800, fouls: 10 },
    awayStats: { team: "Cape Verde Islands", possession: 0.26, totalShots: 6, shotsInsideBox: 2, shotsOutsideBox: 4, shotsOnGoal: 1, corners: 1, xg: 0.2, passAccuracy: 0.74, passes: 278, fouls: 1 },
  },
  {
    fixtureId: "H1_Belgium_v_Egypt",
    home: "Belgium", away: "Egypt", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Belgium", possession: 0.54, totalShots: 15, shotsInsideBox: 9, shotsOutsideBox: 6, shotsOnGoal: 3, corners: 2, xg: 1.35, passAccuracy: 0.86, passes: 455, fouls: 15 },
    awayStats: { team: "Egypt", possession: 0.46, totalShots: 14, shotsInsideBox: 10, shotsOutsideBox: 4, shotsOnGoal: 3, corners: 7, xg: 1.08, passAccuracy: 0.81, passes: 398, fouls: 15 },
  },
  {
    fixtureId: "G1_Saudi_Arabia_v_Uruguay",
    home: "Saudi Arabia", away: "Uruguay", date: "2026-06-15",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Saudi Arabia", possession: 0.33, totalShots: 7, shotsInsideBox: 4, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.66, passAccuracy: 0.73, passes: 322, fouls: 11 },
    awayStats: { team: "Uruguay", possession: 0.67, totalShots: 27, shotsInsideBox: 16, shotsOutsideBox: 11, shotsOnGoal: 10, corners: 14, xg: 1.72, passAccuracy: 0.88, passes: 612, fouls: 6 },
  },
  {
    fixtureId: "H1_Iran_v_New_Zealand",
    home: "Iran", away: "New Zealand", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Iran", possession: 0.48, totalShots: 17, shotsInsideBox: 10, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 4, xg: 1.5, passAccuracy: 0.77, passes: 405, fouls: 10 },
    awayStats: { team: "New Zealand", possession: 0.52, totalShots: 14, shotsInsideBox: 10, shotsOutsideBox: 4, shotsOnGoal: 8, corners: 1, xg: 1.24, passAccuracy: 0.85, passes: 446, fouls: 8 },
  },
  {
    fixtureId: "I1_France_v_Senegal",
    home: "France", away: "Senegal", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "France", possession: 0.53, totalShots: 11, shotsInsideBox: 7, shotsOutsideBox: 4, shotsOnGoal: 8, corners: 6, xg: 1.79, passAccuracy: 0.88, passes: 575, fouls: 5 },
    awayStats: { team: "Senegal", possession: 0.47, totalShots: 6, shotsInsideBox: 4, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 4, xg: 0.53, passAccuracy: 0.86, passes: 502, fouls: 9 },
  },
  {
    fixtureId: "I1_Iraq_v_Norway",
    home: "Iraq", away: "Norway", date: "2026-06-16",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Iraq", possession: 0.39, totalShots: 11, shotsInsideBox: 8, shotsOutsideBox: 3, shotsOnGoal: 1, corners: 2, xg: 0.8, passAccuracy: 0.81, passes: 334, fouls: 12 },
    awayStats: { team: "Norway", possession: 0.61, totalShots: 12, shotsInsideBox: 11, shotsOutsideBox: 1, shotsOnGoal: 5, corners: 5, xg: 2.52, passAccuracy: 0.89, passes: 537, fouls: 13 },
  },
  {
    fixtureId: "J1_Argentina_v_Algeria",
    home: "Argentina", away: "Algeria", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Argentina", possession: 0.48, totalShots: 10, shotsInsideBox: 4, shotsOutsideBox: 6, shotsOnGoal: 6, corners: 2, xg: 1.23, passAccuracy: 0.9, passes: 561, fouls: 13 },
    awayStats: { team: "Algeria", possession: 0.52, totalShots: 7, shotsInsideBox: 3, shotsOutsideBox: 4, shotsOnGoal: 0, corners: 2, xg: 0.31, passAccuracy: 0.92, passes: 607, fouls: 8 },
  },
  {
    fixtureId: "J1_Austria_v_Jordan",
    home: "Austria", away: "Jordan", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Austria", possession: 0.63, totalShots: 11, shotsInsideBox: 6, shotsOutsideBox: 5, shotsOnGoal: 4, corners: 4, xg: 1.66, passAccuracy: 0.84, passes: 580, fouls: 12 },
    awayStats: { team: "Jordan", possession: 0.37, totalShots: 11, shotsInsideBox: 7, shotsOutsideBox: 4, shotsOnGoal: 4, corners: 3, xg: 0.53, passAccuracy: 0.73, passes: 330, fouls: 7 },
  },
  {
    fixtureId: "K1_Portugal_v_Congo_DR",
    home: "Portugal", away: "Congo DR", date: "2026-06-17",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Portugal", possession: 0.75, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 1, corners: 5, xg: 0.69, passAccuracy: 0.92, passes: 783, fouls: 9 },
    awayStats: { team: "Congo DR", possession: 0.25, totalShots: 8, shotsInsideBox: 2, shotsOutsideBox: 6, shotsOnGoal: 2, corners: 4, xg: 0.82, passAccuracy: 0.78, passes: 251, fouls: 10 },
  },
  {
    fixtureId: "L1_England_v_Croatia",
    home: "England", away: "Croatia", date: "2026-06-17",
    status: "LIVE", elapsed: 45,
    homeStats: { team: "England", possession: 0.48, totalShots: 9, shotsInsideBox: 7, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 3, xg: 1.36, passAccuracy: 0.83, passes: 218, fouls: 6 },
    awayStats: { team: "Croatia", possession: 0.52, totalShots: 3, shotsInsideBox: 1, shotsOutsideBox: 2, shotsOnGoal: 1, corners: 1, xg: 0.23, passAccuracy: 0.87, passes: 232, fouls: 5 },
  },
];

export const MATCH_STATS_LAST_UPDATED = '2026-06-17T20:56:32.360Z';
