// Auto-generated by scripts/sync-match-events.ts — do not edit manually.
// Refreshed every 5 minutes during match windows via GitHub Actions.
// Source of truth for tournament intelligence (top scorers, cards).
// Player PROFILES stay hand-curated in lib/playerProfilesData.ts.

export type EventType = 'goal' | 'own-goal' | 'penalty';

export interface GoalEvent {
  player:           string;
  team:             string;
  minute:           number;
  minuteStoppage?:  number; // e.g. 5 for "45+5'"
  type:             EventType;
}

export interface CardEvent {
  player:  string;
  team:    string;
  minute?: number;
  reason?: string;
}

export interface MatchEvents {
  fixtureId:   string; // matches WCFixture.id
  home:        string;
  away:        string;
  date:        string; // YYYY-MM-DD
  goals:       GoalEvent[];
  yellowCards: CardEvent[];
  redCards:    CardEvent[];
}

export const MATCH_EVENTS: MatchEvents[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    goals: [
      { player: "Julián Quiñones", team: "Mexico", minute: 9, type: "goal" },
      { player: "Raúl Jiménez", team: "Mexico", minute: 67, type: "goal" },
    ],
    yellowCards: [
      { player: "Teboho Mokoena", team: "South Africa", minute: 17, reason: "Foul" },
      { player: "Brian Gutiérrez", team: "Mexico", minute: 23, reason: "Foul" },
      { player: "Nkosinathi Sibisi", team: "South Africa", minute: 74, reason: "Foul" },
    ],
    redCards: [
      { player: "Sphephelo Sithole", team: "South Africa", minute: 49, reason: "Professional foul last man" },
      { player: "Themba Zwane", team: "South Africa", minute: 84, reason: "Violent conduct" },
      { player: "César Montes", team: "Mexico", minute: 90, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    goals: [
      { player: "Ladislav Krejčí", team: "Czech Republic", minute: 59, type: "goal" },
      { player: "Hwang In-beom", team: "South Korea", minute: 67, type: "goal" },
      { player: "Oh Hyeon-gyu", team: "South Korea", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "Gi-Hyuk Lee", team: "South Korea", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    goals: [
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 21, type: "goal" },
      { player: "Cyle Larin", team: "Canada", minute: 78, type: "goal" },
    ],
    yellowCards: [
      { player: "Alistair Johnston", team: "Canada", minute: 11, reason: "Foul" },
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 45, reason: "Foul" },
      { player: "Ermedin Demirović", team: "Bosnia & Herzegovina", minute: 45, reason: "Foul" },
      { player: "Luc de Fougerolles", team: "Canada", minute: 53, reason: "Foul" },
      { player: "Nikola Katić", team: "Bosnia & Herzegovina", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    goals: [
      { player: "Damián Bobadilla", team: "Paraguay", minute: 7, type: "own-goal" },
      { player: "Folarin Balogun", team: "USA", minute: 31, type: "goal" },
      { player: "Folarin Balogun", team: "USA", minute: 45, type: "goal" },
      { player: "Maurício", team: "Paraguay", minute: 73, type: "goal" },
      { player: "Giovanni Reyna", team: "USA", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Juan José Cáceres", team: "Paraguay", minute: 10, reason: "Foul" },
      { player: "Miguel Almirón", team: "Paraguay", minute: 53, reason: "Simulation" },
      { player: "Tyler Adams", team: "USA", minute: 59, reason: "Foul" },
      { player: "Diego Gómez", team: "Paraguay", minute: 79, reason: "Foul" },
      { player: "Álex Arce", team: "Paraguay", minute: 88, reason: "Foul" },
      { player: "Júnior Alonso", team: "Paraguay", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    goals: [
      { player: "Breel Embolo", team: "Switzerland", minute: 17, type: "penalty" },
      { player: "Miro Muheim", team: "Switzerland", minute: 90, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Mahmud Abunada", team: "Qatar", minute: 16, reason: "Time wasting" },
      { player: "Jassem Gaber Abdulsallam", team: "Qatar", minute: 23, reason: "Foul" },
      { player: "Denis Zakaria", team: "Switzerland", minute: 42, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    goals: [
      { player: "Ismael Saibari", team: "Morocco", minute: 21, type: "goal" },
      { player: "Vinícius Júnior", team: "Brazil", minute: 32, type: "goal" },
    ],
    yellowCards: [
      { player: "Casemiro", team: "Brazil", minute: 37, reason: "Foul" },
      { player: "Roger Ibañez", team: "Brazil", minute: 43, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D1_Haiti_v_Scotland",
    home: "Haiti", away: "Scotland", date: "2026-06-14",
    goals: [
      { player: "John McGinn", team: "Scotland", minute: 28, type: "goal" },
    ],
    yellowCards: [
      { player: "Jean-Ricner Bellegarde", team: "Haiti", minute: 39, reason: "Foul" },
      { player: "Aaron Hickey", team: "Scotland", minute: 46, reason: "Foul" },
      { player: "Kenny McLean", team: "Scotland", minute: 90, reason: "Foul" },
      { player: "Findlay Curtis", team: "Scotland", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C1_Australia_v_T_rkiye",
    home: "Australia", away: "Türkiye", date: "2026-06-14",
    goals: [
      { player: "Nestory Irankunda", team: "Australia", minute: 27, type: "goal" },
      { player: "Connor Metcalfe", team: "Australia", minute: 75, type: "goal" },
    ],
    yellowCards: [
      { player: "Yunus Akgün", team: "Türkiye", minute: 86, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E1_Germany_v_Cura_ao",
    home: "Germany", away: "Curaçao", date: "2026-06-14",
    goals: [
      { player: "Felix Nmecha", team: "Germany", minute: 6, type: "goal" },
      { player: "Livano Comenencia", team: "Curaçao", minute: 21, type: "goal" },
      { player: "Nico Schlotterbeck", team: "Germany", minute: 38, type: "goal" },
      { player: "Kai Havertz", team: "Germany", minute: 45, type: "penalty" },
      { player: "Jamal Musiala", team: "Germany", minute: 47, type: "goal" },
      { player: "Nathaniel Brown", team: "Germany", minute: 68, type: "goal" },
      { player: "Deniz Undav", team: "Germany", minute: 78, type: "goal" },
      { player: "Kai Havertz", team: "Germany", minute: 88, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "F1_Netherlands_v_Japan",
    home: "Netherlands", away: "Japan", date: "2026-06-14",
    goals: [
      { player: "Virgil van Dijk", team: "Netherlands", minute: 51, type: "goal" },
      { player: "Keito Nakamura", team: "Japan", minute: 57, type: "goal" },
      { player: "Crysencio Summerville", team: "Netherlands", minute: 64, type: "goal" },
      { player: "Daichi Kamada", team: "Japan", minute: 89, type: "goal" },
    ],
    yellowCards: [
      { player: "Crysencio Summerville", team: "Netherlands", minute: 61, reason: "Foul" },
      { player: "Memphis Depay", team: "Netherlands", minute: 83, reason: "Foul" },
      { player: "Micky van de Ven", team: "Netherlands", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E1_Ivory_Coast_v_Ecuador",
    home: "Ivory Coast", away: "Ecuador", date: "2026-06-14",
    goals: [
      { player: "Amad Diallo", team: "Ivory Coast", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Seko Fofana", team: "Ivory Coast", minute: 28, reason: "Foul" },
      { player: "Franck Kessié", team: "Ivory Coast", minute: 38, reason: "Foul" },
      { player: "Guéla Doué", team: "Ivory Coast", minute: 40, reason: "Foul" },
      { player: "Jackson Porozo", team: "Ecuador", minute: 73, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "F1_Sweden_v_Tunisia",
    home: "Sweden", away: "Tunisia", date: "2026-06-15",
    goals: [
      { player: "Yasin Ayari", team: "Sweden", minute: 7, type: "goal" },
      { player: "Alexander Isak", team: "Sweden", minute: 30, type: "goal" },
      { player: "Omar Rekik", team: "Tunisia", minute: 43, type: "goal" },
      { player: "Viktor Gyökeres", team: "Sweden", minute: 59, type: "goal" },
      { player: "Mattias Svanberg", team: "Sweden", minute: 84, type: "goal" },
      { player: "Yasin Ayari", team: "Sweden", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Rani Khedira", team: "Tunisia", minute: 54, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "G1_Spain_v_Cape_Verde_Islands",
    home: "Spain", away: "Cape Verde Islands", date: "2026-06-15",
    goals: [],
    yellowCards: [
      { player: "Sidny Lopes Cabral", team: "Cape Verde Islands", minute: 16, reason: "Foul" },
      { player: "Pedri", team: "Spain", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "H1_Belgium_v_Egypt",
    home: "Belgium", away: "Egypt", date: "2026-06-15",
    goals: [
      { player: "Emam Ashour", team: "Egypt", minute: 20, type: "goal" },
      { player: "Mohamed Hany", team: "Egypt", minute: 66, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Marwan Attia", team: "Egypt", minute: 13, reason: "Foul" },
      { player: "Timothy Castagne", team: "Belgium", minute: 14, reason: "Foul" },
      { player: "Ahmed Fatouh", team: "Egypt", minute: 34, reason: "Foul" },
      { player: "Maxim De Cuyper", team: "Belgium", minute: 75, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "G1_Saudi_Arabia_v_Uruguay",
    home: "Saudi Arabia", away: "Uruguay", date: "2026-06-15",
    goals: [
      { player: "A. Al Amri", team: "Saudi Arabia", minute: 41, type: "goal" },
      { player: "Maximiliano Araújo", team: "Uruguay", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "Abdulelah Al-Amri", team: "Saudi Arabia", minute: 44, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "H1_Iran_v_New_Zealand",
    home: "Iran", away: "New Zealand", date: "2026-06-16",
    goals: [
      { player: "Elijah Just", team: "New Zealand", minute: 7, type: "goal" },
      { player: "Ramin Rezaeian", team: "Iran", minute: 32, type: "goal" },
      { player: "Elijah Just", team: "New Zealand", minute: 54, type: "goal" },
      { player: "Mohammad Mohebi", team: "Iran", minute: 64, type: "goal" },
    ],
    yellowCards: [
      { player: "Ehsan Hajsafi", team: "Iran", minute: 89, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "I1_France_v_Senegal",
    home: "France", away: "Senegal", date: "2026-06-16",
    goals: [
      { player: "Kylian Mbappé", team: "France", minute: 66, type: "goal" },
      { player: "Bradley Barcola", team: "France", minute: 82, type: "goal" },
      { player: "Ibrahim Mbaye", team: "Senegal", minute: 90, type: "goal" },
      { player: "Kylian Mbappé", team: "France", minute: 90, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "I1_Iraq_v_Norway",
    home: "Iraq", away: "Norway", date: "2026-06-16",
    goals: [
      { player: "Erling Haaland", team: "Norway", minute: 29, type: "goal" },
      { player: "Aymen Hussein", team: "Iraq", minute: 39, type: "goal" },
      { player: "Erling Haaland", team: "Norway", minute: 43, type: "goal" },
      { player: "L. Ostigard", team: "Norway", minute: 76, type: "goal" },
      { player: "Aymen Hussein", team: "Iraq", minute: 90, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Zaid Tahseen", team: "Iraq", minute: 86, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "J1_Argentina_v_Algeria",
    home: "Argentina", away: "Algeria", date: "2026-06-17",
    goals: [
      { player: "Lionel Messi", team: "Argentina", minute: 17, type: "goal" },
      { player: "Lionel Messi", team: "Argentina", minute: 60, type: "goal" },
      { player: "Lionel Messi", team: "Argentina", minute: 76, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "J1_Austria_v_Jordan",
    home: "Austria", away: "Jordan", date: "2026-06-17",
    goals: [
      { player: "Romano Schmid", team: "Austria", minute: 21, type: "goal" },
      { player: "Ali Olwan", team: "Jordan", minute: 50, type: "goal" },
      { player: "Y. Al Arab", team: "Jordan", minute: 76, type: "own-goal" },
      { player: "Marko Arnautović", team: "Austria", minute: 90, type: "penalty" },
    ],
    yellowCards: [
      { player: "Marcel Sabitzer", team: "Austria", minute: 77, reason: "Argument" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K1_Portugal_v_Congo_DR",
    home: "Portugal", away: "Congo DR", date: "2026-06-17",
    goals: [
      { player: "João Neves", team: "Portugal", minute: 6, type: "goal" },
      { player: "Yoane Wissa", team: "Congo DR", minute: 45, type: "goal" },
    ],
    yellowCards: [
      { player: "Bernardo Silva", team: "Portugal", minute: 13, reason: "Foul" },
      { player: "Chancel Mbemba", team: "Congo DR", minute: 32, reason: "Foul" },
      { player: "Nélson Semedo", team: "Portugal", minute: 88, reason: "Foul" },
      { player: "Tomás Araújo", team: "Portugal", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "L1_England_v_Croatia",
    home: "England", away: "Croatia", date: "2026-06-17",
    goals: [
      { player: "Harry Kane", team: "England", minute: 12, type: "penalty" },
      { player: "Martin Baturina", team: "Croatia", minute: 36, type: "goal" },
      { player: "Harry Kane", team: "England", minute: 42, type: "goal" },
      { player: "Petar Musa", team: "Croatia", minute: 45, type: "goal" },
      { player: "Jude Bellingham", team: "England", minute: 47, type: "goal" },
      { player: "Marcus Rashford", team: "England", minute: 85, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "L1_Ghana_v_Panama",
    home: "Ghana", away: "Panama", date: "2026-06-17",
    goals: [
      { player: "Caleb Yirenkyi", team: "Ghana", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Caleb Yirenkyi", team: "Ghana", minute: 16, reason: "Foul" },
      { player: "César Blackman", team: "Panama", minute: 72, reason: "Foul" },
      { player: "Carlos Harvey", team: "Panama", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K1_Uzbekistan_v_Colombia",
    home: "Uzbekistan", away: "Colombia", date: "2026-06-18",
    goals: [
      { player: "Daniel Muñoz", team: "Colombia", minute: 40, type: "goal" },
      { player: "Abbosbek Fayzullaev", team: "Uzbekistan", minute: 60, type: "goal" },
      { player: "Luis Díaz", team: "Colombia", minute: 65, type: "goal" },
      { player: "Jaminton Campaz", team: "Colombia", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Johan Mojica", team: "Colombia", minute: 7, reason: "Foul" },
      { player: "Abdukodir Khusanov", team: "Uzbekistan", minute: 34, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "A2_Czech_Republic_v_South_Africa",
    home: "Czech Republic", away: "South Africa", date: "2026-06-18",
    goals: [
      { player: "Michal Sadílek", team: "Czech Republic", minute: 6, type: "goal" },
      { player: "Teboho Mokoena", team: "South Africa", minute: 83, type: "penalty" },
    ],
    yellowCards: [
      { player: "Teboho Mokoena", team: "South Africa", minute: 33, reason: "Foul" },
      { player: "Thalente Mbatha", team: "South Africa", minute: 40, reason: "Foul" },
      { player: "Ladislav Krejčí", team: "Czech Republic", minute: 75, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B2_Switzerland_v_Bosnia_Herzegovina",
    home: "Switzerland", away: "Bosnia & Herzegovina", date: "2026-06-18",
    goals: [
      { player: "Johan Manzambi", team: "Switzerland", minute: 74, type: "goal" },
      { player: "Rubén Vargas", team: "Switzerland", minute: 84, type: "goal" },
      { player: "Johan Manzambi", team: "Switzerland", minute: 90, type: "goal" },
      { player: "Ermin Mahmić", team: "Bosnia & Herzegovina", minute: 90, type: "goal" },
      { player: "Granit Xhaka", team: "Switzerland", minute: 90, type: "penalty" },
    ],
    yellowCards: [
      { player: "Amar Dedić", team: "Bosnia & Herzegovina", minute: 59, reason: "Foul" },
      { player: "Edin Džeko", team: "Bosnia & Herzegovina", minute: 61, reason: "Foul" },
      { player: "Nico Elvedi", team: "Switzerland", minute: 65, reason: "Foul" },
    ],
    redCards: [
      { player: "Tarik Muharemović", team: "Bosnia & Herzegovina", minute: 80, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "B2_Canada_v_Qatar",
    home: "Canada", away: "Qatar", date: "2026-06-18",
    goals: [
      { player: "Cyle Larin", team: "Canada", minute: 16, type: "goal" },
      { player: "Jonathan David", team: "Canada", minute: 29, type: "goal" },
      { player: "Jonathan David", team: "Canada", minute: 45, type: "goal" },
      { player: "Nathan Saliba", team: "Canada", minute: 64, type: "goal" },
      { player: "M. Al Mannai", team: "Qatar", minute: 75, type: "own-goal" },
      { player: "Jonathan David", team: "Canada", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Derek Cornelius", team: "Canada", minute: 9, reason: "Foul" },
      { player: "Ahmed Fathi", team: "Qatar", minute: 62, reason: "Foul" },
    ],
    redCards: [
      { player: "Homam Al-Amin", team: "Qatar", minute: 33, reason: "Professional foul last man" },
      { player: "Assim Madibo", team: "Qatar", minute: 53, reason: "Foul" },
    ],
  },
  {
    fixtureId: "A2_Mexico_v_South_Korea",
    home: "Mexico", away: "South Korea", date: "2026-06-19",
    goals: [
      { player: "Luis Romo", team: "Mexico", minute: 50, type: "goal" },
    ],
    yellowCards: [
      { player: "Kang-in Lee", team: "South Korea", minute: 4, reason: "Foul" },
      { player: "Seung Ho Paik", team: "South Korea", minute: 58, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C2_USA_v_Australia",
    home: "USA", away: "Australia", date: "2026-06-19",
    goals: [
      { player: "Cameron Burgess", team: "Australia", minute: 11, type: "own-goal" },
      { player: "Alex Freeman", team: "USA", minute: 43, type: "goal" },
    ],
    yellowCards: [
      { player: "Jordan Bos", team: "Australia", minute: 16, reason: "Foul" },
      { player: "Alessandro Circati", team: "Australia", minute: 32, reason: "Foul" },
      { player: "Antonee Robinson", team: "USA", minute: 56, reason: "Foul" },
      { player: "Harry Souttar", team: "Australia", minute: 88, reason: "Argument" },
      { player: "Folarin Balogun", team: "USA", minute: 89, reason: "Argument" },
      { player: "Jacob Italiano", team: "Australia", minute: 89, reason: "Argument" },
      { player: "Chris Richards", team: "USA", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D2_Scotland_v_Morocco",
    home: "Scotland", away: "Morocco", date: "2026-06-19",
    goals: [
      { player: "Ismael Saibari", team: "Morocco", minute: 2, type: "goal" },
    ],
    yellowCards: [
      { player: "Issa Diop", team: "Morocco", minute: 23, reason: "Foul" },
      { player: "Andy Robertson", team: "Scotland", minute: 65, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D2_Brazil_v_Haiti",
    home: "Brazil", away: "Haiti", date: "2026-06-20",
    goals: [
      { player: "Matheus Cunha", team: "Brazil", minute: 23, type: "goal" },
      { player: "Matheus Cunha", team: "Brazil", minute: 36, type: "goal" },
      { player: "Vinícius Júnior", team: "Brazil", minute: 45, type: "goal" },
    ],
    yellowCards: [
      { player: "Carlens Arcus", team: "Haiti", minute: 4, reason: "Foul" },
      { player: "Frantzdy Pierrot", team: "Haiti", minute: 45, reason: "Foul" },
      { player: "Douglas Santos", team: "Brazil", minute: 65, reason: "Foul" },
      { player: "Danley Jean Jacques", team: "Haiti", minute: 72, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C2_T_rkiye_v_Paraguay",
    home: "Türkiye", away: "Paraguay", date: "2026-06-19",
    goals: [
      { player: "Matías Galarza", team: "Paraguay", minute: 2, type: "goal" },
    ],
    yellowCards: [
      { player: "Matías Galarza", team: "Paraguay", minute: 4, reason: "Foul" },
      { player: "Eren Elmalı", team: "Türkiye", minute: 71, reason: "Foul" },
    ],
    redCards: [
      { player: "Miguel Almirón", team: "Paraguay", minute: 45, reason: "Argument" },
    ],
  },
  {
    fixtureId: "F2_Netherlands_v_Sweden",
    home: "Netherlands", away: "Sweden", date: "2026-06-20",
    goals: [
      { player: "Brian Brobbey", team: "Netherlands", minute: 5, type: "goal" },
      { player: "Brian Brobbey", team: "Netherlands", minute: 17, type: "goal" },
      { player: "Cody Gakpo", team: "Netherlands", minute: 47, type: "goal" },
      { player: "Cody Gakpo", team: "Netherlands", minute: 54, type: "goal" },
      { player: "Anthony Elanga", team: "Sweden", minute: 59, type: "goal" },
      { player: "Crysencio Summerville", team: "Netherlands", minute: 89, type: "goal" },
    ],
    yellowCards: [
      { player: "Gabriel Gudmundsson", team: "Sweden", minute: 53, reason: "Foul" },
      { player: "Yasin Ayari", team: "Sweden", minute: 75, reason: "Foul" },
      { player: "Lucas Bergvall", team: "Sweden", minute: 80, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E2_Germany_v_Ivory_Coast",
    home: "Germany", away: "Ivory Coast", date: "2026-06-20",
    goals: [
      { player: "Franck Kessié", team: "Ivory Coast", minute: 30, type: "goal" },
      { player: "Deniz Undav", team: "Germany", minute: 68, type: "goal" },
      { player: "Deniz Undav", team: "Germany", minute: 90, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "E2_Ecuador_v_Cura_ao",
    home: "Ecuador", away: "Curaçao", date: "2026-06-21",
    goals: [],
    yellowCards: [
      { player: "Jordy Alcívar", team: "Ecuador", minute: 38, reason: "Foul" },
      { player: "Leandro Bacuna", team: "Curaçao", minute: 39, reason: "Foul" },
      { player: "Juninho Bacuna", team: "Curaçao", minute: 53, reason: "Foul" },
      { player: "Livano Comenencia", team: "Curaçao", minute: 56, reason: "Foul" },
      { player: "Juriën Gaari", team: "Curaçao", minute: 75, reason: "Foul" },
      { player: "Gervane Kastaneer", team: "Curaçao", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "F2_Tunisia_v_Japan",
    home: "Tunisia", away: "Japan", date: "2026-06-21",
    goals: [
      { player: "Daichi Kamada", team: "Japan", minute: 4, type: "goal" },
      { player: "Ayase Ueda", team: "Japan", minute: 31, type: "goal" },
      { player: "Junya Itō", team: "Japan", minute: 69, type: "goal" },
      { player: "Ayase Ueda", team: "Japan", minute: 83, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "G2_Spain_v_Saudi_Arabia",
    home: "Spain", away: "Saudi Arabia", date: "2026-06-21",
    goals: [
      { player: "Lamine Yamal", team: "Spain", minute: 10, type: "goal" },
      { player: "Mikel Oyarzabal", team: "Spain", minute: 21, type: "goal" },
      { player: "Mikel Oyarzabal", team: "Spain", minute: 24, type: "goal" },
      { player: "H. Tambakti", team: "Saudi Arabia", minute: 49, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Salem Al-Dawsari", team: "Saudi Arabia", minute: 30, reason: "Foul" },
      { player: "Mohamed Kanno", team: "Saudi Arabia", minute: 60, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "H2_Belgium_v_Iran",
    home: "Belgium", away: "Iran", date: "2026-06-21",
    goals: [],
    yellowCards: [
      { player: "Romelu Lukaku", team: "Belgium", minute: 3, reason: "Foul" },
      { player: "Saeid Ezatolahi", team: "Iran", minute: 33, reason: "Foul" },
    ],
    redCards: [
      { player: "Nathan Ngoy", team: "Belgium", minute: 66, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "G2_Uruguay_v_Cape_Verde_Islands",
    home: "Uruguay", away: "Cape Verde Islands", date: "2026-06-21",
    goals: [
      { player: "K. Lenini", team: "Cape Verde Islands", minute: 21, type: "goal" },
      { player: "Maximiliano Araújo", team: "Uruguay", minute: 44, type: "goal" },
      { player: "Agustín Canobbio", team: "Uruguay", minute: 45, type: "goal" },
      { player: "Hélio Varela", team: "Cape Verde Islands", minute: 61, type: "goal" },
    ],
    yellowCards: [
      { player: "Sidny Lopes Cabral", team: "Cape Verde Islands", minute: 5, reason: "Foul" },
      { player: "Rodrigo Bentancur", team: "Uruguay", minute: 20, reason: "Foul" },
      { player: "Mathías Olivera", team: "Uruguay", minute: 58, reason: "Foul" },
      { player: "Diney Borges", team: "Cape Verde Islands", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "H2_New_Zealand_v_Egypt",
    home: "New Zealand", away: "Egypt", date: "2026-06-22",
    goals: [
      { player: "Finn Surman", team: "New Zealand", minute: 15, type: "goal" },
      { player: "Mostafa Ziko", team: "Egypt", minute: 58, type: "goal" },
      { player: "Mohamed Salah", team: "Egypt", minute: 67, type: "goal" },
      { player: "Trézéguet", team: "Egypt", minute: 82, type: "goal" },
    ],
    yellowCards: [
      { player: "Mohanad Lasheen", team: "Egypt", minute: 17, reason: "Foul" },
      { player: "Sarpreet Singh", team: "New Zealand", minute: 20, reason: "Foul" },
      { player: "Callum McCowatt", team: "New Zealand", minute: 34, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "J2_Argentina_v_Austria",
    home: "Argentina", away: "Austria", date: "2026-06-22",
    goals: [
      { player: "Lionel Messi", team: "Argentina", minute: 38, type: "goal" },
      { player: "Lionel Messi", team: "Argentina", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Stefan Posch", team: "Austria", minute: 40, reason: "Argument" },
      { player: "Facundo Medina", team: "Argentina", minute: 76, reason: "Argument" },
      { player: "Konrad Laimer", team: "Austria", minute: 76, reason: "Argument" },
      { player: "Leandro Paredes", team: "Argentina", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "I2_France_v_Iraq",
    home: "France", away: "Iraq", date: "2026-06-22",
    goals: [
      { player: "Kylian Mbappé", team: "France", minute: 14, type: "goal" },
      { player: "Kylian Mbappé", team: "France", minute: 54, type: "goal" },
      { player: "Ousmane Dembélé", team: "France", minute: 66, type: "goal" },
    ],
    yellowCards: [
      { player: "Amir Al-Ammari", team: "Iraq", minute: 6, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "I2_Norway_v_Senegal",
    home: "Norway", away: "Senegal", date: "2026-06-23",
    goals: [
      { player: "Marcus Holmgren Pedersen", team: "Norway", minute: 43, type: "goal" },
      { player: "Erling Haaland", team: "Norway", minute: 48, type: "goal" },
      { player: "Ismaïla Sarr", team: "Senegal", minute: 53, type: "goal" },
      { player: "Erling Haaland", team: "Norway", minute: 58, type: "goal" },
      { player: "Ismaïla Sarr", team: "Senegal", minute: 90, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "J2_Jordan_v_Algeria",
    home: "Jordan", away: "Algeria", date: "2026-06-23",
    goals: [
      { player: "N. Al Rashdan", team: "Jordan", minute: 36, type: "goal" },
      { player: "Nadhir Benbouali", team: "Algeria", minute: 69, type: "goal" },
      { player: "Amine Gouiri", team: "Algeria", minute: 82, type: "goal" },
    ],
    yellowCards: [
      { player: "Ramiz Zerrouki", team: "Algeria", minute: 44, reason: "Foul" },
      { player: "Husam Ali Mohammad Abudahab", team: "Jordan", minute: 64, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K2_Portugal_v_Uzbekistan",
    home: "Portugal", away: "Uzbekistan", date: "2026-06-23",
    goals: [
      { player: "Cristiano Ronaldo", team: "Portugal", minute: 6, type: "goal" },
      { player: "Nuno Mendes", team: "Portugal", minute: 17, type: "goal" },
      { player: "Cristiano Ronaldo", team: "Portugal", minute: 39, type: "goal" },
      { player: "Abduvohid Nematov", team: "Uzbekistan", minute: 60, type: "own-goal" },
      { player: "Rafael Leão", team: "Portugal", minute: 87, type: "goal" },
    ],
    yellowCards: [
      { player: "Odiljon Khamrobekov", team: "Uzbekistan", minute: 14, reason: "Foul" },
      { player: "Renato Veiga", team: "Portugal", minute: 68, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "L2_England_v_Ghana",
    home: "England", away: "Ghana", date: "2026-06-23",
    goals: [],
    yellowCards: [
      { player: "Declan Rice", team: "England", minute: 41, reason: "Foul" },
      { player: "Iñaki Williams", team: "Ghana", minute: 60, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "L2_Panama_v_Croatia",
    home: "Panama", away: "Croatia", date: "2026-06-23",
    goals: [
      { player: "Ante Budimir", team: "Croatia", minute: 54, type: "goal" },
    ],
    yellowCards: [
      { player: "Yoel Bárcenas", team: "Panama", minute: 61, reason: "Foul" },
      { player: "Petar Sučić", team: "Croatia", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K2_Colombia_v_Congo_DR",
    home: "Colombia", away: "Congo DR", date: "2026-06-24",
    goals: [
      { player: "Daniel Muñoz", team: "Colombia", minute: 76, type: "goal" },
    ],
    yellowCards: [
      { player: "Jhon Lucumí", team: "Colombia", minute: 56, reason: "Foul" },
      { player: "Jefferson Lerma", team: "Colombia", minute: 90, reason: "Foul" },
      { player: "Charles Pickel", team: "Congo DR", minute: 90, reason: "Argument" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B3_Switzerland_v_Canada",
    home: "Switzerland", away: "Canada", date: "2026-06-24",
    goals: [
      { player: "Rubén Vargas", team: "Switzerland", minute: 46, type: "goal" },
      { player: "Johan Manzambi", team: "Switzerland", minute: 57, type: "goal" },
      { player: "Promise David", team: "Canada", minute: 76, type: "goal" },
    ],
    yellowCards: [
      { player: "Granit Xhaka", team: "Switzerland", minute: 32, reason: "Argument" },
      { player: "Cyle Larin", team: "Canada", minute: 32 },
      { player: "Liam Millar", team: "Canada", minute: 87, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B3_Bosnia_Herzegovina_v_Qatar",
    home: "Bosnia & Herzegovina", away: "Qatar", date: "2026-06-24",
    goals: [
      { player: "Kerim Alajbegović", team: "Bosnia & Herzegovina", minute: 29, type: "goal" },
      { player: "Mahmud Abunada", team: "Qatar", minute: 34, type: "own-goal" },
      { player: "H. Al Haydos", team: "Qatar", minute: 42, type: "goal" },
      { player: "Ermin Mahmić", team: "Bosnia & Herzegovina", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "Ahmed Fathi", team: "Qatar", minute: 78, reason: "Foul" },
      { player: "Ermin Mahmić", team: "Bosnia & Herzegovina", minute: 82 },
    ],
    redCards: [],
  },
  {
    fixtureId: "D3_Morocco_v_Haiti",
    home: "Morocco", away: "Haiti", date: "2026-06-24",
    goals: [
      { player: "Bono", team: "Morocco", minute: 10, type: "own-goal" },
      { player: "Achraf Hakimi", team: "Morocco", minute: 39, type: "goal" },
      { player: "Wilson Isidor", team: "Haiti", minute: 43, type: "goal" },
      { player: "Ismael Saibari", team: "Morocco", minute: 45, type: "goal" },
      { player: "Soufiane Rahimi", team: "Morocco", minute: 78, type: "goal" },
      { player: "Gessime Yassine", team: "Morocco", minute: 89, type: "goal" },
    ],
    yellowCards: [
      { player: "Johny Placide", team: "Haiti", minute: 79, reason: "Argument" },
      { player: "Duckens Nazon", team: "Haiti", minute: 80, reason: "Argument" },
      { player: "Josué Casimir", team: "Haiti", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D3_Scotland_v_Brazil",
    home: "Scotland", away: "Brazil", date: "2026-06-24",
    goals: [
      { player: "Vinícius Júnior", team: "Brazil", minute: 7, type: "goal" },
      { player: "Vinícius Júnior", team: "Brazil", minute: 45, type: "goal" },
      { player: "Matheus Cunha", team: "Brazil", minute: 60, type: "goal" },
    ],
    yellowCards: [
      { player: "Danilo", team: "Brazil", minute: 62, reason: "Foul" },
      { player: "Fabinho", team: "Brazil", minute: 82, reason: "Foul" },
      { player: "Ryan Christie", team: "Scotland", minute: 89, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "A3_Czech_Republic_v_Mexico",
    home: "Czech Republic", away: "Mexico", date: "2026-06-25",
    goals: [
      { player: "M. Chavez Garcia", team: "Mexico", minute: 55, type: "goal" },
      { player: "Julián Quiñones", team: "Mexico", minute: 61, type: "goal" },
      { player: "Álvaro Fidalgo", team: "Mexico", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Edson Álvarez", team: "Mexico", minute: 64, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "A3_South_Africa_v_South_Korea",
    home: "South Africa", away: "South Korea", date: "2026-06-25",
    goals: [
      { player: "Thapelo Maseko", team: "South Africa", minute: 63, type: "goal" },
    ],
    yellowCards: [
      { player: "Aubrey Modiba", team: "South Africa", minute: 73, reason: "Foul" },
      { player: "Gue-sung Cho", team: "South Korea", minute: 79, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E3_Ecuador_v_Germany",
    home: "Ecuador", away: "Germany", date: "2026-06-25",
    goals: [
      { player: "Leroy Sané", team: "Germany", minute: 2, type: "goal" },
      { player: "Nilson Angulo", team: "Ecuador", minute: 9, type: "goal" },
      { player: "Gonzalo Plata", team: "Ecuador", minute: 77, type: "goal" },
    ],
    yellowCards: [
      { player: "Piero Hincapié", team: "Ecuador", minute: 43, reason: "Foul" },
      { player: "Aleksandar Pavlović", team: "Germany", minute: 44, reason: "Foul" },
      { player: "Alan Franco", team: "Ecuador", minute: 50, reason: "Time wasting" },
      { player: "Gonzalo Plata", team: "Ecuador", minute: 89, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E3_Cura_ao_v_Ivory_Coast",
    home: "Curaçao", away: "Ivory Coast", date: "2026-06-25",
    goals: [
      { player: "Nicolas Pépé", team: "Ivory Coast", minute: 7, type: "goal" },
      { player: "Nicolas Pépé", team: "Ivory Coast", minute: 64, type: "goal" },
    ],
    yellowCards: [
      { player: "Nicolas Pépé", team: "Ivory Coast", minute: 35, reason: "Foul" },
      { player: "Juninho Bacuna", team: "Curaçao", minute: 75, reason: "Foul" },
      { player: "Gervane Kastaneer", team: "Curaçao", minute: 83, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "F3_Japan_v_Sweden",
    home: "Japan", away: "Sweden", date: "2026-06-25",
    goals: [
      { player: "Daizen Maeda", team: "Japan", minute: 56, type: "goal" },
      { player: "Anthony Elanga", team: "Sweden", minute: 62, type: "goal" },
    ],
    yellowCards: [
      { player: "Isak Hien", team: "Sweden", minute: 32, reason: "Foul" },
      { player: "Shōgo Taniguchi", team: "Japan", minute: 77, reason: "Foul" },
      { player: "Viktor Gyökeres", team: "Sweden", minute: 85, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "F3_Tunisia_v_Netherlands",
    home: "Tunisia", away: "Netherlands", date: "2026-06-25",
    goals: [
      { player: "Ellyes Skhiri", team: "Tunisia", minute: 3, type: "own-goal" },
      { player: "Brian Brobbey", team: "Netherlands", minute: 7, type: "goal" },
      { player: "Hazem Mastouri", team: "Tunisia", minute: 54, type: "goal" },
      { player: "Jan Paul van Hecke", team: "Netherlands", minute: 62, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "C3_T_rkiye_v_USA",
    home: "Türkiye", away: "USA", date: "2026-06-26",
    goals: [
      { player: "Auston Trusty", team: "USA", minute: 3, type: "goal" },
      { player: "Arda Güler", team: "Türkiye", minute: 10, type: "goal" },
      { player: "B. Yilmaz", team: "Türkiye", minute: 31, type: "goal" },
      { player: "Sebastian Berhalter", team: "USA", minute: 49, type: "goal" },
      { player: "Kaan Ayhan", team: "Türkiye", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Sebastian Berhalter", team: "USA", minute: 19, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C3_Paraguay_v_Australia",
    home: "Paraguay", away: "Australia", date: "2026-06-25",
    goals: [],
    yellowCards: [
      { player: "Jackson Irvine", team: "Australia", minute: 46, reason: "Foul" },
      { player: "Diego Gómez", team: "Paraguay", minute: 77, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "I3_Senegal_v_Iraq",
    home: "Senegal", away: "Iraq", date: "2026-06-26",
    goals: [
      { player: "Habib Diarra", team: "Senegal", minute: 4, type: "goal" },
      { player: "Ismaïla Sarr", team: "Senegal", minute: 56, type: "goal" },
      { player: "Pape Gueye", team: "Senegal", minute: 59, type: "goal" },
      { player: "Pape Gueye", team: "Senegal", minute: 71, type: "goal" },
      { player: "Iliman Ndiaye", team: "Senegal", minute: 82, type: "goal" },
    ],
    yellowCards: [
      { player: "Abdoulaye Seck", team: "Senegal", minute: 18, reason: "Foul" },
      { player: "Amir Al-Ammari", team: "Iraq", minute: 75, reason: "Foul" },
      { player: "Pape Gueye", team: "Senegal", minute: 81, reason: "Foul" },
      { player: "Merchas Doski", team: "Iraq", minute: 90, reason: "Foul" },
    ],
    redCards: [
      { player: "Rebin Sulaka", team: "Iraq", minute: 13, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "I3_Norway_v_France",
    home: "Norway", away: "France", date: "2026-06-26",
    goals: [
      { player: "Ousmane Dembélé", team: "France", minute: 7, type: "goal" },
      { player: "Ousmane Dembélé", team: "France", minute: 20, type: "goal" },
      { player: "Thelo Aasgaard", team: "Norway", minute: 21, type: "goal" },
      { player: "Ousmane Dembélé", team: "France", minute: 32, type: "goal" },
      { player: "Désiré Doué", team: "France", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Patrick Berg", team: "Norway", minute: 10, reason: "Foul" },
      { player: "Aurélien Tchouaméni", team: "France", minute: 74, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "G3_Uruguay_v_Spain",
    home: "Uruguay", away: "Spain", date: "2026-06-27",
    goals: [
      { player: "Álex Baena", team: "Spain", minute: 42, type: "goal" },
    ],
    yellowCards: [
      { player: "Álex Baena", team: "Spain", minute: 46, reason: "Foul" },
      { player: "Juan Manuel Sanabria", team: "Uruguay", minute: 54, reason: "Foul" },
      { player: "Guillermo Varela", team: "Uruguay", minute: 58, reason: "Off the ball foul" },
      { player: "Nicolás de la Cruz", team: "Uruguay", minute: 90, reason: "Foul" },
    ],
    redCards: [
      { player: "Agustín Canobbio", team: "Uruguay", minute: 90, reason: "Foul" },
    ],
  },
  {
    fixtureId: "G3_Cape_Verde_Islands_v_Saudi_Arabia",
    home: "Cape Verde Islands", away: "Saudi Arabia", date: "2026-06-27",
    goals: [],
    yellowCards: [
      { player: "Saud Abdulhamid", team: "Saudi Arabia", minute: 4, reason: "Foul" },
      { player: "Wagner Pina", team: "Cape Verde Islands", minute: 8, reason: "Foul" },
      { player: "Nasser Al-Dawsari", team: "Saudi Arabia", minute: 67, reason: "Foul" },
      { player: "Firas Al-Buraikan", team: "Saudi Arabia", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "H3_Egypt_v_Iran",
    home: "Egypt", away: "Iran", date: "2026-06-27",
    goals: [
      { player: "Mahmoud Saber", team: "Egypt", minute: 5, type: "goal" },
      { player: "Ramin Rezaeian", team: "Iran", minute: 14, type: "goal" },
    ],
    yellowCards: [
      { player: "Hossein Kanaani", team: "Iran", minute: 19, reason: "Foul" },
      { player: "Mahmoud Saber", team: "Egypt", minute: 20, reason: "Foul" },
      { player: "Yasser Ibrahim", team: "Egypt", minute: 42, reason: "Foul" },
      { player: "Ali Nemati", team: "Iran", minute: 43, reason: "Foul" },
      { player: "Saeid Ezatolahi", team: "Iran", minute: 79, reason: "Foul" },
      { player: "Mohanad Lasheen", team: "Egypt", minute: 90, reason: "Foul" },
      { player: "Shojae Khalilzadeh", team: "Iran", minute: 90 },
    ],
    redCards: [],
  },
  {
    fixtureId: "H3_New_Zealand_v_Belgium",
    home: "New Zealand", away: "Belgium", date: "2026-06-27",
    goals: [
      { player: "Leandro Trossard", team: "Belgium", minute: 28, type: "goal" },
      { player: "Leandro Trossard", team: "Belgium", minute: 50, type: "goal" },
      { player: "Kevin De Bruyne", team: "Belgium", minute: 66, type: "goal" },
      { player: "Elijah Just", team: "New Zealand", minute: 84, type: "goal" },
      { player: "Romelu Lukaku", team: "Belgium", minute: 86, type: "goal" },
      { player: "Alexis Saelemaekers", team: "Belgium", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Marko Stamenić", team: "New Zealand", minute: 46, reason: "Foul" },
      { player: "Elijah Just", team: "New Zealand", minute: 56, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "L3_Croatia_v_Ghana",
    home: "Croatia", away: "Ghana", date: "2026-06-27",
    goals: [
      { player: "Petar Sučić", team: "Croatia", minute: 31, type: "goal" },
      { player: "Derrick Luckassen", team: "Ghana", minute: 73, type: "goal" },
      { player: "Nikola Vlašić", team: "Croatia", minute: 83, type: "goal" },
    ],
    yellowCards: [
      { player: "Ivan Perišić", team: "Croatia", minute: 68, reason: "Foul" },
      { player: "Kojo Peprah Oppong", team: "Ghana", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "L3_Panama_v_England",
    home: "Panama", away: "England", date: "2026-06-27",
    goals: [
      { player: "Jude Bellingham", team: "England", minute: 62, type: "goal" },
      { player: "Harry Kane", team: "England", minute: 67, type: "goal" },
    ],
    yellowCards: [
      { player: "José Fajardo", team: "Panama", minute: 53, reason: "Foul" },
      { player: "Jarell Quansah", team: "England", minute: 60, reason: "Foul" },
      { player: "Andrés Andrade", team: "Panama", minute: 84, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K3_Colombia_v_Portugal",
    home: "Colombia", away: "Portugal", date: "2026-06-27",
    goals: [],
    yellowCards: [
      { player: "Gustavo Puerta", team: "Colombia", minute: 86, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "K3_Congo_DR_v_Uzbekistan",
    home: "Congo DR", away: "Uzbekistan", date: "2026-06-27",
    goals: [
      { player: "Eldor Shomurodov", team: "Uzbekistan", minute: 10, type: "goal" },
      { player: "Yoane Wissa", team: "Congo DR", minute: 68, type: "penalty" },
      { player: "Fiston Mayele", team: "Congo DR", minute: 78, type: "goal" },
      { player: "Yoane Wissa", team: "Congo DR", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Noah Sadiki", team: "Congo DR", minute: 21, reason: "Foul" },
      { player: "Abdukodir Khusanov", team: "Uzbekistan", minute: 43, reason: "Foul" },
      { player: "Nathanaël Mbuku", team: "Congo DR", minute: 45, reason: "Foul" },
      { player: "Sherzod Nasrullaev", team: "Uzbekistan", minute: 48, reason: "Foul" },
      { player: "Samuel Moutoussamy", team: "Congo DR", minute: 62, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "J3_Algeria_v_Austria",
    home: "Algeria", away: "Austria", date: "2026-06-28",
    goals: [
      { player: "Marko Arnautović", team: "Austria", minute: 28, type: "goal" },
      { player: "Rafik Belghali", team: "Algeria", minute: 45, type: "goal" },
      { player: "Marcel Sabitzer", team: "Austria", minute: 55, type: "goal" },
      { player: "Riyad Mahrez", team: "Algeria", minute: 60, type: "goal" },
      { player: "Riyad Mahrez", team: "Algeria", minute: 90, type: "goal" },
      { player: "Saša Kalajdžić", team: "Austria", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Marko Arnautović", team: "Austria", minute: 11, reason: "Roughing" },
    ],
    redCards: [],
  },
  {
    fixtureId: "J3_Jordan_v_Argentina",
    home: "Jordan", away: "Argentina", date: "2026-06-28",
    goals: [
      { player: "Giovani Lo Celso", team: "Argentina", minute: 19, type: "goal" },
      { player: "L. Martinez", team: "Argentina", minute: 31, type: "penalty" },
      { player: "M. Tamari", team: "Jordan", minute: 55, type: "goal" },
      { player: "Lionel Messi", team: "Argentina", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "M. Abu Taha", team: "Jordan", minute: 17, reason: "Tripping" },
      { player: "Y. Al Arab", team: "Jordan", minute: 64, reason: "Roughing" },
      { player: "Shararh", team: "Jordan", minute: 90, reason: "Tripping" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1561329",
    home: "South Africa", away: "Canada", date: "2026-06-28",
    goals: [
      { player: "Stephen Eustáquio", team: "Canada", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Nathan Saliba", team: "Canada", minute: 54, reason: "Foul" },
      { player: "Niko Sigur", team: "Canada", minute: 67, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1562344",
    home: "Brazil", away: "Japan", date: "2026-06-29",
    goals: [
      { player: "Kaishū Sano", team: "Japan", minute: 29, type: "goal" },
      { player: "Casemiro", team: "Brazil", minute: 56, type: "goal" },
      { player: "Gabriel Martinelli", team: "Brazil", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Kaishū Sano", team: "Japan", minute: 12, reason: "Foul" },
      { player: "Casemiro", team: "Brazil", minute: 14, reason: "Foul" },
      { player: "Daichi Kamada", team: "Japan", minute: 45, reason: "Foul" },
      { player: "Danilo", team: "Brazil", minute: 48, reason: "Foul" },
      { player: "Junnosuke Suzuki", team: "Japan", minute: 84, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1565176",
    home: "Germany", away: "Paraguay", date: "2026-06-29",
    goals: [
      { player: "Julio Enciso", team: "Paraguay", minute: 42, type: "goal" },
      { player: "Kai Havertz", team: "Germany", minute: 54, type: "goal" },
    ],
    yellowCards: [
      { player: "Andrés Cubas", team: "Paraguay", minute: 65, reason: "Foul" },
      { player: "Kai Havertz", team: "Germany", minute: 106, reason: "Foul" },
      { player: "Jamal Musiala", team: "Germany", minute: 115, reason: "Foul" },
      { player: "Matías Galarza", team: "Paraguay", minute: 117, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1562345",
    home: "Netherlands", away: "Morocco", date: "2026-06-30",
    goals: [
      { player: "Cody Gakpo", team: "Netherlands", minute: 72, type: "goal" },
      { player: "Issa Diop", team: "Morocco", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Issa Diop", team: "Morocco", minute: 47, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1564789",
    home: "Ivory Coast", away: "Norway", date: "2026-06-30",
    goals: [
      { player: "Antonio Nusa", team: "Norway", minute: 39, type: "goal" },
      { player: "Amad Diallo", team: "Ivory Coast", minute: 74, type: "goal" },
      { player: "Erling Haaland", team: "Norway", minute: 86, type: "goal" },
    ],
    yellowCards: [
      { player: "Antonio Nusa", team: "Norway", minute: 45, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1565177",
    home: "France", away: "Sweden", date: "2026-06-30",
    goals: [
      { player: "Kylian Mbappé", team: "France", minute: 45, type: "goal" },
      { player: "Bradley Barcola", team: "France", minute: 53, type: "goal" },
      { player: "Kylian Mbappé", team: "France", minute: 74, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "1567306",
    home: "Mexico", away: "Ecuador", date: "2026-07-01",
    goals: [
      { player: "Julián Quiñones", team: "Mexico", minute: 22, type: "goal" },
      { player: "Raúl Jiménez", team: "Mexico", minute: 31, type: "goal" },
    ],
    yellowCards: [
      { player: "Alan Franco", team: "Ecuador", minute: 45, reason: "Tripping" },
      { player: "Kendry Páez", team: "Ecuador", minute: 90, reason: "Tripping" },
      { player: "Moisés Caicedo", team: "Ecuador", minute: 90, reason: "Tripping" },
    ],
    redCards: [
      { player: "Piero Hincapié", team: "Ecuador", minute: 90, reason: "Unsportsmanlike conduct" },
    ],
  },
  {
    fixtureId: "1567307",
    home: "England", away: "Congo DR", date: "2026-07-01",
    goals: [
      { player: "Brian Cipenga", team: "Congo DR", minute: 7, type: "goal" },
      { player: "Harry Kane", team: "England", minute: 75, type: "goal" },
      { player: "Harry Kane", team: "England", minute: 86, type: "goal" },
    ],
    yellowCards: [
      { player: "Jude Bellingham", team: "England", minute: 19, reason: "Foul" },
      { player: "Noah Sadiki", team: "Congo DR", minute: 27, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1567308",
    home: "Belgium", away: "Senegal", date: "2026-07-01",
    goals: [
      { player: "Habib Diarra", team: "Senegal", minute: 24, type: "goal" },
      { player: "Ismaïla Sarr", team: "Senegal", minute: 51, type: "goal" },
      { player: "Romelu Lukaku", team: "Belgium", minute: 86, type: "goal" },
      { player: "Youri Tielemans", team: "Belgium", minute: 89, type: "goal" },
      { player: "Youri Tielemans", team: "Belgium", minute: 120, type: "penalty" },
    ],
    yellowCards: [
      { player: "Brandon Mechele", team: "Belgium", minute: 64, reason: "Foul" },
      { player: "Lamine Camara", team: "Senegal", minute: 67, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1562586",
    home: "USA", away: "Bosnia & Herzegovina", date: "2026-07-02",
    goals: [
      { player: "Folarin Balogun", team: "USA", minute: 45, type: "goal" },
      { player: "Malik Tillman", team: "USA", minute: 82, type: "goal" },
    ],
    yellowCards: [
      { player: "S. Barbarez", team: "Bosnia & Herzegovina", minute: 80 },
      { player: "Stjepan Radeljić", team: "Bosnia & Herzegovina", minute: 80, reason: "Holding" },
    ],
    redCards: [
      { player: "Folarin Balogun", team: "USA", minute: 64, reason: "Serious foul" },
    ],
  },
  {
    fixtureId: "1567311",
    home: "Spain", away: "Austria", date: "2026-07-02",
    goals: [
      { player: "Mikel Oyarzabal", team: "Spain", minute: 36, type: "goal" },
      { player: "Pedro Porro", team: "Spain", minute: 66, type: "goal" },
      { player: "Mikel Oyarzabal", team: "Spain", minute: 89, type: "goal" },
    ],
    yellowCards: [
      { player: "Stefan Posch", team: "Austria", minute: 83, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1567309",
    home: "Portugal", away: "Croatia", date: "2026-07-02",
    goals: [
      { player: "Ivan Perišić", team: "Croatia", minute: 53, type: "goal" },
      { player: "Cristiano Ronaldo", team: "Portugal", minute: 68, type: "penalty" },
      { player: "Gonçalo Ramos", team: "Portugal", minute: 90, minuteStoppage: 4, type: "goal" },
    ],
    yellowCards: [
      { player: "Rúben Dias", team: "Portugal", minute: 17, reason: "Elbowing" },
      { player: "Luka Modrić", team: "Croatia", minute: 59, reason: "Tripping" },
      { player: "Ivan Perišić", team: "Croatia", minute: 90, reason: "Unsportsmanlike conduct" },
    ],
    redCards: [],
  },
  {
    fixtureId: "1567312",
    home: "Switzerland", away: "Algeria", date: "2026-07-03",
    goals: [
      { player: "Breel Embolo", team: "Switzerland", minute: 10, type: "goal" },
      { player: "Dan Ndoye", team: "Switzerland", minute: 46, type: "goal" },
    ],
    yellowCards: [
      { player: "Farès Chaïbi", team: "Algeria", minute: 36, reason: "Tripping" },
      { player: "Hicham Boudaoui", team: "Algeria", minute: 72, reason: "Roughing" },
    ],
    redCards: [],
  },
];

export const MATCH_EVENTS_LAST_UPDATED = '2026-07-03T07:35:59.901Z';
