// Auto-generated by scripts/sync-live-stats.ts — do not edit manually.
// Live match statistics feeding the territory/pressure heatmap (lib/heatmap.ts).

export interface TeamMatchStats {
  team: string;
  possession: number;      // 0..1
  totalShots: number;
  shotsInsideBox: number;
  shotsOutsideBox: number;
  shotsOnGoal: number;
  corners: number;
  xg: number;
  passAccuracy: number;    // 0..1
}

export interface MatchStats {
  fixtureId: string; // matches WCFixture.id
  home: string;
  away: string;
  date: string;
  status: 'LIVE' | 'FINISHED';
  elapsed: number | null;  // live minute, null when finished
  homeStats: TeamMatchStats;
  awayStats: TeamMatchStats;
}

export const MATCH_STATS: MatchStats[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Mexico", possession: 0.61, totalShots: 16, shotsInsideBox: 9, shotsOutsideBox: 7, shotsOnGoal: 4, corners: 3, xg: 1.46, passAccuracy: 0.9 },
    awayStats: { team: "South Africa", possession: 0.39, totalShots: 3, shotsInsideBox: 1, shotsOutsideBox: 2, shotsOnGoal: 2, corners: 1, xg: 0.07, passAccuracy: 0.81 },
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "South Korea", possession: 0.62, totalShots: 15, shotsInsideBox: 10, shotsOutsideBox: 5, shotsOnGoal: 6, corners: 4, xg: 2.3, passAccuracy: 0.87 },
    awayStats: { team: "Czech Republic", possession: 0.38, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 4, corners: 5, xg: 0.83, passAccuracy: 0.7 },
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Canada", possession: 0.61, totalShots: 13, shotsInsideBox: 10, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 9, xg: 1.23, passAccuracy: 0.74 },
    awayStats: { team: "Bosnia & Herzegovina", possession: 0.39, totalShots: 8, shotsInsideBox: 5, shotsOutsideBox: 3, shotsOnGoal: 3, corners: 4, xg: 0.96, passAccuracy: 0.63 },
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "USA", possession: 0.65, totalShots: 16, shotsInsideBox: 13, shotsOutsideBox: 3, shotsOnGoal: 6, corners: 3, xg: 1.27, passAccuracy: 0.85 },
    awayStats: { team: "Paraguay", possession: 0.35, totalShots: 9, shotsInsideBox: 4, shotsOutsideBox: 5, shotsOnGoal: 1, corners: 1, xg: 0.51, passAccuracy: 0.72 },
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Qatar", possession: 0.32, totalShots: 7, shotsInsideBox: 5, shotsOutsideBox: 2, shotsOnGoal: 4, corners: 3, xg: 0.76, passAccuracy: 0.71 },
    awayStats: { team: "Switzerland", possession: 0.68, totalShots: 26, shotsInsideBox: 18, shotsOutsideBox: 8, shotsOnGoal: 7, corners: 10, xg: 3.24, passAccuracy: 0.91 },
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Brazil", possession: 0.54, totalShots: 12, shotsInsideBox: 9, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 5, xg: 1.24, passAccuracy: 0.88 },
    awayStats: { team: "Morocco", possession: 0.46, totalShots: 12, shotsInsideBox: 6, shotsOutsideBox: 6, shotsOnGoal: 2, corners: 0, xg: 1.28, passAccuracy: 0.87 },
  },
  {
    fixtureId: "D1_Haiti_v_Scotland",
    home: "Haiti", away: "Scotland", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Haiti", possession: 0.54, totalShots: 15, shotsInsideBox: 8, shotsOutsideBox: 7, shotsOnGoal: 2, corners: 4, xg: 1.21, passAccuracy: 0.85 },
    awayStats: { team: "Scotland", possession: 0.46, totalShots: 9, shotsInsideBox: 8, shotsOutsideBox: 1, shotsOnGoal: 2, corners: 3, xg: 1.07, passAccuracy: 0.82 },
  },
  {
    fixtureId: "C1_Australia_v_T_rkiye",
    home: "Australia", away: "Türkiye", date: "2026-06-14",
    status: "FINISHED", elapsed: null,
    homeStats: { team: "Australia", possession: 0.28, totalShots: 9, shotsInsideBox: 6, shotsOutsideBox: 3, shotsOnGoal: 4, corners: 5, xg: 0.77, passAccuracy: 0.75 },
    awayStats: { team: "Türkiye", possession: 0.72, totalShots: 30, shotsInsideBox: 14, shotsOutsideBox: 16, shotsOnGoal: 8, corners: 8, xg: 1.33, passAccuracy: 0.9 },
  },
];

export const MATCH_STATS_LAST_UPDATED = '2026-06-14T11:52:10.572Z';
