// Auto-generated by scripts/sync-match-events.ts — do not edit manually.
// Refreshed every 5 minutes during match windows via GitHub Actions.
// Source of truth for tournament intelligence (top scorers, cards).
// Player PROFILES stay hand-curated in lib/playerProfilesData.ts.

export type EventType = 'goal' | 'own-goal' | 'penalty';

export interface GoalEvent {
  player:           string;
  team:             string;
  minute:           number;
  minuteStoppage?:  number; // e.g. 5 for "45+5'"
  type:             EventType;
}

export interface CardEvent {
  player:  string;
  team:    string;
  minute?: number;
  reason?: string;
}

export interface MatchEvents {
  fixtureId:   string; // matches WCFixture.id
  home:        string;
  away:        string;
  date:        string; // YYYY-MM-DD
  goals:       GoalEvent[];
  yellowCards: CardEvent[];
  redCards:    CardEvent[];
}

export const MATCH_EVENTS: MatchEvents[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    goals: [
      { player: "Julián Quiñones", team: "Mexico", minute: 9, type: "goal" },
      { player: "Raúl Jiménez", team: "Mexico", minute: 67, type: "goal" },
    ],
    yellowCards: [
      { player: "Teboho Mokoena", team: "South Africa", minute: 17, reason: "Foul" },
      { player: "Brian Gutiérrez", team: "Mexico", minute: 23, reason: "Foul" },
      { player: "Nkosinathi Sibisi", team: "South Africa", minute: 74, reason: "Foul" },
    ],
    redCards: [
      { player: "Sphephelo Sithole", team: "South Africa", minute: 49, reason: "Professional foul last man" },
      { player: "Themba Zwane", team: "South Africa", minute: 84, reason: "Violent conduct" },
      { player: "César Montes", team: "Mexico", minute: 90, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    goals: [
      { player: "Ladislav Krejčí", team: "Czech Republic", minute: 59, type: "goal" },
      { player: "Hwang In-beom", team: "South Korea", minute: 67, type: "goal" },
      { player: "Oh Hyeon-gyu", team: "South Korea", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "Gi-Hyuk Lee", team: "South Korea", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    goals: [
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 21, type: "goal" },
      { player: "Cyle Larin", team: "Canada", minute: 78, type: "goal" },
    ],
    yellowCards: [
      { player: "Alistair Johnston", team: "Canada", minute: 11, reason: "Foul" },
      { player: "Ermedin Demirović", team: "Bosnia & Herzegovina", minute: 44, reason: "Foul" },
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 45, reason: "Foul" },
      { player: "Luc de Fougerolles", team: "Canada", minute: 53, reason: "Foul" },
      { player: "Nikola Katić", team: "Bosnia & Herzegovina", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    goals: [
      { player: "Damián Bobadilla", team: "Paraguay", minute: 7, type: "own-goal" },
      { player: "Folarin Balogun", team: "USA", minute: 31, type: "goal" },
      { player: "Folarin Balogun", team: "USA", minute: 45, minuteStoppage: 5, type: "goal" },
      { player: "Maurício", team: "Paraguay", minute: 73, type: "goal" },
      { player: "Giovanni Reyna", team: "USA", minute: 90, minuteStoppage: 8, type: "goal" },
    ],
    yellowCards: [
      { player: "Juan José Cáceres", team: "Paraguay", minute: 10, reason: "Tripping" },
      { player: "Miguel Almirón", team: "Paraguay", minute: 53, reason: "Diving" },
      { player: "Tyler Adams", team: "USA", minute: 59, reason: "Roughing" },
      { player: "Diego Gómez", team: "Paraguay", minute: 79, reason: "Holding" },
      { player: "Álex Arce", team: "Paraguay", minute: 88, reason: "Roughing" },
      { player: "Júnior Alonso", team: "Paraguay", minute: 90, reason: "Holding" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    goals: [
      { player: "Breel Embolo", team: "Switzerland", minute: 17, type: "penalty" },
      { player: "Miro Muheim", team: "Switzerland", minute: 90, minuteStoppage: 4, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Mahmud Abunada", team: "Qatar", minute: 16, reason: "Delay of game" },
      { player: "Jassem Gaber", team: "Qatar", minute: 23, reason: "Roughing" },
      { player: "Denis Zakaria", team: "Switzerland", minute: 42, reason: "Tripping" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    goals: [
      { player: "Ismael Saibari", team: "Morocco", minute: 21, type: "goal" },
      { player: "Vinícius Júnior", team: "Brazil", minute: 32, type: "goal" },
    ],
    yellowCards: [
      { player: "Casemiro", team: "Brazil", minute: 37, reason: "Tripping" },
      { player: "Roger Ibañez", team: "Brazil", minute: 43, reason: "Tripping" },
    ],
    redCards: [],
  },
];

export const MATCH_EVENTS_LAST_UPDATED = '2026-06-14T00:26:42.182Z';
