// Auto-generated by scripts/sync-match-events.ts — do not edit manually.
// Refreshed every 5 minutes during match windows via GitHub Actions.
// Source of truth for tournament intelligence (top scorers, cards).
// Player PROFILES stay hand-curated in lib/playerProfilesData.ts.

export type EventType = 'goal' | 'own-goal' | 'penalty';

export interface GoalEvent {
  player:           string;
  team:             string;
  minute:           number;
  minuteStoppage?:  number; // e.g. 5 for "45+5'"
  type:             EventType;
}

export interface CardEvent {
  player:  string;
  team:    string;
  minute?: number;
  reason?: string;
}

export interface MatchEvents {
  fixtureId:   string; // matches WCFixture.id
  home:        string;
  away:        string;
  date:        string; // YYYY-MM-DD
  goals:       GoalEvent[];
  yellowCards: CardEvent[];
  redCards:    CardEvent[];
}

export const MATCH_EVENTS: MatchEvents[] = [
  {
    fixtureId: "A1_Mexico_v_South_Africa",
    home: "Mexico", away: "South Africa", date: "2026-06-11",
    goals: [
      { player: "Julián Quiñones", team: "Mexico", minute: 9, type: "goal" },
      { player: "Raúl Jiménez", team: "Mexico", minute: 67, type: "goal" },
    ],
    yellowCards: [
      { player: "Teboho Mokoena", team: "South Africa", minute: 17, reason: "Foul" },
      { player: "Brian Gutiérrez", team: "Mexico", minute: 23, reason: "Foul" },
      { player: "Nkosinathi Sibisi", team: "South Africa", minute: 74, reason: "Foul" },
    ],
    redCards: [
      { player: "Sphephelo Sithole", team: "South Africa", minute: 49, reason: "Professional foul last man" },
      { player: "Themba Zwane", team: "South Africa", minute: 84, reason: "Violent conduct" },
      { player: "César Montes", team: "Mexico", minute: 90, reason: "Professional foul last man" },
    ],
  },
  {
    fixtureId: "A1_South_Korea_v_Czech_Republic",
    home: "South Korea", away: "Czech Republic", date: "2026-06-12",
    goals: [
      { player: "Ladislav Krejčí", team: "Czech Republic", minute: 59, type: "goal" },
      { player: "Hwang In-beom", team: "South Korea", minute: 67, type: "goal" },
      { player: "Oh Hyeon-gyu", team: "South Korea", minute: 80, type: "goal" },
    ],
    yellowCards: [
      { player: "Gi-Hyuk Lee", team: "South Korea", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Canada_v_Bosnia_Herzegovina",
    home: "Canada", away: "Bosnia & Herzegovina", date: "2026-06-12",
    goals: [
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 21, type: "goal" },
      { player: "Cyle Larin", team: "Canada", minute: 78, type: "goal" },
    ],
    yellowCards: [
      { player: "Alistair Johnston", team: "Canada", minute: 11, reason: "Foul" },
      { player: "Jovo Lukić", team: "Bosnia & Herzegovina", minute: 45, reason: "Foul" },
      { player: "Ermedin Demirović", team: "Bosnia & Herzegovina", minute: 45, reason: "Foul" },
      { player: "Luc de Fougerolles", team: "Canada", minute: 53, reason: "Foul" },
      { player: "Nikola Katić", team: "Bosnia & Herzegovina", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C1_USA_v_Paraguay",
    home: "USA", away: "Paraguay", date: "2026-06-13",
    goals: [
      { player: "Damián Bobadilla", team: "Paraguay", minute: 7, type: "own-goal" },
      { player: "Folarin Balogun", team: "USA", minute: 31, type: "goal" },
      { player: "Folarin Balogun", team: "USA", minute: 45, type: "goal" },
      { player: "Maurício", team: "Paraguay", minute: 73, type: "goal" },
      { player: "Giovanni Reyna", team: "USA", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Juan José Cáceres", team: "Paraguay", minute: 10, reason: "Foul" },
      { player: "Miguel Almirón", team: "Paraguay", minute: 53, reason: "Simulation" },
      { player: "Tyler Adams", team: "USA", minute: 59, reason: "Foul" },
      { player: "Diego Gómez", team: "Paraguay", minute: 79, reason: "Foul" },
      { player: "Álex Arce", team: "Paraguay", minute: 88, reason: "Foul" },
      { player: "Júnior Alonso", team: "Paraguay", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "B1_Qatar_v_Switzerland",
    home: "Qatar", away: "Switzerland", date: "2026-06-13",
    goals: [
      { player: "Breel Embolo", team: "Switzerland", minute: 17, type: "penalty" },
      { player: "Miro Muheim", team: "Switzerland", minute: 90, type: "own-goal" },
    ],
    yellowCards: [
      { player: "Mahmud Abunada", team: "Qatar", minute: 16, reason: "Time wasting" },
      { player: "Jassem Gaber Abdulsallam", team: "Qatar", minute: 23, reason: "Foul" },
      { player: "Denis Zakaria", team: "Switzerland", minute: 42, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D1_Brazil_v_Morocco",
    home: "Brazil", away: "Morocco", date: "2026-06-13",
    goals: [
      { player: "Ismael Saibari", team: "Morocco", minute: 21, type: "goal" },
      { player: "Vinícius Júnior", team: "Brazil", minute: 32, type: "goal" },
    ],
    yellowCards: [
      { player: "Casemiro", team: "Brazil", minute: 37, reason: "Foul" },
      { player: "Roger Ibañez", team: "Brazil", minute: 43, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "D1_Haiti_v_Scotland",
    home: "Haiti", away: "Scotland", date: "2026-06-14",
    goals: [
      { player: "John McGinn", team: "Scotland", minute: 28, type: "goal" },
    ],
    yellowCards: [
      { player: "Jean-Ricner Bellegarde", team: "Haiti", minute: 39, reason: "Foul" },
      { player: "Aaron Hickey", team: "Scotland", minute: 47, reason: "Foul" },
      { player: "Kenny McLean", team: "Scotland", minute: 90, reason: "Foul" },
      { player: "Findlay Curtis", team: "Scotland", minute: 90, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "C1_Australia_v_T_rkiye",
    home: "Australia", away: "Türkiye", date: "2026-06-14",
    goals: [
      { player: "Nestory Irankunda", team: "Australia", minute: 27, type: "goal" },
      { player: "Connor Metcalfe", team: "Australia", minute: 75, type: "goal" },
    ],
    yellowCards: [
      { player: "Yunus Akgün", team: "Türkiye", minute: 86, reason: "Foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E1_Germany_v_Cura_ao",
    home: "Germany", away: "Curaçao", date: "2026-06-14",
    goals: [
      { player: "Felix Nmecha", team: "Germany", minute: 6, type: "goal" },
      { player: "Livano Comenencia", team: "Curaçao", minute: 21, type: "goal" },
      { player: "Nico Schlotterbeck", team: "Germany", minute: 38, type: "goal" },
      { player: "Kai Havertz", team: "Germany", minute: 45, minuteStoppage: 5, type: "penalty" },
      { player: "Jamal Musiala", team: "Germany", minute: 47, type: "goal" },
      { player: "Nathaniel Brown", team: "Germany", minute: 68, type: "goal" },
      { player: "Deniz Undav", team: "Germany", minute: 78, type: "goal" },
      { player: "Kai Havertz", team: "Germany", minute: 88, type: "goal" },
    ],
    yellowCards: [],
    redCards: [],
  },
  {
    fixtureId: "F1_Netherlands_v_Japan",
    home: "Netherlands", away: "Japan", date: "2026-06-14",
    goals: [
      { player: "Virgil van Dijk", team: "Netherlands", minute: 51, type: "goal" },
      { player: "Keito Nakamura", team: "Japan", minute: 57, type: "goal" },
      { player: "Crysencio Summerville", team: "Netherlands", minute: 64, type: "goal" },
      { player: "Daichi Kamada", team: "Japan", minute: 89, type: "goal" },
    ],
    yellowCards: [
      { player: "Crysencio Summerville", team: "Netherlands", minute: 61, reason: "Foul" },
      { player: "Memphis Depay", team: "Netherlands", minute: 83, reason: "Foul" },
      { player: "Micky van de Ven", team: "Netherlands", minute: 90, reason: "Professional foul" },
    ],
    redCards: [],
  },
  {
    fixtureId: "E1_Ivory_Coast_v_Ecuador",
    home: "Ivory Coast", away: "Ecuador", date: "2026-06-14",
    goals: [
      { player: "Amad Diallo", team: "Ivory Coast", minute: 90, type: "goal" },
    ],
    yellowCards: [
      { player: "Seko Fofana", team: "Ivory Coast", minute: 28, reason: "Roughing" },
      { player: "Franck Kessié", team: "Ivory Coast", minute: 38, reason: "Tripping" },
      { player: "Guéla Doué", team: "Ivory Coast", minute: 40, reason: "Tripping" },
      { player: "Jackson Porozo", team: "Ecuador", minute: 73, reason: "Holding" },
    ],
    redCards: [],
  },
  {
    fixtureId: "F1_Sweden_v_Tunisia",
    home: "Sweden", away: "Tunisia", date: "2026-06-15",
    goals: [
      { player: "Yasin Ayari", team: "Sweden", minute: 7, type: "goal" },
      { player: "Alexander Isak", team: "Sweden", minute: 30, type: "goal" },
      { player: "Omar Rekik", team: "Tunisia", minute: 43, type: "goal" },
      { player: "Viktor Gyökeres", team: "Sweden", minute: 59, type: "goal" },
      { player: "Mattias Svanberg", team: "Sweden", minute: 84, type: "goal" },
      { player: "Yasin Ayari", team: "Sweden", minute: 90, minuteStoppage: 6, type: "goal" },
    ],
    yellowCards: [
      { player: "Rani Khedira", team: "Tunisia", minute: 54, reason: "Tripping" },
    ],
    redCards: [],
  },
];

export const MATCH_EVENTS_LAST_UPDATED = '2026-06-15T09:46:06.817Z';
