import type { LangCode } from './i18n';
import type { Position } from './playerXI';

export interface PlayerContent {
  positionFull: string;
  description:  string;
  features:     string[];
  liliSays:     string;
}

export interface PlayerI18nBundle {
  players: PlayerContent[]; // 11 entries, index = player.number - 1
}

export const PLAYER_I18N: Record<LangCode, PlayerI18nBundle> = {

  // ─── English ────────────────────────────────────────────────────────────────
  EN: { players: [
    { positionFull: 'Goalkeeper',           description: 'The last line of intelligence. World Signals watches the full 48-team field simultaneously, surfacing the signals that matter before they become obvious — climate stress, momentum shifts, structural danger.', features: ['Multi-dimensional signal aggregation across all groups', 'Danger zone classification and momentum detection', 'Environmental and logistical pressure scoring', 'Cross-confederation pattern recognition engine'], liliSays: 'I watch everything so you only need to watch what counts.' },
    { positionFull: 'Right Back',           description: 'Tactical, precise, positioned exactly where the battle is fought. Stadium Intelligence maps all 16 WC 2026 venues with environmental, logistical, and competitive data — every pitch is a different game.', features: ['16-venue ecosystem profiles across 3 countries', 'Altitude, heat, and humidity performance indices', 'Travel stress modelling per venue stop', 'Tournament pressure coefficient per stadium'], liliSays: 'Every pitch is a different game. I know them all.' },
    { positionFull: 'Center Back',          description: 'The data bedrock. Nothing gets past it. The World Table tracks all 12 groups and 48 teams simultaneously — qualification mathematics, form indicators, and points projections in one clean view.', features: ['All 12 groups, 48 teams tracked in real time', 'Win / draw / loss form dots per team', 'Live qualification probability overlay', 'Group tiebreaker scenario analysis'], liliSays: 'In the data, the truth. Always.' },
    { positionFull: 'Center Back',          description: 'Power and authority at the structural level. Confederations maps the global football power landscape — who dominates, who surprises, and where the title will most likely come from.', features: ['6-confederation power and simulation analysis', 'Monte Carlo WC winner probability by region', 'Tournament survival race by stage', 'Confederation clash probability matrix'], liliSays: 'Europe defends. South America attacks. The rest is chaos — and I love chaos.' },
    { positionFull: 'Left Back',            description: 'Disciplined, methodical, covers every meter of terrain. Route Intelligence is the environmental engine — mapping how travel distances, altitude shifts, and climate transitions stack up to fatigue the field.', features: ['Danger zone classification: Death Corridor → Safe', 'Climate transition fatigue scoring per campaign', 'Altitude and heat exposure per team route', 'Full 48-team difficulty ranking with briefings'], liliSays: 'The hardest match is sometimes the one before the match.' },
    { positionFull: 'Central Midfielder',   description: 'Reads tension before anyone else does. The Drama Index runs 729 group-stage outcome scenarios per group, using Shannon entropy to score how mathematically unpredictable each group really is.', features: ['729-scenario analytical engine per group', 'Shannon entropy drama score 0–100', 'CALM / BUILDING / TENSION / CHAOS classification', 'Dark horse callouts and qualifying-pair probabilities'], liliSays: 'Every group tells a story. Some are thrillers.' },
    { positionFull: 'Attacking Midfielder', description: "The creative playmaker. Alternate Timeline is the counterfactual engine — shift any team's effective strength and watch how the group re-draws itself, match by match, qualification by qualification.", features: ['Strength delta override from −20 to +20', 'Per-match probability comparison: BASE vs ALT', 'Qualification shift and expected-points analysis', 'Group ripple effect on all 3 rivals simultaneously'], liliSays: 'What if Argentina were weaker? What if Morocco were stronger? I answer both.' },
    { positionFull: 'Central Midfielder',   description: "Endurance and range. The Cumulative Graph tracks how teams' expected tournament momentum builds or collapses across the full group stage — fixture by fixture, day by day.", features: ['Expected-points trajectory per team over 3 matchdays', 'Multi-team comparison overlay in the same group', 'Momentum shift detection at the midpoint', 'Visual divergence from pre-tournament projections'], liliSays: "It's not where you start. It's where you're going." },
    { positionFull: 'Right Winger',         description: 'Fast, direct, attacks the space. Team Route maps the full geographic and environmental journey any team will make through the WC 2026 venues — with venue-by-venue intelligence at every stop.', features: ['Full campaign route mapped by matchday', 'Venue environmental profile per stop', 'Climate and altitude transition notes between venues', 'Total travel distance and estimated flight hours'], liliSays: 'Before the ball is kicked, the journey has already begun.' },
    { positionFull: 'Striker',              description: 'The duel. Pure competitive instinct. Select any WC 2026 team and Lili generates a full prediction profile — then runs a Monte Carlo tournament simulation across up to 10,000 scenarios.', features: ['Match-by-match group stage prediction profile', 'Monte Carlo tournament simulation (1 to 10,000 runs)', 'Win probability per knockout round', 'Lili reasoning, danger signals, and key opponent analysis'], liliSays: "Pick your team. I'll tell you what happens." },
    { positionFull: 'Left Winger',          description: 'Passionate, personal, always moving forward. Choose your team and follow their projected path through the entire tournament — from the first group-stage whistle to the final.', features: ['Projected knockout path from group stage to final', 'Win / draw / loss probability per group fixture', 'Round-by-round survival odds through the bracket', 'Lili tactical insight and risk note per fixture'], liliSays: "Every fan deserves to know the truth about their team's chances." },
  ]},

  // ─── French ─────────────────────────────────────────────────────────────────
  FR: { players: [
    { positionFull: 'Gardien',          description: "La dernière ligne d'intelligence. World Signals surveille simultanément les 48 équipes, faisant émerger les signaux qui comptent avant qu'ils ne deviennent évidents — stress climatique, changements de momentum, dangers structurels.", features: ["Agrégation multidimensionnelle des signaux sur tous les groupes", "Classification des zones de danger et détection du momentum", "Scoring des pressions environnementales et logistiques", "Moteur de reconnaissance de tendances inter-confédérations"], liliSays: "J'observe tout pour que vous n'ayez à regarder que ce qui compte." },
    { positionFull: 'Arrière Droit',    description: "Tactique, précis, positionné là où la bataille se joue. Stadium Intelligence cartographie les 16 enceintes du Mondial 2026 avec des données environnementales, logistiques et compétitives — chaque terrain est un jeu différent.", features: ["Profils de 16 enceintes dans 3 pays", "Indices de performance altitude, chaleur et humidité", "Modélisation du stress de voyage par étape", "Coefficient de pression du tournoi par stade"], liliSays: "Chaque terrain est un jeu différent. Je les connais tous." },
    { positionFull: 'Défenseur Central', description: "Le socle des données. Rien ne lui échappe. Le Tableau Mondial suit les 12 groupes et 48 équipes simultanément — mathématiques de qualification, indicateurs de forme et projections de points en une vue claire.", features: ["12 groupes, 48 équipes suivis en temps réel", "Historique de forme V/N/D par équipe", "Superposition des probabilités de qualification en direct", "Analyse des scénarios de départage par groupe"], liliSays: "Dans les données, la vérité. Toujours." },
    { positionFull: 'Défenseur Central', description: "Pouvoir et autorité au niveau structurel. Confédérations cartographie le paysage mondial du football — qui domine, qui surprend, et d'où viendra le plus probablement le titre.", features: ["Analyse de puissance et simulation de 6 confédérations", "Probabilité Monte Carlo de victoire en Coupe du Monde par région", "Course de survie au tournoi par phase", "Matrice de probabilité de confrontation entre confédérations"], liliSays: "L'Europe défend. L'Amérique du Sud attaque. Le reste, c'est le chaos — et j'adore le chaos." },
    { positionFull: 'Arrière Gauche',   description: "Discipliné, méthodique, il couvre chaque mètre. Route Intelligence est le moteur environnemental — cartographiant comment les distances de voyage, les changements d'altitude et les transitions climatiques s'accumulent pour épuiser le terrain.", features: ["Classification des zones de danger : Couloir de la Mort → Sécurisé", "Scoring de fatigue des transitions climatiques par campagne", "Exposition altitude et chaleur par route d'équipe", "Classement de difficulté des 48 équipes avec briefings"], liliSays: "Le match le plus difficile est parfois celui qui précède le match." },
    { positionFull: 'Milieu Central',   description: "Lit la tension avant tout le monde. L'Indice de Drame analyse 729 scénarios de résultats par groupe, en utilisant l'entropie de Shannon pour évaluer à quel point chaque groupe est mathématiquement imprévisible.", features: ["Moteur analytique de 729 scénarios par groupe", "Score de drame par entropie de Shannon 0–100", "Classification CALME / MONTÉE / TENSION / CHAOS", "Signalement des outsiders et probabilités de qualification"], liliSays: "Chaque groupe raconte une histoire. Certains sont des thrillers." },
    { positionFull: 'Milieu Offensif',  description: "Le créateur de jeu. Chronologie Alternative est le moteur contrefactuel — modifiez la force effective de n'importe quelle équipe et regardez comment le groupe se redessine, match par match, qualification par qualification.", features: ["Ajustement du delta de force de −20 à +20", "Comparaison de probabilité par match : BASE vs ALT", "Analyse des changements de qualification et des points attendus", "Effet de ricochet sur les 3 rivaux du groupe simultanément"], liliSays: "Et si l'Argentine était plus faible ? Et si le Maroc était plus fort ? Je réponds aux deux." },
    { positionFull: 'Milieu Central',   description: "Endurance et portée. Le Graphe Cumulatif suit comment le momentum de tournoi attendu des équipes se construit ou s'effondre tout au long de la phase de groupes — match par match, jour après jour.", features: ["Trajectoire des points attendus par équipe sur 3 journées", "Superposition de comparaison multi-équipes dans le même groupe", "Détection du changement de momentum à mi-parcours", "Divergence visuelle par rapport aux projections d'avant-tournoi"], liliSays: "Ce n'est pas là où vous commencez qui compte. C'est là où vous allez." },
    { positionFull: 'Ailier Droit',     description: "Rapide, direct, il attaque l'espace. Team Route cartographie le parcours géographique et environnemental complet de chaque équipe à travers les enceintes du Mondial 2026 — avec des renseignements venue par venue.", features: ["Parcours complet de campagne cartographié par journée", "Profil environnemental de l'enceinte à chaque étape", "Notes de transition climatique et d'altitude entre les stades", "Distance de voyage totale et heures de vol estimées"], liliSays: "Avant que le ballon soit botté, le voyage a déjà commencé." },
    { positionFull: 'Attaquant',        description: "Le duel. L'instinct compétitif pur. Sélectionnez n'importe quelle équipe du Mondial 2026 et Lili génère un profil de prédiction complet — puis lance une simulation Monte Carlo du tournoi sur jusqu'à 10 000 scénarios.", features: ["Profil de prédiction de la phase de groupes match par match", "Simulation Monte Carlo du tournoi (1 à 10 000 runs)", "Probabilité de victoire par tour éliminatoire", "Raisonnement de Lili, signaux de danger et analyse des adversaires clés"], liliSays: "Choisissez votre équipe. Je vous dis ce qui se passe." },
    { positionFull: 'Ailier Gauche',    description: "Passionné, personnel, toujours en mouvement. Choisissez votre équipe et suivez leur parcours projeté à travers l'intégralité du tournoi — du premier coup de sifflet de la phase de groupes à la finale.", features: ["Parcours éliminatoire projeté de la phase de groupes à la finale", "Probabilité V/N/D par match de groupe", "Chances de survie tour par tour dans le tableau", "Analyse tactique de Lili et note de risque par match"], liliSays: "Chaque supporter mérite de connaître la vérité sur les chances de son équipe." },
  ]},

  // ─── Italian ─────────────────────────────────────────────────────────────────
  IT: { players: [
    { positionFull: 'Portiere',         description: "L'ultima linea d'intelligenza. World Signals osserva tutti i 48 team simultaneamente, portando in superficie i segnali che contano prima che diventino ovvi — stress climatico, cambi di momentum, pericoli strutturali.", features: ["Aggregazione multidimensionale dei segnali su tutti i gruppi", "Classificazione delle zone di pericolo e rilevamento del momentum", "Scoring delle pressioni ambientali e logistiche", "Motore di riconoscimento dei pattern tra le confederazioni"], liliSays: "Osservo tutto affinché tu debba osservare solo ciò che conta." },
    { positionFull: 'Terzino Destro',   description: "Tattico, preciso, posizionato esattamente dove si combatte la battaglia. Stadium Intelligence mappa tutte le 16 sedi del Mondiale 2026 con dati ambientali, logistici e competitivi — ogni campo è un gioco diverso.", features: ["Profili di 16 stadi in 3 paesi", "Indici di performance per altitudine, caldo e umidità", "Modellazione dello stress di viaggio per ogni tappa", "Coefficiente di pressione del torneo per stadio"], liliSays: "Ogni campo è un gioco diverso. Li conosco tutti." },
    { positionFull: 'Difensore Centrale', description: "La base dati. Niente le sfugge. La Tabella Mondiale tiene traccia di tutti i 12 gironi e 48 squadre simultaneamente — matematica di qualificazione, indicatori di forma e proiezioni di punti in un'unica vista.", features: ["12 gironi, 48 squadre monitorate in tempo reale", "Storico di forma V/P/S per squadra", "Overlay delle probabilità di qualificazione in diretta", "Analisi degli scenari di spareggio per girone"], liliSays: "Nei dati, la verità. Sempre." },
    { positionFull: 'Difensore Centrale', description: "Potere e autorità a livello strutturale. Confederazioni mappa il panorama calcistico mondiale — chi domina, chi sorprende, e da dove verrà più probabilmente il titolo.", features: ["Analisi di potere e simulazione di 6 confederazioni", "Probabilità Monte Carlo di vincere i Mondiali per regione", "Corsa alla sopravvivenza nel torneo per fase", "Matrice di probabilità degli scontri tra confederazioni"], liliSays: "L'Europa difende. Il Sud America attacca. Il resto è caos — e io adoro il caos." },
    { positionFull: 'Terzino Sinistro',  description: "Disciplinato, metodico, copre ogni metro di terreno. Route Intelligence è il motore ambientale — mappa come le distanze di viaggio, i cambi di altitudine e le transizioni climatiche si accumulano per affaticare il campo.", features: ["Classificazione zone di pericolo: Corridoio della Morte → Sicuro", "Scoring della fatica da transizione climatica per campagna", "Esposizione ad altitudine e caldo per rotta di squadra", "Classifica di difficoltà completa delle 48 squadre"], liliSays: "La partita più difficile è a volte quella prima della partita." },
    { positionFull: 'Centrocampista',   description: "Legge la tensione prima di tutti. Il Drama Index esegue 729 scenari di risultati per girone, usando l'entropia di Shannon per valutare quanto ogni girone sia matematicamente imprevedibile.", features: ["Motore analitico di 729 scenari per girone", "Punteggio drama con entropia di Shannon 0–100", "Classificazione CALMO / IN CRESCITA / TENSIONE / CAOS", "Segnalazione di outsider e probabilità di qualificazione"], liliSays: "Ogni girone racconta una storia. Alcuni sono thriller." },
    { positionFull: 'Trequartista',     description: "Il fantasista creativo. Linea Temporale Alternativa è il motore controfattuale — modifica la forza effettiva di qualsiasi squadra e osserva come il girone si ridisegna, partita per partita.", features: ["Override del delta di forza da −20 a +20", "Confronto delle probabilità per partita: BASE vs ALT", "Analisi del cambio di qualificazione e dei punti attesi", "Effetto a catena nel girone su tutti e 3 i rivali simultaneamente"], liliSays: "E se l'Argentina fosse più debole? E se il Marocco fosse più forte? Rispondo a entrambe." },
    { positionFull: 'Centrocampista',   description: "Resistenza e portata. Il Grafico Cumulativo traccia come il momentum di torneo atteso delle squadre si costruisce o crolla lungo l'intera fase a gironi — partita per partita, giorno dopo giorno.", features: ["Traiettoria dei punti attesi per squadra nelle 3 giornate", "Overlay di confronto multi-squadra nello stesso girone", "Rilevamento del cambio di momentum a metà percorso", "Divergenza visiva rispetto alle proiezioni pre-torneo"], liliSays: "Non conta dove inizi. Conta dove stai andando." },
    { positionFull: 'Ala Destra',       description: "Veloce, diretto, attacca gli spazi. Team Route mappa il percorso geografico e ambientale completo che ogni squadra farà attraverso le sedi del Mondiale 2026 — con intelligence sede per sede.", features: ["Percorso completo di campagna mappato per giornata", "Profilo ambientale della sede per ogni tappa", "Note di transizione climatica e altitudinale tra le sedi", "Distanza di viaggio totale e ore di volo stimate"], liliSays: "Prima che il pallone venga calciato, il viaggio è già iniziato." },
    { positionFull: 'Attaccante',       description: "Il duello. Puro istinto competitivo. Seleziona qualsiasi squadra del Mondiale 2026 e Lili genera un profilo di previsione completo — poi lancia una simulazione Monte Carlo del torneo fino a 10.000 scenari.", features: ["Profilo di previsione della fase a gironi partita per partita", "Simulazione Monte Carlo del torneo (da 1 a 10.000 run)", "Probabilità di vittoria per ogni turno a eliminazione", "Ragionamento di Lili, segnali di pericolo e analisi degli avversari"], liliSays: "Scegli la tua squadra. Ti dico cosa succederà." },
    { positionFull: 'Ala Sinistra',     description: "Appassionata, personale, sempre in movimento. Scegli la tua squadra e segui il loro percorso proiettato attraverso l'intero torneo — dal primo fischio della fase a gironi alla finale.", features: ["Percorso eliminatorio proiettato dalla fase a gironi alla finale", "Probabilità V/P/S per ogni partita del girone", "Probabilità di sopravvivenza turno per turno nel tabellone", "Analisi tattica di Lili e nota di rischio per ogni partita"], liliSays: "Ogni tifoso merita di conoscere la verità sulle possibilità della propria squadra." },
  ]},

  // ─── German ──────────────────────────────────────────────────────────────────
  DE: { players: [
    { positionFull: 'Torwart',                   description: "Die letzte Intelligenzlinie. World Signals beobachtet alle 48 Teams gleichzeitig und bringt die wichtigen Signale ans Licht, bevor sie offensichtlich werden — Klimastress, Momentum-Verschiebungen, strukturelle Gefahr.", features: ["Mehrdimensionale Signalaggregation über alle Gruppen", "Gefahrenzonen-Klassifizierung und Momentum-Erkennung", "Umwelt- und Logistikdruck-Scoring", "Konfederations-übergreifende Mustererkennung"], liliSays: "Ich beobachte alles, damit du nur das Wichtige beobachten musst." },
    { positionFull: 'Rechter Verteidiger',        description: "Taktisch, präzise, genau dort positioniert, wo die Schlacht geführt wird. Stadium Intelligence kartiert alle 16 WM-2026-Venues mit Umwelt-, Logistik- und Wettbewerbsdaten — jedes Spielfeld ist ein anderes Spiel.", features: ["16 Venue-Profile in 3 Ländern", "Höhen-, Hitze- und Feuchtigkeits-Performance-Indizes", "Reisestress-Modellierung pro Venue-Stopp", "Turnier-Druckkoeffizient pro Stadion"], liliSays: "Jedes Spielfeld ist ein anderes Spiel. Ich kenne sie alle." },
    { positionFull: 'Innenverteidiger',           description: "Das Datenfundament. Nichts kommt daran vorbei. Die Welttabelle verfolgt alle 12 Gruppen und 48 Teams gleichzeitig — Qualifikationsmathematik, Formkennzahlen und Punkteprognosen in einer übersichtlichen Ansicht.", features: ["Alle 12 Gruppen, 48 Teams in Echtzeit verfolgt", "S/U/N-Form-Punkte pro Team", "Live-Qualifikationswahrscheinlichkeits-Overlay", "Gruppen-Tiebreaker-Szenarioanalyse"], liliSays: "In den Daten liegt die Wahrheit. Immer." },
    { positionFull: 'Innenverteidiger',           description: "Macht und Autorität auf struktureller Ebene. Konföderationen kartiert die globale Fußball-Machtlandschaft — wer dominiert, wer überrascht, und woher der Titel am wahrscheinlichsten kommen wird.", features: ["6-Konföderation Macht- und Simulationsanalyse", "Monte Carlo WM-Sieger-Wahrscheinlichkeit nach Region", "Turnier-Überlebensrennen nach Phase", "Konföderations-Aufeinandertreffen-Wahrscheinlichkeitsmatrix"], liliSays: "Europa verteidigt. Südamerika greift an. Der Rest ist Chaos — und ich liebe Chaos." },
    { positionFull: 'Linker Verteidiger',         description: "Diszipliniert, methodisch, deckt jeden Meter Terrain ab. Routen-Intelligenz ist die Umwelt-Engine — wie Reisedistanzen, Höhenverschiebungen und Klimaübergänge sich aufaddieren und das Feld ermüden.", features: ["Gefahrenzonen-Klassifizierung: Todeszone → Sicher", "Klimatransitions-Ermüdungs-Scoring pro Kampagne", "Höhen- und Hitzeexposition pro Team-Route", "Vollständiges 48-Team-Schwierigkeitsranking mit Briefings"], liliSays: "Das schwerste Spiel ist manchmal das vor dem Spiel." },
    { positionFull: 'Zentrales Mittelfeld',       description: "Liest Spannung, bevor alle anderen es tun. Der Drama-Index führt 729 Gruppenphase-Ergebnisszenarien pro Gruppe durch und nutzt Shannon-Entropie, um zu bewerten, wie mathematisch unvorhersehbar jede Gruppe wirklich ist.", features: ["729-Szenario-Analyseengine pro Gruppe", "Shannon-Entropie-Drama-Score 0–100", "RUHIG / STEIGERND / SPANNUNG / CHAOS-Klassifizierung", "Außenseiter-Callouts und Qualifikationspaar-Wahrscheinlichkeiten"], liliSays: "Jede Gruppe erzählt eine Geschichte. Einige sind Thriller." },
    { positionFull: 'Offensivmittelfeld',         description: "Der kreative Spielmacher. Alternate Timeline ist die kontrafaktische Engine — ändere die effektive Stärke eines Teams und beobachte, wie sich die Gruppe neu zeichnet, Spiel für Spiel, Qualifikation für Qualifikation.", features: ["Stärke-Delta-Override von −20 bis +20", "Spielweise Wahrscheinlichkeitsvergleich: BASIS vs. ALT", "Qualifikationsverschiebung und Erwartungspunkte-Analyse", "Gruppen-Welleneffekt auf alle 3 Rivalen gleichzeitig"], liliSays: "Was wäre, wenn Argentinien schwächer wäre? Was wäre, wenn Marokko stärker wäre? Ich beantworte beides." },
    { positionFull: 'Zentrales Mittelfeld',       description: "Ausdauer und Reichweite. Der Kumulative Graph verfolgt, wie das erwartete Turnier-Momentum der Teams über die gesamte Gruppenphase auf- oder abbaut — Spiel für Spiel, Tag für Tag.", features: ["Erwartete-Punkte-Trajektorie pro Team über 3 Spieltage", "Multi-Team-Vergleichs-Overlay in derselben Gruppe", "Momentum-Verschiebungserkennung am Mittelpunkt", "Visuelle Abweichung von Vor-Turnier-Projektionen"], liliSays: "Es kommt nicht darauf an, wo du anfängst. Es kommt darauf an, wohin du gehst." },
    { positionFull: 'Rechtsaußen',               description: "Schnell, direkt, greift den Raum an. Team-Route kartiert den vollständigen geografischen und ökologischen Weg jedes Teams durch die WM-2026-Venues — mit Venue-für-Venue-Intelligenz an jedem Stop.", features: ["Vollständige Kampagnenroute nach Spieltag kartiert", "Venue-Umweltprofil pro Stop", "Klimatransitions- und Höhennotizen zwischen Venues", "Gesamtreisedistanz und geschätzte Flugstunden"], liliSays: "Bevor der Ball getreten wird, hat die Reise bereits begonnen." },
    { positionFull: 'Stürmer',                   description: "Das Duell. Reiner Wettkampfinstinkt. Wähle ein WM-2026-Team und Lili generiert ein vollständiges Vorhersageprofil — dann führt sie eine Monte-Carlo-Turniersimulation über bis zu 10.000 Szenarien durch.", features: ["Spielweise Gruppenphase-Vorhersageprofil", "Monte-Carlo-Turniersimulation (1 bis 10.000 Runs)", "Siegwahrscheinlichkeit pro K.-o.-Runde", "Lilis Analyse, Gefahrensignale und Schlüsselgegner-Analyse"], liliSays: "Wähl dein Team. Ich sage dir, was passiert." },
    { positionFull: 'Linksaußen',                description: "Leidenschaftlich, persönlich, immer vorwärts. Wähle dein Team und verfolge ihren projizierten Weg durch das gesamte Turnier — vom ersten Gruppenphase-Pfiff bis zum Finale.", features: ["Projizierter K.-o.-Weg von der Gruppenphase bis zum Finale", "S/U/N-Wahrscheinlichkeit pro Gruppenspiel", "Überlebenschancen Runde für Runde im Tableau", "Lilis taktische Einschätzung und Risikonotiz pro Spiel"], liliSays: "Jeder Fan verdient es, die Wahrheit über die Chancen seines Teams zu kennen." },
  ]},

  // ─── Spanish ─────────────────────────────────────────────────────────────────
  ES: { players: [
    { positionFull: 'Portero',            description: "La última línea de inteligencia. World Signals observa el campo completo de 48 equipos simultáneamente, sacando a la superficie las señales que importan antes de que se vuelvan obvias — estrés climático, cambios de momentum, peligro estructural.", features: ["Agregación multidimensional de señales en todos los grupos", "Clasificación de zonas de peligro y detección de momentum", "Puntuación de presión ambiental y logística", "Motor de reconocimiento de patrones entre confederaciones"], liliSays: "Lo observo todo para que tú solo debas ver lo que cuenta." },
    { positionFull: 'Lateral Derecho',    description: "Táctico, preciso, posicionado exactamente donde se libra la batalla. Stadium Intelligence mapea los 16 estadios del Mundial 2026 con datos ambientales, logísticos y competitivos — cada campo es un juego diferente.", features: ["Perfiles de 16 estadios en 3 países", "Índices de rendimiento por altitud, calor y humedad", "Modelización del estrés de viaje por parada", "Coeficiente de presión del torneo por estadio"], liliSays: "Cada campo es un juego diferente. Los conozco todos." },
    { positionFull: 'Defensa Central',    description: "La base de datos. Nada le pasa por alto. La Tabla Mundial rastrea los 12 grupos y 48 equipos simultáneamente — matemáticas de clasificación, indicadores de forma y proyecciones de puntos en una vista limpia.", features: ["12 grupos, 48 equipos en tiempo real", "Historial de forma V/E/D por equipo", "Superposición de probabilidad de clasificación en vivo", "Análisis de escenarios de desempate por grupo"], liliSays: "En los datos, la verdad. Siempre." },
    { positionFull: 'Defensa Central',    description: "Poder y autoridad a nivel estructural. Confederaciones mapea el panorama del fútbol mundial — quién domina, quién sorprende, y de dónde vendrá el título con mayor probabilidad.", features: ["Análisis de poder y simulación de 6 confederaciones", "Probabilidad Monte Carlo de ganar el Mundial por región", "Carrera de supervivencia en el torneo por fase", "Matriz de probabilidad de enfrentamiento entre confederaciones"], liliSays: "Europa defiende. Sudamérica ataca. El resto es caos — y adoro el caos." },
    { positionFull: 'Lateral Izquierdo',  description: "Disciplinado, metódico, cubre cada metro de terreno. Route Intelligence es el motor ambiental — mapeando cómo las distancias de viaje, cambios de altitud y transiciones climáticas se acumulan para fatigar al campo.", features: ["Clasificación de zonas de peligro: Corredor de la Muerte → Seguro", "Puntuación de fatiga por transición climática por campaña", "Exposición a altitud y calor por ruta de equipo", "Ranking completo de dificultad de los 48 equipos con briefings"], liliSays: "El partido más difícil es a veces el que precede al partido." },
    { positionFull: 'Centrocampista',     description: "Lee la tensión antes que nadie. El Índice de Drama ejecuta 729 escenarios de resultados por grupo, usando la entropía de Shannon para puntuar cuán matemáticamente impredecible es cada grupo.", features: ["Motor analítico de 729 escenarios por grupo", "Puntuación de drama por entropía de Shannon 0–100", "Clasificación CALMA / CRESCENDO / TENSIÓN / CAOS", "Señalización de outsiders y probabilidades de clasificación"], liliSays: "Cada grupo cuenta una historia. Algunos son thrillers." },
    { positionFull: 'Mediapunta',         description: "El creador de juego. Línea Temporal Alternativa es el motor contrafáctico — cambia la fuerza efectiva de cualquier equipo y observa cómo el grupo se redibuja, partido a partido, clasificación a clasificación.", features: ["Override del delta de fuerza de −20 a +20", "Comparación de probabilidad por partido: BASE vs ALT", "Análisis de cambio de clasificación y puntos esperados", "Efecto dominó en los 3 rivales del grupo simultáneamente"], liliSays: "¿Y si Argentina fuera más débil? ¿Y si Marruecos fuera más fuerte? Respondo a ambas." },
    { positionFull: 'Centrocampista',     description: "Resistencia y alcance. El Gráfico Acumulativo rastrea cómo el momentum de torneo esperado de los equipos se construye o colapsa a lo largo de toda la fase de grupos — partido a partido, día a día.", features: ["Trayectoria de puntos esperados por equipo en 3 jornadas", "Superposición de comparación multi-equipo en el mismo grupo", "Detección del cambio de momentum en el punto medio", "Divergencia visual respecto a las proyecciones pre-torneo"], liliSays: "No importa dónde empiezas. Importa a dónde vas." },
    { positionFull: 'Extremo Derecho',    description: "Rápido, directo, ataca el espacio. Team Route mapea el recorrido geográfico y ambiental completo que cualquier equipo realizará por los estadios del Mundial 2026 — con inteligencia estadio por estadio.", features: ["Ruta completa de campaña mapeada por jornada", "Perfil ambiental del estadio por parada", "Notas de transición climática y de altitud entre estadios", "Distancia total de viaje y horas de vuelo estimadas"], liliSays: "Antes de que el balón sea pateado, el viaje ya ha comenzado." },
    { positionFull: 'Delantero',          description: "El duelo. Puro instinto competitivo. Selecciona cualquier equipo del Mundial 2026 y Lili genera un perfil de predicción completo — luego ejecuta una simulación Monte Carlo del torneo con hasta 10.000 escenarios.", features: ["Perfil de predicción de la fase de grupos partido a partido", "Simulación Monte Carlo del torneo (1 a 10.000 runs)", "Probabilidad de victoria por ronda eliminatoria", "Razonamiento de Lili, señales de peligro y análisis de rivales clave"], liliSays: "Elige tu equipo. Te digo qué pasa." },
    { positionFull: 'Extremo Izquierdo',  description: "Apasionada, personal, siempre hacia adelante. Elige tu equipo y sigue su camino proyectado a través de todo el torneo — desde el primer silbato de la fase de grupos hasta la final.", features: ["Camino eliminatorio proyectado desde la fase de grupos hasta la final", "Probabilidad V/E/D por partido de grupo", "Probabilidades de supervivencia ronda a ronda en el cuadro", "Análisis táctico de Lili y nota de riesgo por partido"], liliSays: "Todo aficionado merece conocer la verdad sobre las posibilidades de su equipo." },
  ]},

  // ─── Russian ─────────────────────────────────────────────────────────────────
  RU: { players: [
    { positionFull: 'Вратарь',                      description: "Последний рубеж разведки. World Signals наблюдает за всеми 48 командами одновременно, выводя важные сигналы на поверхность до того, как они становятся очевидными — климатический стресс, изменения momentum, структурные опасности.", features: ["Многомерная агрегация сигналов по всем группам", "Классификация опасных зон и определение momentum", "Оценка экологического и логистического давления", "Межконфедерационный движок распознавания паттернов"], liliSays: "Я слежу за всем, чтобы вам нужно было следить только за главным." },
    { positionFull: 'Правый Защитник',              description: "Тактичный, точный, занимающий именно ту позицию, где ведётся борьба. Stadium Intelligence картирует все 16 площадок ЧМ-2026 с экологическими, логистическими и соревновательными данными — каждое поле — другая игра.", features: ["16 профилей площадок в 3 странах", "Индексы производительности по высоте, жаре и влажности", "Моделирование стресса от поездок по каждой площадке", "Коэффициент турнирного давления по стадионам"], liliSays: "Каждое поле — другая игра. Я знаю их все." },
    { positionFull: 'Центральный Защитник',         description: "Основа данных. Ничто не проходит мимо. Мировая Таблица следит за всеми 12 группами и 48 командами одновременно — математика квалификации, показатели формы и прогнозы очков в одном чистом виде.", features: ["12 групп, 48 команд в реальном времени", "Точки формы П/Н/П по каждой команде", "Оверлей вероятности квалификации в реальном времени", "Анализ сценариев дополнительных показателей по группам"], liliSays: "В данных — правда. Всегда." },
    { positionFull: 'Центральный Защитник',         description: "Власть и авторитет на структурном уровне. Конфедерации картирует глобальный ландшафт футбольной власти — кто доминирует, кто удивляет, и откуда, скорее всего, придёт чемпион.", features: ["Анализ силы и симуляция 6 конфедераций", "Вероятность победы на ЧМ по регионам (Монте-Карло)", "Гонка выживания в турнире по фазам", "Матрица вероятности столкновений между конфедерациями"], liliSays: "Европа обороняется. Южная Америка атакует. Всё остальное — хаос, а я люблю хаос." },
    { positionFull: 'Левый Защитник',               description: "Дисциплинированный, методичный, покрывает каждый метр terrain. Route Intelligence — экологический движок, картирующий, как расстояния перелётов, изменения высоты и климатические переходы накапливаются, чтобы утомить поле.", features: ["Классификация опасных зон: Коридор Смерти → Безопасно", "Оценка климатической усталости по кампаниям", "Воздействие высоты и жары на маршрут каждой команды", "Полный рейтинг сложности 48 команд с брифингами"], liliSays: "Самый трудный матч — иногда тот, что перед матчем." },
    { positionFull: 'Центральный Полузащитник',     description: "Читает напряжение раньше всех. Индекс Драмы просчитывает 729 сценариев исходов группового этапа на группу, используя энтропию Шеннона для оценки математической непредсказуемости каждой группы.", features: ["Аналитический движок 729 сценариев на группу", "Оценка драмы по энтропии Шеннона 0–100", "Классификация СПОКОЙНО / НАРАСТАНИЕ / НАПРЯЖЕНИЕ / ХАОС", "Выявление тёмных лошадок и вероятностей пар квалификации"], liliSays: "Каждая группа рассказывает историю. Некоторые — настоящие триллеры." },
    { positionFull: 'Атакующий Полузащитник',       description: "Творческий плеймейкер. Альтернативный Поток — контрфактический движок: измените эффективную силу любой команды и наблюдайте, как группа перестраивается матч за матчем, квалификация за квалификацией.", features: ["Переопределение дельты силы от −20 до +20", "Сравнение вероятностей по матчам: БАЗА vs АЛЬ", "Анализ сдвига квалификации и ожидаемых очков", "Эффект рябей на всех 3 соперников в группе одновременно"], liliSays: "Что если Аргентина будет слабее? Что если Марокко станет сильнее? Я отвечу на оба вопроса." },
    { positionFull: 'Центральный Полузащитник',     description: "Выносливость и диапазон. Кумулятивный График отслеживает, как ожидаемый турнирный импульс команд нарастает или рушится на протяжении всего группового этапа — матч за матчем, день за днём.", features: ["Траектория ожидаемых очков по команде за 3 тура", "Многокомандный сравнительный оверлей в одной группе", "Определение сдвига импульса в середине", "Визуальное отклонение от дотурнирных прогнозов"], liliSays: "Важно не то, где ты начинаешь. Важно, куда ты идёшь." },
    { positionFull: 'Правый Вингер',                description: "Быстрый, прямолинейный, атакует пространство. Team Route картирует полный географический и экологический путь любой команды по площадкам ЧМ-2026 — с разведданными по каждому объекту.", features: ["Полный маршрут кампании по турам", "Экологический профиль площадки на каждой остановке", "Заметки о климатических и высотных переходах между объектами", "Общее расстояние поездок и расчётное лётное время"], liliSays: "До первого удара по мячу путешествие уже началось." },
    { positionFull: 'Нападающий',                   description: "Дуэль. Чистый соревновательный инстинкт. Выберите любую команду ЧМ-2026, и Лили создаёт полный прогнозный профиль — затем запускает симуляцию Монте-Карло на 10 000 сценариев.", features: ["Прогнозный профиль группового этапа матч за матчем", "Симуляция Монте-Карло (от 1 до 10 000 запусков)", "Вероятность победы в каждом раунде плей-офф", "Анализ Лили, сигналы опасности и ключевые соперники"], liliSays: "Выберите команду. Я скажу вам, что произойдёт." },
    { positionFull: 'Левый Вингер',                 description: "Страстная, личная, всегда вперёд. Выберите свою команду и следите за её проектируемым путём через весь турнир — от первого свистка группового этапа до финала.", features: ["Проектируемый путь в плей-офф от группового этапа до финала", "Вероятность П/Н/П по каждому матчу в группе", "Шансы выживания раунд за раундом в сетке", "Тактический анализ Лили и оценка риска по матчу"], liliSays: "Каждый болельщик заслуживает знать правду о шансах своей команды." },
  ]},

  // ─── Chinese ─────────────────────────────────────────────────────────────────
  CN: { players: [
    { positionFull: '门将',     description: "最后一道情报防线。世界信号同时监视全部48支球队，在关键信号变得显而易见之前将其捕获——气候压力、势头转变、结构性危险。", features: ["跨所有小组的多维信号聚合", "危险区分类和势头检测", "环境和后勤压力评分", "跨联合会模式识别引擎"], liliSays: "我观察一切，让你只需关注最重要的事情。" },
    { positionFull: '右后卫',   description: "战术精准，定位在战斗发生的地方。球场智能绘制了2026年世界杯所有16个场馆的环境、后勤和竞技数据图——每块球场都是不同的比赛。", features: ["3个国家16个场馆生态系统档案", "海拔、高温和湿度表现指数", "每个场馆行程压力建模", "每个球场的赛事压力系数"], liliSays: "每块球场都是不同的比赛。我了解它们所有。" },
    { positionFull: '中后卫',   description: "数据基石，无懈可击。世界积分榜同时追踪12个小组和48支球队——资格赛数学、状态指标和积分预测，一目了然。", features: ["12个小组、48支球队实时追踪", "每队胜/平/负状态记录", "实时资格赛概率叠加", "小组附加赛情景分析"], liliSays: "数据中，自有真理。永远如此。" },
    { positionFull: '中后卫',   description: "结构层面的权力与权威。联合会绘制了全球足球权力格局——谁占主导、谁带来惊喜，以及冠军最可能来自哪里。", features: ["6个联合会实力与模拟分析", "按地区划分的蒙特卡洛世界杯冠军概率", "按阶段划分的赛事生存竞赛", "联合会对阵概率矩阵"], liliSays: "欧洲防守，南美进攻，其余是混乱——我喜欢混乱。" },
    { positionFull: '左后卫',   description: "纪律严明，方法严谨，覆盖每一米地形。路线情报是环境引擎——绘制旅行距离、海拔变化和气候转换如何累积使球队疲惫。", features: ["危险区分类：死亡走廊→安全", "每次征程的气候过渡疲劳评分", "每支球队路线的海拔和热量暴露", "全部48支球队难度排名与简报"], liliSays: "最难的比赛有时是比赛前的那场比赛。" },
    { positionFull: '中场',     description: "比任何人都更早读懂紧张态势。小组悬念指数对每个小组运行729个阶段性结果场景，使用香农熵评分衡量每个小组真正的数学不可预测性。", features: ["每组729个场景分析引擎", "香农熵戏剧性评分0–100", "平静/升温/紧张/混乱分类", "黑马点名和资格对概率"], liliSays: "每个小组都讲述一个故事。有些是惊险小说。" },
    { positionFull: '攻击中场', description: "创造性组织核心。平行时间线是反事实引擎——改变任何球队的实际实力，观察小组如何逐场、逐次资格赛重新划定。", features: ["实力差值覆盖范围−20到+20", "逐场概率比较：基础版vs替代版", "资格赛变化和预期积分分析", "对小组内全部3个对手的连锁影响"], liliSays: "如果阿根廷更弱会怎样？如果摩洛哥更强会怎样？我都能回答。" },
    { positionFull: '中场',     description: "耐力与覆盖范围。累计图追踪球队在整个小组赛阶段预期赛事势头的增长或崩溃——逐场比赛，逐日追踪。", features: ["每队3场比赛日的预期积分轨迹", "同组多队比较叠加", "中途势头转变检测", "与赛前预测的视觉偏差"], liliSays: "重要的不是你从哪里开始，而是你要去哪里。" },
    { positionFull: '右边锋',   description: "快速、直接、攻击空间。队伍路线绘制任何球队将在2026年世界杯场馆进行的完整地理和环境旅程——每个场馆逐一提供情报。", features: ["按比赛日绘制的完整征程路线", "每站的场馆环境档案", "场馆间的气候和海拔过渡说明", "总旅行距离和估计飞行时间"], liliSays: "在球被踢出之前，旅程已经开始。" },
    { positionFull: '前锋',     description: "决斗。纯粹的竞争本能。选择任何2026年世界杯球队，莉莉生成完整的预测档案——然后进行多达10,000个场景的蒙特卡洛赛事模拟。", features: ["逐场小组赛预测档案", "蒙特卡洛赛事模拟（1到10,000次运行）", "每个淘汰轮的胜出概率", "莉莉推理、危险信号和关键对手分析"], liliSays: "选择你的球队，我告诉你会发生什么。" },
    { positionFull: '左边锋',   description: "充满激情、私人化、始终向前。选择你的球队，跟随他们在整个赛事中的预测路径——从小组赛第一声哨声到决赛。", features: ["从小组赛到决赛的预测淘汰路径", "每场小组赛的胜/平/负概率", "淘汰赛每轮的晋级赔率", "莉莉战术洞察和每场比赛风险说明"], liliSays: "每位球迷都有权知道自己球队机会的真相。" },
  ]},

  // ─── Japanese ────────────────────────────────────────────────────────────────
  JP: { players: [
    { positionFull: 'ゴールキーパー',   description: "最後の情報防衛線。World Signalsは48チーム全体のフィールドを同時に監視し、気候ストレス、勢いの変化、構造的危険など、重要なシグナルが明白になる前に浮き上がらせます。", features: ["全グループにわたる多次元シグナル集約", "危険ゾーン分類と勢い検出", "環境・物流プレッシャースコアリング", "コンフェデレーション横断パターン認識エンジン"], liliSays: "私はすべてを見ているので、あなたは重要なことだけを見ればいいのです。" },
    { positionFull: '右サイドバック',   description: "戦術的で正確、まさに戦いが行われる場所に位置します。スタジアム情報はWC2026の16会場すべてを環境・物流・競技データでマッピング──すべてのピッチは異なるゲームです。", features: ["3カ国16会場のエコシステムプロファイル", "高度・暑さ・湿度のパフォーマンス指数", "会場ごとの移動ストレスモデリング", "スタジアムごとのトーナメント圧力係数"], liliSays: "すべてのピッチは異なるゲームです。私はすべてを知っています。" },
    { positionFull: 'センターバック',   description: "データの礎石。何も通過させません。ワールドテーブルは12グループ・48チームすべてを同時に追跡──資格数学、フォーム指標、ポイント予測を一つのクリーンなビューで。", features: ["12グループ・48チームのリアルタイム追跡", "チームごとの勝/引/負フォームドット", "ライブ資格確率オーバーレイ", "グループタイブレーカーシナリオ分析"], liliSays: "データの中に真実がある。いつも。" },
    { positionFull: 'センターバック',   description: "構造レベルの力と権威。連盟はグローバルサッカー権力の地形を描写します──誰が支配し、誰が驚かせ、タイトルはどこから来る可能性が最も高いかを。", features: ["6連盟の実力・シミュレーション分析", "地域別モンテカルロWC優勝確率", "フェーズごとのトーナメント生存レース", "連盟対戦確率マトリクス"], liliSays: "ヨーロッパは守る。南アメリカは攻める。残りは混沌──そして私は混沌が大好きです。" },
    { positionFull: '左サイドバック',   description: "規律的で方法論的、テレーンのすべてのメートルをカバーします。ルート情報は環境エンジンで、移動距離、高度変化、気候変化がどのように積み重なってフィールドを疲弊させるかをマッピングします。", features: ["危険ゾーン分類：死のコリドー→安全", "キャンペーンごとの気候移行疲労スコアリング", "チームルートごとの高度・暑さ暴露", "48チーム全体の難易度ランキングとブリーフィング"], liliSays: "最も難しい試合は、時として試合前の試合です。" },
    { positionFull: 'セントラルMF',     description: "誰よりも先に緊張を読み取ります。ドラマ指数はグループごとに729のグループステージ結果シナリオを実行し、シャノンエントロピーを使用して各グループが数学的にどれほど予測不可能かをスコアリングします。", features: ["グループごとの729シナリオ分析エンジン", "シャノンエントロピードラマスコア0–100", "CALM/BUILDING/TENSION/CHAOS分類", "ダークホース指摘と資格ペア確率"], liliSays: "すべてのグループが物語を語ります。いくつかはスリラーです。" },
    { positionFull: '攻撃的MF',         description: "創造的なプレーメーカー。並行タイムラインは反事実エンジンです──チームの実効強度を変えて、グループが試合ごとに再描画される様子を観察してください。", features: ["−20から+20の強度デルタオーバーライド", "試合ごとの確率比較：BASE vs ALT", "資格変化と期待ポイント分析", "3つのライバル全員への同時グループ波及効果"], liliSays: "アルゼンチンがもっと弱かったら？モロッコがもっと強かったら？両方答えます。" },
    { positionFull: 'セントラルMF',     description: "持久力と射程。累積グラフはチームの期待トーナメント勢いがグループステージ全体でどのように構築または崩壊するかを追跡します──試合ごと、日ごとに。", features: ["3試合日にわたるチームごとの期待ポイント軌跡", "同グループ内のマルチチーム比較オーバーレイ", "中間点での勢い変化検出", "トーナメント前予測からの視覚的乖離"], liliSays: "重要なのはどこから始めるかではありません。どこへ向かっているかです。" },
    { positionFull: '右ウィング',       description: "速く、直接的で、スペースを攻撃します。チームルートはWC2026会場を通じて任意のチームが行う完全な地理的・環境的旅程をマッピングします──各停車地での会場ごとのインテリジェンスを提供。", features: ["試合日ごとにマッピングされた完全なキャンペーンルート", "各停車地の会場環境プロファイル", "会場間の気候と高度移行ノート", "総移動距離と推定飛行時間"], liliSays: "ボールが蹴られる前に、旅はすでに始まっています。" },
    { positionFull: 'ストライカー',     description: "決闘。純粋な競争本能。WC2026チームを選択するとリリが完全な予測プロファイルを生成し、最大10,000シナリオのモンテカルロトーナメントシミュレーションを実行します。", features: ["試合ごとのグループステージ予測プロファイル", "モンテカルロトーナメントシミュレーション（1〜10,000実行）", "ノックアウトラウンドごとの勝利確率", "リリの推論、危険シグナル、主要対戦相手分析"], liliSays: "チームを選んでください。何が起こるか教えます。" },
    { positionFull: '左ウィング',       description: "情熱的で、個人的で、常に前進します。チームを選んでトーナメント全体を通じた予測パスを追跡──グループステージの最初の笛から決勝まで。", features: ["グループステージから決勝までの予測ノックアウトパス", "グループ試合ごとの勝/引/負確率", "ブラケットを通じたラウンドごとの生存オッズ", "試合ごとのリリ戦術インサイトとリスクノート"], liliSays: "すべてのファンはチームのチャンスについての真実を知る権利があります。" },
  ]},

  // ─── Korean ──────────────────────────────────────────────────────────────────
  KR: { players: [
    { positionFull: '골키퍼',           description: "마지막 정보 방어선. 월드 시그널은 48개 팀 전체를 동시에 감시하며, 기후 스트레스, 모멘텀 변화, 구조적 위험 등 중요한 신호가 명백해지기 전에 포착합니다.", features: ["모든 그룹에 걸친 다차원 신호 집계", "위험 구역 분류 및 모멘텀 감지", "환경 및 물류 압력 점수", "연맹 간 패턴 인식 엔진"], liliSays: "저는 모든 것을 봐서 당신은 중요한 것만 보면 됩니다." },
    { positionFull: '오른쪽 풀백',      description: "전술적이고 정확하며, 전투가 벌어지는 곳에 정확히 위치합니다. 스타디움 인텔리전스는 환경, 물류, 경쟁 데이터로 WC 2026의 16개 경기장을 모두 매핑합니다.", features: ["3개국 16개 경기장 생태계 프로파일", "고도, 더위, 습도 성능 지수", "경기장별 이동 스트레스 모델링", "경기장별 토너먼트 압력 계수"], liliSays: "모든 경기장은 다른 게임입니다. 저는 모두 알고 있습니다." },
    { positionFull: '센터백',           description: "데이터의 기반. 아무것도 통과시키지 않습니다. 월드 테이블은 12개 그룹과 48개 팀을 동시에 추적합니다 — 자격 수학, 폼 지표, 포인트 예측을 하나의 깔끔한 뷰로.", features: ["12개 그룹, 48개 팀 실시간 추적", "팀별 승/무/패 폼 점수", "라이브 자격 확률 오버레이", "그룹 타이브레이커 시나리오 분석"], liliSays: "데이터 속에 진실이 있습니다. 항상." },
    { positionFull: '센터백',           description: "구조적 차원의 힘과 권위. 연맹은 글로벌 축구 파워 지형을 매핑합니다 — 누가 지배하고, 누가 놀라게 하며, 우승이 어디서 올 가능성이 가장 높은지를.", features: ["6개 연맹 파워 및 시뮬레이션 분석", "지역별 몬테카를로 WC 우승 확률", "단계별 토너먼트 생존 레이스", "연맹 간 충돌 확률 매트릭스"], liliSays: "유럽은 수비합니다. 남미는 공격합니다. 나머지는 혼돈 — 저는 혼돈을 사랑합니다." },
    { positionFull: '왼쪽 풀백',        description: "규율적이고 체계적이며, 지형의 모든 미터를 커버합니다. 루트 인텔리전스는 환경 엔진으로, 이동 거리, 고도 변화, 기후 전환이 어떻게 누적되어 팀을 피로하게 만드는지 매핑합니다.", features: ["위험 구역 분류: 죽음의 코리도 → 안전", "캠페인별 기후 전환 피로 점수", "팀 루트별 고도 및 열기 노출", "48개 팀 전체 난이도 랭킹 및 브리핑"], liliSays: "가장 어려운 경기는 때때로 경기 전의 그 경기입니다." },
    { positionFull: '중앙 미드필더',    description: "누구보다 먼저 긴장을 읽습니다. 드라마 지수는 그룹당 729개의 그룹 단계 결과 시나리오를 실행하며, 섀넌 엔트로피를 사용해 각 그룹이 수학적으로 얼마나 예측 불가능한지 점수화합니다.", features: ["그룹당 729개 시나리오 분석 엔진", "섀넌 엔트로피 드라마 점수 0–100", "평온/고조/긴장/혼란 분류", "다크호스 지목 및 자격 쌍 확률"], liliSays: "모든 그룹은 이야기를 들려줍니다. 어떤 것들은 스릴러입니다." },
    { positionFull: '공격형 미드필더',  description: "창의적인 플레이메이커. 대안 타임라인은 반사실 엔진입니다 — 어떤 팀의 실효 강점을 바꾸고 그룹이 경기마다, 자격마다 어떻게 재구성되는지 지켜보세요.", features: ["−20에서 +20까지 강도 델타 재정의", "경기별 확률 비교: 기준 vs 대안", "자격 변화 및 예상 포인트 분석", "3개 라이벌 모두에 대한 동시 그룹 파급 효과"], liliSays: "아르헨티나가 더 약했다면? 모로코가 더 강했다면? 둘 다 대답합니다." },
    { positionFull: '중앙 미드필더',    description: "지구력과 범위. 누적 그래프는 팀의 예상 토너먼트 모멘텀이 전체 그룹 단계에 걸쳐 어떻게 구축되거나 붕괴되는지 추적합니다 — 경기마다, 날마다.", features: ["3개 경기일에 걸친 팀별 예상 포인트 궤적", "같은 그룹 내 다중 팀 비교 오버레이", "중간 지점에서의 모멘텀 변화 감지", "토너먼트 전 예측으로부터의 시각적 이탈"], liliSays: "중요한 것은 어디서 시작하느냐가 아닙니다. 어디로 가고 있느냐입니다." },
    { positionFull: '오른쪽 윙어',      description: "빠르고 직접적이며 공간을 공격합니다. 팀 루트는 WC 2026 경기장을 통해 모든 팀이 만들 전체 지리적·환경적 여정을 매핑합니다.", features: ["경기일별로 매핑된 전체 캠페인 루트", "각 기착지의 경기장 환경 프로파일", "경기장 간 기후 및 고도 전환 노트", "총 이동 거리 및 예상 비행 시간"], liliSays: "공이 차이기 전에, 여정은 이미 시작되었습니다." },
    { positionFull: '스트라이커',       description: "결투. 순수한 경쟁 본능. WC 2026 팀을 선택하면 릴리가 완전한 예측 프로파일을 생성합니다 — 그런 다음 최대 10,000개 시나리오에 걸쳐 몬테카를로 토너먼트 시뮬레이션을 실행합니다.", features: ["경기별 그룹 단계 예측 프로파일", "몬테카를로 토너먼트 시뮬레이션 (1~10,000회)", "각 녹아웃 라운드별 승리 확률", "릴리 추론, 위험 신호, 주요 상대 분석"], liliSays: "팀을 선택하세요. 무슨 일이 일어날지 알려드립니다." },
    { positionFull: '왼쪽 윙어',        description: "열정적이고 개인적이며 항상 앞으로 나아갑니다. 팀을 선택하고 그룹 단계의 첫 번째 휘슬부터 결승전까지 전체 토너먼트를 통한 예측 경로를 따라가세요.", features: ["그룹 단계부터 결승까지 예측 녹아웃 경로", "그룹 경기별 승/무/패 확률", "브래킷을 통한 라운드별 생존 배당률", "릴리 전술 인사이트 및 경기별 위험 노트"], liliSays: "모든 팬은 자신의 팀 기회에 대한 진실을 알 자격이 있습니다." },
  ]},

  // ─── Portuguese ──────────────────────────────────────────────────────────────
  PT: { players: [
    { positionFull: 'Guarda-Redes',     description: "A última linha de inteligência. World Signals observa os 48 equipas em campo simultaneamente, trazendo à superfície os sinais que importam antes de se tornarem óbvios — stress climático, mudanças de momentum, perigo estrutural.", features: ["Agregação multidimensional de sinais em todos os grupos", "Classificação de zonas de perigo e detecção de momentum", "Pontuação de pressão ambiental e logística", "Motor de reconhecimento de padrões entre confederações"], liliSays: "Observo tudo para que só precises de observar o que conta." },
    { positionFull: 'Lateral Direito',  description: "Táctico, preciso, posicionado exactamente onde a batalha é travada. Stadium Intelligence mapeia todos os 16 recintos do Mundial 2026 com dados ambientais, logísticos e competitivos — cada relvado é um jogo diferente.", features: ["Perfis de ecossistema de 16 recintos em 3 países", "Índices de desempenho por altitude, calor e humidade", "Modelação do stress de viagem por paragem", "Coeficiente de pressão do torneio por estádio"], liliSays: "Cada relvado é um jogo diferente. Conheço-os todos." },
    { positionFull: 'Defesa Central',   description: "A base de dados. Nada passa por ela. A Tabela Mundial acompanha todos os 12 grupos e 48 equipas simultaneamente — matemática de qualificação, indicadores de forma e projecções de pontos numa vista limpa.", features: ["12 grupos, 48 equipas monitoradas em tempo real", "Pontos de forma V/E/D por equipa", "Sobreposição de probabilidade de qualificação em directo", "Análise de cenários de desempate por grupo"], liliSays: "Nos dados, a verdade. Sempre." },
    { positionFull: 'Defesa Central',   description: "Poder e autoridade ao nível estrutural. Confederações mapeia a paisagem global do poder futebolístico — quem domina, quem surpreende, e de onde o título virá mais provavelmente.", features: ["Análise de poder e simulação de 6 confederações", "Probabilidade Monte Carlo de vencer o Mundial por região", "Corrida de sobrevivência no torneio por fase", "Matriz de probabilidade de confronto entre confederações"], liliSays: "A Europa defende. A América do Sul ataca. O resto é caos — e eu adoro o caos." },
    { positionFull: 'Lateral Esquerdo', description: "Disciplinado, metódico, cobre cada metro de terreno. Route Intelligence é o motor ambiental — mapeando como as distâncias de viagem, mudanças de altitude e transições climáticas se acumulam para fatigar o campo.", features: ["Classificação de zonas de perigo: Corredor da Morte → Seguro", "Pontuação de fadiga de transição climática por campanha", "Exposição a altitude e calor por rota de equipa", "Ranking completo de dificuldade das 48 equipas com briefings"], liliSays: "O jogo mais difícil é às vezes o que precede o jogo." },
    { positionFull: 'Médio Central',    description: "Lê a tensão antes de todos. O Índice de Drama corre 729 cenários de resultados de fase de grupos por grupo, usando a entropia de Shannon para classificar o quão matematicamente imprevisível cada grupo realmente é.", features: ["Motor analítico de 729 cenários por grupo", "Pontuação de drama de entropia de Shannon 0–100", "Classificação CALMO / CRESCENDO / TENSÃO / CAOS", "Sinalizações de azarão e probabilidades de pares de qualificação"], liliSays: "Cada grupo conta uma história. Alguns são thrillers." },
    { positionFull: 'Médio Ofensivo',   description: "O criativo organizador. Linha do Tempo Alternativa é o motor contrafactual — muda a força efectiva de qualquer equipa e observa como o grupo se redesenha, jogo a jogo, qualificação a qualificação.", features: ["Override de delta de força de −20 a +20", "Comparação de probabilidade por jogo: BASE vs ALT", "Análise de mudança de qualificação e pontos esperados", "Efeito de ondulação no grupo nos 3 rivais simultaneamente"], liliSays: "E se a Argentina fosse mais fraca? E se Marrocos fosse mais forte? Respondo a ambas." },
    { positionFull: 'Médio Central',    description: "Resistência e alcance. O Gráfico Cumulativo acompanha como o momentum esperado de torneio das equipas se constrói ou colapsa ao longo de toda a fase de grupos — jogo a jogo, dia a dia.", features: ["Trajectória de pontos esperados por equipa em 3 jornadas", "Sobreposição de comparação multi-equipa no mesmo grupo", "Detecção de mudança de momentum no ponto médio", "Divergência visual das projecções pré-torneio"], liliSays: "Não é de onde começas que importa. É para onde vais." },
    { positionFull: 'Extremo Direito',  description: "Rápido, directo, ataca o espaço. Team Route mapeia a jornada geográfica e ambiental completa que qualquer equipa fará pelos recintos do Mundial 2026 — com inteligência recinto a recinto em cada paragem.", features: ["Rota completa de campanha mapeada por jornada", "Perfil ambiental do recinto por paragem", "Notas de transição climática e de altitude entre recintos", "Distância total de viagem e horas de voo estimadas"], liliSays: "Antes de a bola ser chutada, a jornada já começou." },
    { positionFull: 'Avançado',         description: "O duelo. Puro instinto competitivo. Selecciona qualquer equipa do Mundial 2026 e Lili gera um perfil de previsão completo — depois corre uma simulação Monte Carlo do torneio com até 10.000 cenários.", features: ["Perfil de previsão da fase de grupos jogo a jogo", "Simulação Monte Carlo do torneio (1 a 10.000 runs)", "Probabilidade de vitória por ronda de eliminatória", "Raciocínio de Lili, sinais de perigo e análise de adversários-chave"], liliSays: "Escolhe a tua equipa. Digo-te o que acontece." },
    { positionFull: 'Extremo Esquerdo', description: "Apaixonada, pessoal, sempre em frente. Escolhe a tua equipa e segue o seu caminho projectado ao longo de todo o torneio — desde o primeiro apito da fase de grupos até à final.", features: ["Caminho de eliminatória projectado desde a fase de grupos até à final", "Probabilidade V/E/D por jogo de grupo", "Probabilidades de sobrevivência ronda a ronda no quadro", "Análise táctica de Lili e nota de risco por jogo"], liliSays: "Cada adepto merece conhecer a verdade sobre as hipóteses da sua equipa." },
  ]},

  // ─── Arabic ──────────────────────────────────────────────────────────────────
  AR: { players: [
    { positionFull: 'حارس المرمى',  description: "خط الاستخبارات الأخير. تراقب إشارات العالم ميدان الـ48 فريقًا بالكامل في آنٍ واحد، مستخرجةً الإشارات المهمة قبل أن تصبح واضحة — إجهاد مناخي، تحولات في الزخم، وخطر هيكلي.", features: ["تجميع متعدد الأبعاد للإشارات عبر جميع المجموعات", "تصنيف مناطق الخطر وكشف الزخم", "تقييم الضغط البيئي واللوجستي", "محرك التعرف على الأنماط عبر الاتحادات"], liliSays: "أراقب كل شيء لتحتاج أنت فقط إلى مراقبة ما يهم." },
    { positionFull: 'ظهير أيمن',    description: "تكتيكي، دقيق، في موقعه الصحيح أينما دارت المعركة. يرسم ذكاء الملاعب خريطة الملاعب الـ16 لكأس العالم 2026 بالبيانات البيئية واللوجستية والتنافسية — كل ملعب هو لعبة مختلفة.", features: ["ملفات تعريف للملاعب الـ16 في 3 دول", "مؤشرات الأداء للارتفاع والحرارة والرطوبة", "نمذجة إجهاد السفر لكل محطة ملعب", "معامل ضغط البطولة لكل ملعب"], liliSays: "كل ملعب لعبة مختلفة. أنا أعرفها جميعًا." },
    { positionFull: 'قلب الدفاع',   description: "الركيزة البيانية. لا شيء يفوته. يتتبع الجدول العالمي الـ12 مجموعة والـ48 فريقًا في آنٍ واحد — رياضيات التأهل، ومؤشرات الشكل، وتوقعات النقاط في عرض واحد واضح.", features: ["12 مجموعة، 48 فريقًا مُتابَعًا في الوقت الفعلي", "نقاط شكل الفوز/التعادل/الخسارة لكل فريق", "تراكب احتمال التأهل المباشر", "تحليل سيناريوهات الفاصل بين الفرق"], liliSays: "في البيانات الحقيقة. دائمًا." },
    { positionFull: 'قلب الدفاع',   description: "القوة والسلطة على المستوى الهيكلي. ترسم الاتحادات خريطة مشهد القوى الكروية العالمي — من يهيمن، ومن يفاجئ، ومن أين سيأتي اللقب على الأرجح.", features: ["تحليل القوة ومحاكاة الاتحادات الـ6", "احتمال الفوز بكأس العالم حسب المنطقة (مونت كارلو)", "سباق البقاء في البطولة حسب المرحلة", "مصفوفة احتمال المواجهة بين الاتحادات"], liliSays: "أوروبا تدافع. أمريكا الجنوبية تهاجم. الباقي فوضى — وأنا أحب الفوضى." },
    { positionFull: 'ظهير أيسر',    description: "منضبط، منهجي، يغطي كل متر من الأرض. ذكاء المسار هو المحرك البيئي — يرسم خريطة لكيفية تراكم مسافات السفر وتحولات الارتفاع والتحولات المناخية لإرهاق الفرق.", features: ["تصنيف مناطق الخطر: ممر الموت ← آمن", "تقييم إرهاق التحولات المناخية لكل حملة", "التعرض للارتفاع والحرارة لكل مسار فريق", "التصنيف الكامل لصعوبة الـ48 فريقًا مع إحاطات"], liliSays: "أصعب مباراة أحيانًا هي تلك التي تسبق المباراة." },
    { positionFull: 'وسط دفاعي',    description: "يقرأ التوتر قبل أي أحد آخر. يُشغّل مؤشر الإثارة 729 سيناريو لنتائج الدور الجماعي لكل مجموعة، مستخدمًا إنتروبيا شانون لتقييم مدى الغموض الرياضي الحقيقي لكل مجموعة.", features: ["محرك تحليلي بـ729 سيناريو لكل مجموعة", "درجة الإثارة بإنتروبيا شانون 0–100", "تصنيف هادئ / متصاعد / توتر / فوضى", "تنبيه المفاجآت واحتمالات الأزواج المؤهِّلة"], liliSays: "كل مجموعة تحكي قصة. بعضها من نوع التشويق والإثارة." },
    { positionFull: 'وسط هجومي',    description: "صانع اللعب الإبداعي. الجدول الزمني البديل هو محرك السيناريوهات البديلة — غيّر القوة الفعلية لأي فريق وشاهد كيف تُعيد المجموعة رسم نفسها مباراةً تلو مباراة.", features: ["تعديل فارق القوة من −20 إلى +20", "مقارنة الاحتمالات لكل مباراة: أساسي مقابل بديل", "تحليل تحول التأهل والنقاط المتوقعة", "أثر التموج على الـ3 منافسين في المجموعة في آنٍ واحد"], liliSays: "ماذا لو كانت الأرجنتين أضعف؟ ماذا لو كان المغرب أقوى؟ أجيب على كليهما." },
    { positionFull: 'وسط دفاعي',    description: "القدرة على التحمل والمدى. يتتبع الرسم التراكمي كيف يتشكل الزخم المتوقع للفرق في البطولة أو ينهار عبر الدور الجماعي بأكمله — مباراةً تلو مباراة، يومًا تلو يوم.", features: ["مسار النقاط المتوقعة لكل فريق على 3 أيام مباريات", "تراكب مقارنة متعدد الفرق في المجموعة ذاتها", "كشف تحول الزخم عند منتصف الطريق", "التباين البصري عن التوقعات السابقة للبطولة"], liliSays: "المهم ليس من أين تبدأ. المهم إلى أين أنت ذاهب." },
    { positionFull: 'جناح أيمن',    description: "سريع، مباشر، يهاجم المساحة. يرسم مسار الفريق الرحلة الجغرافية والبيئية الكاملة لأي فريق عبر ملاعب كأس العالم 2026 — مع معلومات استخباراتية لكل ملعب.", features: ["مسار الحملة الكاملة مُعدّ حسب يوم المباراة", "الملف البيئي للملعب في كل محطة", "ملاحظات التحول المناخي والارتفاع بين الملاعب", "إجمالي مسافة السفر وساعات الطيران المقدرة"], liliSays: "قبل أن تُركل الكرة، تكون الرحلة قد بدأت بالفعل." },
    { positionFull: 'مهاجم',        description: "المبارزة. الغريزة التنافسية الخالصة. اختر أي فريق من كأس العالم 2026 وتولّد ليلي ملف تنبؤ كاملًا — ثم تُشغّل محاكاة مونت كارلو للبطولة عبر ما يصل إلى 10,000 سيناريو.", features: ["ملف التنبؤ بالدور الجماعي مباراةً تلو مباراة", "محاكاة مونت كارلو للبطولة (من 1 إلى 10,000 تشغيل)", "احتمالية الفوز لكل جولة إقصائية", "تحليل ليلي وإشارات الخطر والمنافسين الرئيسيين"], liliSays: "اختر فريقك. سأخبرك بما سيحدث." },
    { positionFull: 'جناح أيسر',    description: "شغوفة، شخصية، تتقدم دائمًا. اختر فريقك وتابع مساره المتوقع عبر البطولة كاملةً — من صافرة البداية في الدور الجماعي حتى النهائي.", features: ["مسار الإقصاء المتوقع من الدور الجماعي إلى النهائي", "احتمال الفوز/التعادل/الخسارة لكل مباراة في الدور الجماعي", "حظوظ البقاء جولةً تلو جولة في الجدول الإقصائي", "رؤية ليلي التكتيكية وملاحظة المخاطر لكل مباراة"], liliSays: "كل مشجع يستحق معرفة حقيقة فرص فريقه." },
  ]},
};
