// Auto-generated by scripts/sync-standings.ts — do not edit manually.
// Refreshed every 4 hours during the tournament via GitHub Actions.

export type StandingStatus = 'QUALIFIED' | 'ALIVE' | 'AT-RISK' | 'ELIMINATED' | 'UPCOMING';

export interface GroupStanding {
  group:  string;
  team:   string;
  rank:   number;
  played: number;
  won:    number;
  drawn:  number;
  lost:   number;
  gf:     number;
  ga:     number;
  gd:     number;
  pts:    number;
  status: StandingStatus;
}

// All 12 groups (A–L), populated once the tournament starts.
export const GROUP_STANDINGS: GroupStanding[] = [
  { group: "H", team: "Saudi Arabia", rank: 4, played: 3, won: 0, drawn: 2, lost: 1, gf: 1, ga: 5, gd: -4, pts: 2, status: 'ELIMINATED' },
  { group: "H", team: "Spain", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 5, ga: 0, gd: 5, pts: 7, status: 'QUALIFIED' },
  { group: "H", team: "Cape Verde Islands", rank: 2, played: 3, won: 0, drawn: 3, lost: 0, gf: 2, ga: 2, gd: 0, pts: 3, status: 'ALIVE' },
  { group: "H", team: "Uruguay", rank: 3, played: 3, won: 0, drawn: 2, lost: 1, gf: 3, ga: 4, gd: -1, pts: 2, status: 'ELIMINATED' },
  { group: "A", team: "Mexico", rank: 1, played: 3, won: 3, drawn: 0, lost: 0, gf: 6, ga: 0, gd: 6, pts: 9, status: 'QUALIFIED' },
  { group: "A", team: "South Africa", rank: 2, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 3, gd: -1, pts: 4, status: 'QUALIFIED' },
  { group: "A", team: "South Korea", rank: 3, played: 3, won: 1, drawn: 0, lost: 2, gf: 2, ga: 3, gd: -1, pts: 3, status: 'AT-RISK' },
  { group: "A", team: "Czech Republic", rank: 4, played: 3, won: 0, drawn: 1, lost: 2, gf: 2, ga: 6, gd: -4, pts: 1, status: 'ELIMINATED' },
  { group: "I", team: "France", rank: 1, played: 3, won: 3, drawn: 0, lost: 0, gf: 10, ga: 2, gd: 8, pts: 9, status: 'QUALIFIED' },
  { group: "I", team: "Norway", rank: 2, played: 3, won: 2, drawn: 0, lost: 1, gf: 8, ga: 7, gd: 1, pts: 6, status: 'QUALIFIED' },
  { group: "I", team: "Senegal", rank: 3, played: 3, won: 1, drawn: 0, lost: 2, gf: 8, ga: 6, gd: 2, pts: 3, status: 'AT-RISK' },
  { group: "I", team: "Iraq", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 1, ga: 12, gd: -11, pts: 0, status: 'ELIMINATED' },
  { group: "B", team: "Switzerland", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 7, ga: 3, gd: 4, pts: 7, status: 'QUALIFIED' },
  { group: "B", team: "Canada", rank: 2, played: 3, won: 1, drawn: 1, lost: 1, gf: 8, ga: 3, gd: 5, pts: 4, status: 'QUALIFIED' },
  { group: "B", team: "Bosnia & Herzegovina", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 5, ga: 6, gd: -1, pts: 4, status: 'ALIVE' },
  { group: "B", team: "Qatar", rank: 4, played: 3, won: 0, drawn: 1, lost: 2, gf: 2, ga: 10, gd: -8, pts: 1, status: 'ELIMINATED' },
  { group: "J", team: "Argentina", rank: 1, played: 3, won: 3, drawn: 0, lost: 0, gf: 8, ga: 1, gd: 7, pts: 9, status: 'QUALIFIED' },
  { group: "J", team: "Austria", rank: 2, played: 3, won: 1, drawn: 1, lost: 1, gf: 6, ga: 6, gd: 0, pts: 4, status: 'QUALIFIED' },
  { group: "J", team: "Algeria", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 5, ga: 7, gd: -2, pts: 4, status: 'ALIVE' },
  { group: "J", team: "Jordan", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 3, ga: 8, gd: -5, pts: 0, status: 'ELIMINATED' },
  { group: "C", team: "Brazil", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 7, ga: 1, gd: 6, pts: 7, status: 'QUALIFIED' },
  { group: "C", team: "Morocco", rank: 2, played: 3, won: 2, drawn: 1, lost: 0, gf: 6, ga: 3, gd: 3, pts: 7, status: 'QUALIFIED' },
  { group: "C", team: "Scotland", rank: 3, played: 3, won: 1, drawn: 0, lost: 2, gf: 1, ga: 4, gd: -3, pts: 3, status: 'AT-RISK' },
  { group: "C", team: "Haiti", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 2, ga: 8, gd: -6, pts: 0, status: 'ELIMINATED' },
  { group: "K", team: "Colombia", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 4, ga: 1, gd: 3, pts: 7, status: 'QUALIFIED' },
  { group: "K", team: "Portugal", rank: 2, played: 3, won: 1, drawn: 2, lost: 0, gf: 6, ga: 1, gd: 5, pts: 5, status: 'QUALIFIED' },
  { group: "K", team: "Congo DR", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 4, ga: 3, gd: 1, pts: 4, status: 'ALIVE' },
  { group: "K", team: "Uzbekistan", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 2, ga: 11, gd: -9, pts: 0, status: 'ELIMINATED' },
  { group: "L", team: "England", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 6, ga: 2, gd: 4, pts: 7, status: 'QUALIFIED' },
  { group: "L", team: "Croatia", rank: 2, played: 3, won: 2, drawn: 0, lost: 1, gf: 5, ga: 5, gd: 0, pts: 6, status: 'QUALIFIED' },
  { group: "L", team: "Ghana", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 2, gd: 0, pts: 4, status: 'ALIVE' },
  { group: "L", team: "Panama", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 0, ga: 4, gd: -4, pts: 0, status: 'ELIMINATED' },
  { group: "D", team: "USA", rank: 1, played: 3, won: 2, drawn: 0, lost: 1, gf: 8, ga: 4, gd: 4, pts: 6, status: 'QUALIFIED' },
  { group: "D", team: "Australia", rank: 2, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 2, gd: 0, pts: 4, status: 'QUALIFIED' },
  { group: "D", team: "Paraguay", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 4, gd: -2, pts: 4, status: 'ALIVE' },
  { group: "D", team: "Türkiye", rank: 4, played: 3, won: 1, drawn: 0, lost: 2, gf: 3, ga: 5, gd: -2, pts: 3, status: 'ELIMINATED' },
  { group: "Stage", team: "Congo DR", rank: 1, played: 3, won: 1, drawn: 1, lost: 1, gf: 4, ga: 3, gd: 1, pts: 4, status: 'QUALIFIED' },
  { group: "Stage", team: "Sweden", rank: 2, played: 3, won: 1, drawn: 1, lost: 1, gf: 7, ga: 7, gd: 0, pts: 4, status: 'QUALIFIED' },
  { group: "Stage", team: "Ghana", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 2, gd: 0, pts: 4, status: 'ALIVE' },
  { group: "Stage", team: "Ecuador", rank: 4, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 2, gd: 0, pts: 4, status: 'AT-RISK' },
  { group: "Stage", team: "Bosnia & Herzegovina", rank: 5, played: 3, won: 1, drawn: 1, lost: 1, gf: 5, ga: 6, gd: -1, pts: 4, status: 'AT-RISK' },
  { group: "Stage", team: "Algeria", rank: 6, played: 3, won: 1, drawn: 1, lost: 1, gf: 5, ga: 7, gd: -2, pts: 4, status: 'AT-RISK' },
  { group: "Stage", team: "Paraguay", rank: 7, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 4, gd: -2, pts: 4, status: 'AT-RISK' },
  { group: "Stage", team: "Senegal", rank: 8, played: 3, won: 1, drawn: 0, lost: 2, gf: 8, ga: 6, gd: 2, pts: 3, status: 'ELIMINATED' },
  { group: "Stage", team: "Iran", rank: 9, played: 3, won: 0, drawn: 3, lost: 0, gf: 3, ga: 3, gd: 0, pts: 3, status: 'ELIMINATED' },
  { group: "Stage", team: "South Korea", rank: 10, played: 3, won: 1, drawn: 0, lost: 2, gf: 2, ga: 3, gd: -1, pts: 3, status: 'ELIMINATED' },
  { group: "Stage", team: "Scotland", rank: 11, played: 3, won: 1, drawn: 0, lost: 2, gf: 1, ga: 4, gd: -3, pts: 3, status: 'ELIMINATED' },
  { group: "Stage", team: "Uruguay", rank: 12, played: 3, won: 0, drawn: 2, lost: 1, gf: 3, ga: 4, gd: -1, pts: 2, status: 'ELIMINATED' },
  { group: "E", team: "Germany", rank: 1, played: 3, won: 2, drawn: 0, lost: 1, gf: 10, ga: 4, gd: 6, pts: 6, status: 'QUALIFIED' },
  { group: "E", team: "Ivory Coast", rank: 2, played: 3, won: 2, drawn: 0, lost: 1, gf: 4, ga: 2, gd: 2, pts: 6, status: 'QUALIFIED' },
  { group: "E", team: "Ecuador", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 2, ga: 2, gd: 0, pts: 4, status: 'ALIVE' },
  { group: "E", team: "Curaçao", rank: 4, played: 3, won: 0, drawn: 1, lost: 2, gf: 1, ga: 9, gd: -8, pts: 1, status: 'ELIMINATED' },
  { group: "F", team: "Netherlands", rank: 1, played: 3, won: 2, drawn: 1, lost: 0, gf: 10, ga: 4, gd: 6, pts: 7, status: 'QUALIFIED' },
  { group: "F", team: "Japan", rank: 2, played: 3, won: 1, drawn: 2, lost: 0, gf: 7, ga: 3, gd: 4, pts: 5, status: 'QUALIFIED' },
  { group: "F", team: "Sweden", rank: 3, played: 3, won: 1, drawn: 1, lost: 1, gf: 7, ga: 7, gd: 0, pts: 4, status: 'ALIVE' },
  { group: "F", team: "Tunisia", rank: 4, played: 3, won: 0, drawn: 0, lost: 3, gf: 2, ga: 12, gd: -10, pts: 0, status: 'ELIMINATED' },
  { group: "G", team: "Belgium", rank: 1, played: 3, won: 1, drawn: 2, lost: 0, gf: 6, ga: 2, gd: 4, pts: 5, status: 'QUALIFIED' },
  { group: "G", team: "Egypt", rank: 2, played: 3, won: 1, drawn: 2, lost: 0, gf: 5, ga: 3, gd: 2, pts: 5, status: 'QUALIFIED' },
  { group: "G", team: "Iran", rank: 3, played: 3, won: 0, drawn: 3, lost: 0, gf: 3, ga: 3, gd: 0, pts: 3, status: 'AT-RISK' },
  { group: "G", team: "New Zealand", rank: 4, played: 3, won: 0, drawn: 1, lost: 2, gf: 4, ga: 10, gd: -6, pts: 1, status: 'ELIMINATED' },
];

export const STANDINGS_LAST_UPDATED = '2026-07-06T05:05:13.516Z';
