// Habitual formations for all 48 WC 2026 nations.
// Sourced from RotoWire group previews, ESPN predicted XIs, Squawka tactical analyses (2026).
// Updated by scripts/sync-lineups.ts when web sources provide confirmed data.

export const TEAM_FORMATIONS_BASELINE: Record<string, string> = {
  Algeria:              '4-3-3',
  Argentina:            '4-2-3-1',
  Australia:            '3-4-2-1',
  Austria:              '4-2-3-1',
  Belgium:              '4-2-3-1',
  'Bosnia & Herzegovina': '4-4-2',
  Brazil:               '4-2-3-1',
  Canada:               '4-4-2',
  'Cape Verde Islands': '4-2-3-1',
  Colombia:             '4-2-3-1',
  'Congo DR':           '4-3-3',
  Croatia:              '4-2-3-1',
  'Curaçao':            '4-3-3',
  'Czech Republic':     '4-2-3-1',
  Ecuador:              '4-2-3-1',
  Egypt:                '4-3-3',
  England:              '4-2-3-1',
  France:               '4-2-3-1',
  Germany:              '4-2-3-1',
  Ghana:                '4-2-3-1',
  Haiti:                '4-2-3-1',
  Iran:                 '4-3-3',
  Iraq:                 '4-4-2',
  'Ivory Coast':        '4-3-3',
  Japan:                '3-4-2-1',
  Jordan:               '4-5-1',
  Mexico:               '4-3-3',
  Morocco:              '4-3-3',
  Netherlands:          '4-2-3-1',
  'New Zealand':        '4-2-3-1',
  Norway:               '4-3-3',
  Panama:               '3-4-2-1',
  Paraguay:             '4-2-3-1',
  Portugal:             '4-2-3-1',
  Qatar:                '4-3-3',
  'Saudi Arabia':       '4-3-3',
  Scotland:             '4-2-3-1',
  Senegal:              '4-3-3',
  'South Africa':       '4-2-3-1',
  'South Korea':        '3-4-2-1',
  Spain:                '4-3-3',
  Sweden:               '3-4-2-1',
  Switzerland:          '4-2-3-1',
  Tunisia:              '4-2-3-1',
  'Türkiye':            '4-2-3-1',
  USA:                  '4-2-3-1',
  Uruguay:              '4-4-2',
  Uzbekistan:           '3-4-2-1',
};
